Hannah-Sten/TeXiFy-IDEA

- src/nl/rubensten/texifyidea/TexifyIcons.java
- src/nl/rubensten/texifyidea/file/FileExtensionMatcher.java
- src/nl/rubensten/texifyidea/file/FileNameMatcher.java
- src/nl/rubensten/texifyidea/gutter/LatexNavigationGutter.java
- src/nl/rubensten/texifyidea/insight/LatexParameterInfoHandler.java
- src/nl/rubensten/texifyidea/lang/LatexNoMathCommand.java
- src/nl/rubensten/texifyidea/lang/RequiredArgument.java
- src/nl/rubensten/texifyidea/lang/RequiredFileArgument.java
`\include`, `\includeonly`, and `\bibliography` now also get navigation icons. The new system allows an easier method to add support for more commands.
- Refactored `LatexNavigationGutter`
- Added `TexifyIcons#getIconFromExtension(String)`
> Added more advanced navigation gutter system.

- gen/nl/rubensten/texifyidea/grammar/LatexLexer.java
- gen/nl/rubensten/texifyidea/parser/LatexParser.java
- gen/nl/rubensten/texifyidea/psi/LatexBeginCommand.java
- gen/nl/rubensten/texifyidea/psi/LatexEndCommand.java
- gen/nl/rubensten/texifyidea/psi/LatexEnvironment.java
- gen/nl/rubensten/texifyidea/psi/LatexNoMathContent.java
- gen/nl/rubensten/texifyidea/psi/LatexTypes.java
- gen/nl/rubensten/texifyidea/psi/LatexVisitor.java
- gen/nl/rubensten/texifyidea/psi/impl/LatexBeginCommandImpl.java
- gen/nl/rubensten/texifyidea/psi/impl/LatexEndCommandImpl.java
- gen/nl/rubensten/texifyidea/psi/impl/LatexEnvironmentImpl.java
- gen/nl/rubensten/texifyidea/psi/impl/LatexNoMathContentImpl.java
- src/nl/rubensten/texifyidea/formatting/LatexBlock.java
- src/nl/rubensten/texifyidea/grammar/Latex.bnf
- src/nl/rubensten/texifyidea/grammar/LatexLexer.flex
- src/nl/rubensten/texifyidea/highlighting/LatexSyntaxHighlighter.java
Fixes issue #16.
Automatically indent within LaTeX environments. As a bonus, the auto reformatter will indent environment contents as well.
Compatibility note: to accomplish this, the grammar needed to be changed such that `\begin` and `\end` could be distinguished from other commands at token level and hence in the parse tree.
> Recognize indent within LaTeX environment

- src/nl/rubensten/texifyidea/highlighting/LatexTypedHandler.java
Closes #15.
Note: this ignores display math environment support with primitive `$$ ... $$` delimiters for now, as inserting `$$<cursor>$$` is not easily achievable anymore. However, this will come when such display math environments are supported by the parser.
> Caret run over closing `$` in inline math environment

- resources/META-INF/plugin.xml
- resources/liveTemplates/LaTeX.xml
- resources/liveTemplates/hidden/LaTeX.xml
- src/nl/rubensten/texifyidea/completion/LatexCommandProvider.java
- src/nl/rubensten/texifyidea/completion/LatexCompletionContributor.java
- src/nl/rubensten/texifyidea/completion/handlers/LatexNoMathInsertHandler.java
- src/nl/rubensten/texifyidea/lang/LatexMode.java
- src/nl/rubensten/texifyidea/templates/LatexContext.java
- src/nl/rubensten/texifyidea/templates/LatexLiveTemplateProvider.java
To make life (much) easier, environment autocomplete has arrived! Upon inserting `\begin` from autocomplete, now `\end` will be inserted as well. In addition, common environment names are being suggested.
> Live template for environments

- resources/META-INF/plugin.xml
- src/nl/rubensten/texifyidea/folding/LatexEnvironmentFoldingBuilder.java
Expand and collapse of LaTeX environments. Useful for when your document is so complex and large that you have to hide parts of it from yourself.
Supports nested environments as well.
> Folding for environments.

- gen/nl/rubensten/texifyidea/grammar/LatexLexer.java
- gen/nl/rubensten/texifyidea/parser/LatexParser.java
- gen/nl/rubensten/texifyidea/psi/LatexTypes.java
- src/nl/rubensten/texifyidea/grammar/Latex.bnf
- src/nl/rubensten/texifyidea/grammar/LatexLexer.flex
- src/nl/rubensten/texifyidea/highlighting/LatexPairedBraceMatcher.java
Fixes #38. Parentheses are now matched to a dedicated token type `OPEN_PAREN` and `CLOSE_PAREN` to make this possible.
> Parentheses matching

- gen/nl/rubensten/texifyidea/grammar/LatexLexer.java
- gen/nl/rubensten/texifyidea/parser/LatexParser.java
- gen/nl/rubensten/texifyidea/psi/LatexTypes.java
- src/nl/rubensten/texifyidea/grammar/Latex.bnf
- src/nl/rubensten/texifyidea/grammar/LatexLexer.flex
- src/nl/rubensten/texifyidea/highlighting/LatexPairedBraceMatcher.java
Fixes #31. Changed parser to allow non-matching brackets in math mode. `[` and `]` are now different token types inside and outside of math mode.
Question for review: do we still provide bracket matching (though not always right)? Advantage is that it introduces close-completion on typing the opening bracket, but can be annoying.
> Allow non-matching brackets in math mode

- gen/nl/rubensten/texifyidea/grammar/LatexLexer.java
- src/nl/rubensten/texifyidea/grammar/LatexLexer.flex
Fixed an issue introduced in `b0.2` which prevented the recognition of inline math environment placed after a displaymath environment.
Made this a pull request for changelog purposes.
> Fixed lexer issue with displaymath environment

- src/nl/rubensten/texifyidea/completion/handlers/LatexCommandArgumentInsertHandler.java
- When replacing a command via autocomplete, no `{}` will be inserted if there already are braces.
- Additionally, the cursor will skip to the end of the first required argument.
Awesome illustrating gif:
> Fixed #49: Replacing a command skips over the first required argument.

- src/nl/rubensten/texifyidea/structure/LatexIncludePresentation.java
- src/nl/rubensten/texifyidea/structure/LatexPresentationFactory.java
- src/nl/rubensten/texifyidea/structure/LatexStructureViewElement.java
- src/nl/rubensten/texifyidea/structure/filter/LatexIncludesFilter.java
- See #50: `\input`-esque includes are now present in the structure view.
Screenshot:
> Fixed #50: \input commands now show up as include in the structure view.

- README.md
- src/nl/rubensten/texifyidea/completion/LatexCompletionContributor.java
- src/nl/rubensten/texifyidea/completion/LatexFileProvider.java
- src/nl/rubensten/texifyidea/structure/LatexStructureViewElement.java
- Added autocomplete for files and directories for command arguments that take a file argument.
- When entered a directory, the window disappears and WONT reappear when adding a slash. You have to either use `CTRL`+`SPACE` or type the first letter to let it reappear. It does do silly things when using dots, however.
- Fixed a NPE when the structure view tries to get the structure of a non-existent include.
Screenshot:
> Fixed #51: Directory completion

- gen/nl/rubensten/texifyidea/psi/impl/LatexCommandsImpl.java
- src/nl/rubensten/texifyidea/completion/LatexCompletionContributor.java
- src/nl/rubensten/texifyidea/completion/LatexReferenceProvider.java
- src/nl/rubensten/texifyidea/reference/LatexLabelReference.java
- src/nl/rubensten/texifyidea/util/TexifyUtil.java
Ctrl+click and Ctrl+B or whatever is related works on label references inside a `\ref{}` command.
Also changed the implementation of the reference completion, since this is provided by `PsiReference`.
Closes #46
> Label reference 'Go to declaration'

- src/nl/rubensten/texifyidea/run/LatexCompiler.java
- src/nl/rubensten/texifyidea/run/LatexRunConfiguration.java
- src/nl/rubensten/texifyidea/run/LatexSettingsEditor.java
Added the ability to specify a custom compiler executable path in run configurations. This should resolve #25, but I cannot test this beforehand since I have no OSX machine available right now.
A custom path must match the selected compiler. Only pdflatex is supported for now, which means that the base name of the executable file that is selected must equal `pdflatex`.
> Custom compiler path

- src/nl/rubensten/texifyidea/modules/LatexModuleType.java
- src/nl/rubensten/texifyidea/run/LatexRunConfiguration.java
* Fixes Run Configuration related null pointer exceptions (null file).
* Removed `getBigIcon()` to align with the 2017.2.1 build of IntelliJ.
> Fix for #82 (NPE Crash) and #80 (2017.2.1 update)

- src/nl/rubensten/texifyidea/completion/LatexCompletionContributor.java
Problem was with the changed leaf parser element from the previous version. This used to be NORMAL_TEXT, but now is NORMAL_TEXT_WORD instead.
This closes #87.
> Reinstated file completion

- resources/META-INF/plugin.xml
- src/nl/rubensten/texifyidea/documentation/LatexDocumentationProvider.java
Adds proper formatting for goto label popup. Includes file name and line number where the label was declared.
Closes #91.
> Added quick navigation info for labels

- src/nl/rubensten/texifyidea/completion/LatexCommandProvider.java
* Fixed issue #89. This meant that command definitions in included files had the wrong line number shown as the plugin was using the currently opened editor to determine the line number. Now it solely relies on the included file. The IndexOutOfBoundsException occured because the included file is larger than the opened file causing a greater offset to be used than possible (hence index out of bounds).
* As a side effect, file names with line numbers have returned as type text with custom commands in the autocomplete.
> Fixed #89.

- resources/META-INF/plugin.xml
- resources/inspectionDescriptions/NonMatchingEnvironment.html
- src/nl/rubensten/texifyidea/inspections/NonMatchingEnvironmentInspection.kt
- src/nl/rubensten/texifyidea/util/PsiUtil.kt
- Adds an inspection that checks for matching environment names.
- Provides 2 quick fixes: change the `\end` name, or the `\begin` name.
> Non matching environment inspection

- src/nl/rubensten/texifyidea/completion/handlers/LatexMathInsertHandler.java
- src/nl/rubensten/texifyidea/completion/handlers/RightInsertHandler.kt
- src/nl/rubensten/texifyidea/lang/LatexMathCommand.java
- src/nl/rubensten/texifyidea/util/CollectionUtil.kt
- Added `\leftX`/`\rightX` to autocomplete for `() [] \{\} || \|\| <>`
- Automatically inserts the `\rightX` variant when `\leftX` is selected from the autocomplete.
> Added auto insertion for \leftX \rightX.

- resources/META-INF/plugin.xml
- src/nl/rubensten/texifyidea/completion/handlers/RightInsertHandler.kt
- src/nl/rubensten/texifyidea/editor/InsertEnumerationItem.kt
- src/nl/rubensten/texifyidea/editor/UpDownAutoBracket.kt
- src/nl/rubensten/texifyidea/util/PsiUtil.kt
- src/nl/rubensten/texifyidea/util/StringUtil.kt
- Whenever you write multiple characters in a subscript (e.g. `a_ij`), braces get inserted automatically (e.g. `a_{ij}`)
- When inserting `left` and `righ`, two extra spaces are inserted (i.e. `\left( ^ \right)` where `^` is the cursor).
> Auto insertion of `{}` when having multiple characters in super/subscript in math mode.

- src/nl/rubensten/texifyidea/highlighting/LatexAnnotator.java
- Comments now get highlighted in math mode.
> Fixed #111 - Comments not being highlighted in math mode.

- src/nl/rubensten/texifyidea/completion/LatexCompletionContributor.kt
- src/nl/rubensten/texifyidea/completion/LatexFileProvider.java
- src/nl/rubensten/texifyidea/completion/handlers/CompositeHandler.kt
- src/nl/rubensten/texifyidea/completion/handlers/FileNameInsertionHandler.kt
- src/nl/rubensten/texifyidea/util/FileUtil.kt
- When you insert `\include` using the autocomplete and select a file from the list, the extension gets omitted. (#118)
> File autocomplete of \include omits extension - Fixes #118.

- src/nl/rubensten/texifyidea/completion/LatexCommandProvider.java
- src/nl/rubensten/texifyidea/lang/LatexNoMathCommand.java
- src/nl/rubensten/texifyidea/structure/LatexNewCommandPresentation.java
- src/nl/rubensten/texifyidea/structure/LatexPresentationFactory.java
- src/nl/rubensten/texifyidea/structure/LatexStructureViewElement.java
- src/nl/rubensten/texifyidea/structure/filter/LatexNewCommandFilter.java
- Operators defined with `\DeclareMathOperator` do now appear in the autocomplete in math mode.
- `\DeclareMathOperator` added to autocomplete list.
- Operators declared as `\DeclareMathOperator` appear in the structure view under newcommands.
> Added DeclareMathOperator support.

- resources/META-INF/plugin.xml
- src/nl/rubensten/texifyidea/structure/LatexBreadcrumbsInfo.kt
- Added breadcrumbs for LatexCommands and LatexEnvironment.
- It does make use of the deprecated ~~`BreadcrumbsInfoProvider`~~. Couldn't find a better way to do it. Just to keep in mind for later updates.
> Added breadcrumbs for environments and commands.

- src/nl/rubensten/texifyidea/inspections/MissingLabelInspection.kt
- src/nl/rubensten/texifyidea/util/PsiUtil.kt
* After having inserted a label using the Missing Label inspection, the caret will be placed after the inserted label. (#133)
> Jump to end of label when inserting with the MissingLabel inspection.

- resources/META-INF/plugin.xml
- Re-anchored the new latex file action to the `NewGroup` group, after the new file action.
- This fixes #121: the new file action missing in other JetBrains products.
> Anchored New Latex File action to the NewGroup group.

- src/nl/rubensten/texifyidea/completion/LatexCommandProvider.java
- src/nl/rubensten/texifyidea/structure/LatexIncludePresentation.java
- src/nl/rubensten/texifyidea/structure/LatexPresentationFactory.java
- src/nl/rubensten/texifyidea/structure/LatexStructureViewElement.java
- src/nl/rubensten/texifyidea/util/FileUtil.kt
- The contents of a used documentclass (where the cls is in your project) get displayed in the include part of the structure view.
- Commands defined in an included document class (where the cls is in your project) get added to the autocomplete, (#143)
> Documentclass: commands in autocomplete and contents in structure view.

- gen/nl/rubensten/texifyidea/grammar/LatexLexer.java
- gen/nl/rubensten/texifyidea/parser/LatexParser.java
- gen/nl/rubensten/texifyidea/psi/LatexContent.java
- gen/nl/rubensten/texifyidea/psi/LatexNoMathContent.java
- gen/nl/rubensten/texifyidea/psi/impl/LatexContentImpl.java
- gen/nl/rubensten/texifyidea/psi/impl/LatexNoMathContentImpl.java
- src/nl/rubensten/texifyidea/grammar/Latex.bnf
- src/nl/rubensten/texifyidea/grammar/LatexLexer.flex
- src/nl/rubensten/texifyidea/psi/LatexPsiUtil.java
Resolves #61.
Needed because the state of (non-)math mode cannot accurately be presumed at parser/lexer level.
> Parser relaxation for nested math environments

- src/nl/rubensten/texifyidea/action/analysis/WordCountAction.kt
- src/nl/rubensten/texifyidea/index/LatexCommandsIndex.java
- src/nl/rubensten/texifyidea/util/FileUtil.kt
- src/nl/rubensten/texifyidea/util/PackageUtils.kt
Fixes #147.
- `\RequirePackage` now behaves the same as `\usepackage`.
- Packages loaded in the document class are now in the included packages index
Implementation note: all commands from the documentclass are now loaded in the indexed commands in the file set.
> Support for \RequirePackage and packages loaded in documentclass

- resources/META-INF/plugin.xml
- src/nl/rubensten/texifyidea/gutter/LatexNavigationGutter.java
- src/nl/rubensten/texifyidea/index/LatexIncludesIndex.java
- src/nl/rubensten/texifyidea/index/stub/LatexCommandsStubElementType.java
- src/nl/rubensten/texifyidea/lang/Diacritic.kt
- src/nl/rubensten/texifyidea/lang/LatexNoMathCommand.kt
- src/nl/rubensten/texifyidea/lang/RequiredFileArgument.java
- src/nl/rubensten/texifyidea/util/TexifyUtil.java
- Included `\usepackage` and `\RequirePackage` into inclusion loop detection. (Fixes #162)
- Added new index for inclusion commands.
- Added navigation gutter icons for `\usepackage` and `\RequirePackage` that have a local style file.
> Inclusion index & Usepackage/RequirePackage integration

- src/nl/rubensten/texifyidea/completion/LatexCommandProvider.java
- src/nl/rubensten/texifyidea/completion/handlers/LatexNoMathInsertHandler.kt
- src/nl/rubensten/texifyidea/highlighting/LatexAnnotator.kt
- src/nl/rubensten/texifyidea/inspections/MissingImportInspection.kt
- src/nl/rubensten/texifyidea/util/FileUtil.kt
- src/nl/rubensten/texifyidea/util/PsiUtil.kt
- Whenever a comment environment is defined, comment environments won't get syntax highlighting for comments.
- For performance reasons, the definition check happens only once every 40 annotation checks (cache).
- Also the MissingImport inspection takes definitions into account.
- Whenever comment environments are defined, `\usepackage{comment}` won't be auto-inserted.
> Advanced syntax highlighting of the comment environment.

- src/nl/rubensten/texifyidea/inspections/UnicodeInspection.java
- src/nl/rubensten/texifyidea/util/PackageUtils.kt
- Whenever there are no usepackages in the file, and the unicode include packages option is selected, the packages will be inserted directly underneath the documentclass. The problem was that the 2nd usepackage is still recognised as a 1st use of usepackage as the first command is not properly indexed before the 2nd one gets included. This makes it hard to do some logic on it. This workaround just removes all extra newlines, so it is glued to the documentclass. `\endramble` Resolves #168
> Package inclusion by Unicode inspection now inserts fewer newlines

- src/nl/rubensten/texifyidea/action/sumatra/ForwardSearchAction.kt
- src/nl/rubensten/texifyidea/run/LatexCommandLineState.kt
- After compilation, the cursor's location will be highlighted in SumatraPDF.
- Uses a delay of 500ms so it also works when the program gets booted.
> Execute forward search after compilation.

- src/nl/rubensten/texifyidea/editor/UpDownAutoBracket.kt
- src/nl/rubensten/texifyidea/util/PsiUtil.kt
- Auto insertion of `{}` after `_` and `^` now works in math-esque environments.
- Fixed that the editor doesn't recognise auto insertion cases correctly in certain cases.
- Fixed `PsiUtilKt#lastChildOfType` not performing instance check correctly.
> Fixed auto insertion of sub/superscript after _ or ^

- src/nl/rubensten/texifyidea/action/analysis/WordCountAction.kt
- Word count now ignores environments in `WordCountAction#IGNORE_ENVIRONMENTS`. Only goes for `tikzpicture` and `thebibliography` for now, if you know more please add them before merging.
- Math mode now gets ignored in word count.
> Enhanced word count

- src/nl/rubensten/texifyidea/inspections/latex/LatexMissingDocumentEnvironmentInspection.kt
- src/nl/rubensten/texifyidea/run/LatexCommandLineState.kt
- Resolves #199.
- I disabled forward search when the cursor is not in the main `.tex`-file.
- Removed debug println.
> Fixed #199: Only go to line in PDF when the source .tex is opened.

- src/nl/rubensten/texifyidea/intentions/LatexMoveSectionToFileIntention.kt
Now generated filenames for the Move large section to new file quickfix follow the convention of lowercase letters and dash instead of using spaces.
> Fixed spaces in generated filenames

- src/nl/rubensten/texifyidea/inspections/TexifyInspectionBase.java
- src/nl/rubensten/texifyidea/inspections/TexifyRegexInspection.kt
- src/nl/rubensten/texifyidea/util/PsiUtil.kt
- All inspections get ignored in `\begin{comment}..\end{comment}` from `comment`.
> Made inspections ignore comments by default.

- src/nl/rubensten/texifyidea/inspections/latex/LatexLineBreakInspection.kt
- See title. This means that works like `Inc.` or `Mr.` are not valid sentence ends.
- This does mean that sentences ending with names do not get the inspection. I do prefer this over having false positives on the abbreviations.
> Resolved #209: Words starting with a capital are no longer seen as end of sentence

- src/nl/rubensten/texifyidea/run/LatexCommandLineState.kt
- src/nl/rubensten/texifyidea/util/GeneralUtil.kt
- See title. Fixes #220.
- Achieved it by checking if the caret position is within the document environment.
> Resolved #220: When in the preamble, don't automatically do the inverse search

- resources/META-INF/plugin.xml
- resources/inspectionDescriptions/BibtexDuplicateBibliography.html
- resources/inspectionDescriptions/LatexNoExtension.html
- src/nl/rubensten/texifyidea/inspections/bibtex/BibtexDuplicateBibliographyInspection.kt
- src/nl/rubensten/texifyidea/inspections/latex/LatexNoExtensionInspection.kt
- Inspection that reports when the same bibliography is inserted multiple times
- Inspection that reports when the file extension is used in `\include` or `\bibliography` commands.
> Inspections related to includes

- src/nl/rubensten/texifyidea/folding/LatexImportFoldingBuilder.kt
- src/nl/rubensten/texifyidea/util/Magic.kt
- Blank lines allow usepackage folding groups to be seperated.
- Comments get ignored by import folding.
- As per default IJ behaviour with Java imports.
> Resolved #229: import folding breaks at double line breaks and ignore comments

- src/nl/rubensten/texifyidea/action/group/SumatraActionGroup.java
- src/nl/rubensten/texifyidea/action/sumatra/ConfigureInverseSearchAction.kt
- src/nl/rubensten/texifyidea/action/sumatra/ForwardSearchAction.kt
- src/nl/rubensten/texifyidea/run/LatexCommandLineState.kt
- src/nl/rubensten/texifyidea/run/OpenSumatraListener.kt
- src/nl/rubensten/texifyidea/run/SumatraConversation.kt
On startup, check installation status of SumatraPDF (through registry keys). When SumatraPDF is not installed, disable all `SumatraConversation` actions.
Note: since the installation status is only checked on startup (performance considerations), users must restart TeXiFy when installing SumatraPDF.
Fixes #148.
> Check SumatraPDF installation status

- src/nl/rubensten/texifyidea/highlighting/LatexTypedHandler.java
- Resolves #267 (see title).
- Fixed by checking if the document contains a `]` at the given offset.
> Fixed insertion of extra ']' after '\[' in outer scope.

- src/nl/rubensten/texifyidea/editor/UpDownAutoBracket.kt
- src/nl/rubensten/texifyidea/inspections/TexifyRegexInspection.kt
- src/nl/rubensten/texifyidea/inspections/latex/LatexGroupedSubSupScriptInspection.kt
- Resolves #264: Subscript must be grouped in labels.
- Disabled checking in inspection.
- Disabled auto insertion.
> Fixes for SubSupscripts in \label and \bibitem

- src/nl/rubensten/texifyidea/completion/LatexCommandProvider.java
- src/nl/rubensten/texifyidea/inspections/latex/LatexNonMatchingIfInspection.kt
- src/nl/rubensten/texifyidea/util/GeneralUtil.kt
- src/nl/rubensten/texifyidea/util/Magic.kt
- src/nl/rubensten/texifyidea/util/PsiUtil.kt
- Unknown variants of `\if`-commands get recognised by NonMatchingIf inspection.
- Commands defined by `\newif` are now included into the autocomplete.
> Fix for If-inspection & Added \newif definitions to autocomplete.

- README.md
Small build instructions update which specifies to check the kotlin jvm target option. It can happen that this is set to JVM 1.6 instead of 1.8.
> Small build instructions update

- src/nl/rubensten/texifyidea/util/TexifyUtil.java
None.
Another fix for a nullpointer issue. Did not find an issue for this one, but encountered it myself. From previous issues we have learned that ```command.getName()``` is nullable, so could use optional here to avoid referencing null.
Here is the stacktrace:
```
null
java.lang.NullPointerException
at nl.rubensten.texifyidea.util.TexifyUtil.isCommandKnown(TexifyUtil.java:656)
at nl.rubensten.texifyidea.inspections.latex.LatexCommandAlreadyDefinedInspection.inspectFile(LatexCommandAlreadyDefinedInspection.kt:38)
at nl.rubensten.texifyidea.inspections.TexifyInspectionBase.checkFile(TexifyInspectionBase.java:57)
at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:142)
at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
at …
```
> TexifyUtil nullpointer issue

- src/nl/rubensten/texifyidea/inspections/latex/LatexFileNotFoundInspection.kt
- src/nl/rubensten/texifyidea/util/FileUtil.kt
- src/nl/rubensten/texifyidea/util/PsiUtil.kt
- src/nl/rubensten/texifyidea/util/TexifyUtil.java
Closes #421.
Adds a quickfix to add unresolved files in include commands. Makes use of the (undocumented) `CreateFileFix` in the IntelliJ API. Upon creation, it opens the file automatically.
> Quickfix to add missing files in include commands

- src/nl/rubensten/texifyidea/action/group/SumatraActionGroup.java
- src/nl/rubensten/texifyidea/action/sumatra/ConfigureInverseSearchAction.kt
- src/nl/rubensten/texifyidea/action/sumatra/ForwardSearchAction.kt
- src/nl/rubensten/texifyidea/run/LatexCommandLineState.kt
- src/nl/rubensten/texifyidea/run/OpenSumatraListener.kt
- src/nl/rubensten/texifyidea/run/SumatraConversation.kt
- src/nl/rubensten/texifyidea/util/TexifyUtil.java
Fixes issues #432 and #424 (and related).
The check for Sumatra bindings was placed inside the class that depended directly on native DLL libraries, which causes issues on non-Windows systems.
Fixed by placing the `isSumatraAvailable` check outside of the `SumatraConversaion` class.
> Sumatra native library fix

- build.gradle
- src/nl/rubensten/texifyidea/editor/BibtexQuoteInsertHandler.kt
- src/nl/rubensten/texifyidea/editor/ShiftTracker.kt
- src/nl/rubensten/texifyidea/editor/UpDownAutoBracket.kt
Opening as discussion, because I see a versioning problem: after installing IntelliJ 2018.1 I could not install TeXiFy build with Gradle under 2017.3, since "plugin is not compatible". The plugin as released to Jetbrains still could be installed.
When changing the build number in Gradle, there were some backwards incompatible changes in the code (see diff of this PR) and  after that it all worked again.
This needs to be sorted out before releasing a gradle build to Jetbrains, since it's not good if the plugin breaks when everyone updates their IDE. 
My guess is that plugins do build against a new IntelliJ version before official release date, and release to Jetbrains for a specific version of IDE only, so users can update to the new version of the plugin once they update their IDE? For …
> IntelliJ 2018.1 versioning issues

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Just wanted to show you that there exists a plugin which updates Gradle dependencies automatically (both plugins and module dependencies, but not Gradle itself) when you run it (help/useLatestVersions). Also works for Gradle Kotlin DSL build files. You should try it, it's fun. Not that updating these kind of dependencies is very important, I guess. Ah well.
> Semi-automatically update Gradle dependencies

- resources/fileTemplates/internal/LaTeX Source With BibTeX.tex.ft
- resources/fileTemplates/internal/LaTeX Source.tex.ft
Using the a4wide package by default creates some unnecessary complications on linux as a4(wide) is pretty hard to install. Besides, some people say it shouldn't be used anyway: https://tex.stackexchange.com/questions/95201/why-should-i-avoid-the-a4-and-aeguill-packages
So I propose to change a4wide into something else like amsmath or whatever you want.
> Remove a4wide from template file

- src/nl/rubensten/texifyidea/editor/InsertEnumerationItem.kt
- src/nl/rubensten/texifyidea/settings/TexifyConfigurable.kt
- src/nl/rubensten/texifyidea/settings/TexifySettings.kt
It is now possible to disable this feature in the plugin settings.
Checkbox in the plugin settings to enable/disable automatic insertion of `\item` on pressing enter in itemize-like environments. The setting is enabled by default.
The insertion of `\item` on pressing enter in itemize-like environments will be suppressed when the setting is disabled.
None
> Make the insertion of `\item` on enter in itemize-like environments optional

- src/nl/rubensten/texifyidea/util/Magic.kt
- src/nl/rubensten/texifyidea/util/TexifyUtil.java
Bib files are not recognized as included when a tex file with the same name exists in the directory of the referenced bib file.
This is caused by the fact that getReferencedFiles previously did not take into account which extensions should be scanned for by particular include commands; instead the whole set of include commands (tex, cls, sty and bib) was used. Tex files took precedence over bib files, which made the bib file 'lost'.
None
Added a Magic constant indicating which extensions should be scanned per include command (if any).
None
> Fixed #612: Bib entries are not recognized when name clash with tex file exists

- src/nl/rubensten/texifyidea/run/LatexCommandLineState.kt
- src/nl/rubensten/texifyidea/run/OpenSumatraListener.kt
- src/nl/rubensten/texifyidea/run/SumatraConversation.kt
None
- When the bibtex run configuration is removed from the latex run config, it will not be automatically added when the document is compiled again. This is to prevent long compilation sequences for large documents that may be undesired. The bibtex run configuration is still generated when the latex run configuration is created from the gutter icon.
- On Windows: SumatraPDF will no longer steal focus from the IDE after compiling the document. This only works when SumatraPDF is already running. When the SumatraPDF process needs to be started, focus will transfer to SumatraPDF (there is no way to reliable prevent this).
None
> Improved compile experience

- src/nl/rubensten/texifyidea/lang/DefaultEnvironment.kt
- src/nl/rubensten/texifyidea/lang/LatexNoMathCommand.kt
- src/nl/rubensten/texifyidea/lang/Package.kt
- src/nl/rubensten/texifyidea/run/BibtexCommandLineState.kt
- src/nl/rubensten/texifyidea/run/BibtexRunConfiguration.kt
- src/nl/rubensten/texifyidea/run/BibtexSettingsEditor.kt
- src/nl/rubensten/texifyidea/run/LatexCommandLineState.kt
- src/nl/rubensten/texifyidea/run/LatexCompiler.java
- src/nl/rubensten/texifyidea/run/LatexRunConfiguration.java
- src/nl/rubensten/texifyidea/run/LatexSettingsEditor.java
- src/nl/rubensten/texifyidea/run/compiler/BibtexCompiler.kt
- src/nl/rubensten/texifyidea/util/PlatformUtil.kt
This PR depends on #732.
Added lualatex as compiler option. And tested that it works on a sample file:
```latex
\usepackage{luacode}
A random number:
\directlua{tex.print(math.random())}
and another one:
\begin{luacode}
tex.print(math.pi)
\end{luacode}
\end{document}
```
This doesn't automatically select lualatex as compiler, see #737.
> Add lualatex option to compilers

- src/nl/rubensten/texifyidea/lang/DefaultEnvironment.kt
As the [amsmath docs](http://texdoc.net/texmf-dist/doc/latex/amsmath/amsldoc.pdf) shows on page 7, the `split*` environment does not exist. On the bottom of page 8 it says that the `equation*` environment does not exist in plain LaTeX and is added by amsmath. I tested and it seems correct.
> Remove split* and add equation* dependency

- src/nl/rubensten/texifyidea/run/BibtexCommandLineState.kt
- src/nl/rubensten/texifyidea/run/LatexCompiler.java
- src/nl/rubensten/texifyidea/run/LatexRunConfiguration.java
- src/nl/rubensten/texifyidea/run/LatexSettingsEditor.java
Continuation of PR #645, solves issue #728.
- Add the option to disable the out/ directory (on Windows/MiKTeX).
- Fix bibtex working directory when auxil/ is not used (on Windows/MiKTeX).
- Make auxil/ and out/ options invisible for non-windows systems (at the moment they just don't do anything on non-windows systems).
- Make the auxil path invisible in the BiBTeX run configuration, as this was overwritten by the settings in the LaTeX run configuration.
```
\usepackage{imakeidx}
\makeindex
Please look at~\cite{golub}.
This \index{this} will appear in the index.
\printindex
\newpage
\bibliography{main}
\bibliographystyle{plain}
\end{document}
```
where the `main.bib` file is
```
@Book{golub,
title     = {Matrix {C}omputations}, …
```
> Add option to disable the out directory

- build.gradle
Fixes #760, fortunately it was quickly fixed.
Documentation: https://github.com/JetBrains/gradle-intellij-plugin#patching-dsl
Please check if in the generated zip in `build\distributions`, that  `TeXiFy-IDEA-0.6.1\TeXiFy-IDEA\lib\TeXiFy-IDEA-0.6.1\META-INF\plugin.xml` contains the line ` <idea-version since-build="141.*"/>`
> Fixes #760 compatibility with future versions

- src/nl/rubensten/texifyidea/run/compiler/BibtexCompiler.kt
Fixes #765, simple bug with big consequences. As I said, I think we need to run some manual tests for common usage before a release, we would have caught this bug.
> Use bibtex executablename in bibtex run config

- src/nl/rubensten/texifyidea/highlighting/LatexAnnotator.kt
- src/nl/rubensten/texifyidea/highlighting/LatexColorSettingsPage.kt
- src/nl/rubensten/texifyidea/highlighting/LatexSyntaxHighlighter.java
- src/nl/rubensten/texifyidea/util/Magic.kt
Resolves #772 and Resolves #774.
- Added syntax highlighting for references and reference definitions.
- Added syntax highlighting for style commands like `\textbf`.
- Both settings are disabled by default (making use of default style). Highlighting can be turned on by the users themselves.
- Grouped attribute descriptors in colour highlighting settings page.
- Updated the example text accordingly.
> Syntax highlighting for labels and font style

- gen/nl/rubensten/texifyidea/grammar/BibtexLexer.java
- src/nl/rubensten/texifyidea/grammar/BibtexLexer.flex
Fixes #425.
Parse text between bibtex entries as comment, except for the first comma separator between entries.
@PHPirates do you know if Biber is as lenient with extra commas between entries as Bibtex?
> Bibtex plaintext comments

- resources/META-INF/plugin.xml
- src/nl/rubensten/texifyidea/completion/LatexCommandProvider.java
- src/nl/rubensten/texifyidea/completion/TexifyCompletionContributor.kt
- src/nl/rubensten/texifyidea/completion/handlers/LatexCommandArgumentInsertHandler.java
- src/nl/rubensten/texifyidea/gutter/LatexNavigationGutter.java
- src/nl/rubensten/texifyidea/insight/LatexParameterInfoHandler.kt
- src/nl/rubensten/texifyidea/inspections/LatexSpellcheckingStrategy.kt
- src/nl/rubensten/texifyidea/inspections/latex/LatexUnicodeInspection.java
- src/nl/rubensten/texifyidea/lang/LatexCommand.kt
- src/nl/rubensten/texifyidea/lang/LatexMathCommand.kt
- src/nl/rubensten/texifyidea/lang/LatexRegularCommand.kt
- src/nl/rubensten/texifyidea/lang/Package.kt
- src/nl/rubensten/texifyidea/navigation/GotoCommandDefinitionSymbolContributor.kt
- src/nl/rubensten/texifyidea/navigation/GotoEnvironmentDefinitionSymbolContributor.kt
- src/nl/rubensten/texifyidea/navigation/GotoLabelSymbolContributor.kt
- src/nl/rubensten/texifyidea/navigation/NavigationItemUtil.kt
- src/nl/rubensten/texifyidea/navigation/TexifyGotoSymbolBase.kt
- src/nl/rubensten/texifyidea/structure/latex/LatexLabelPresentation.kt
- src/nl/rubensten/texifyidea/structure/latex/LatexStructureViewElement.kt
- src/nl/rubensten/texifyidea/util/Commands.kt
- src/nl/rubensten/texifyidea/util/Environments.kt
- src/nl/rubensten/texifyidea/util/Labels.kt
- src/nl/rubensten/texifyidea/util/Magic.kt
- src/nl/rubensten/texifyidea/util/Psi.kt
- src/nl/rubensten/texifyidea/util/PsiCommands.kt
Various updates to the built in commands. Depends on PR #789.
- Added support for `xparse` definition commands.
- Added `\binom`, `\vee`, and `\wedge` to the autocomplete.
- `LatexNoMathCommand` is now called `LatexRegularCommand`.
> Commands update

- src/nl/rubensten/texifyidea/completion/handlers/FileNameInsertionHandler.kt
- src/nl/rubensten/texifyidea/inspections/bibtex/BibtexDuplicateBibliographyInspection.kt
- src/nl/rubensten/texifyidea/structure/latex/LatexStructureViewElement.kt
- src/nl/rubensten/texifyidea/util/Magic.kt
Fixes #803 (MWE also here)
**Changes**
Some inspections and checks for `\bibliography` command are now also triggered for `\addbibresource`.
Note that `\addbibresource` requires the `.bib` extension (but there is no inspection for that yet), see the [docs](http://ctan.triasinformatica.nl/macros/latex/contrib/biblatex/doc/biblatex.pdf) section 3.7.1.
> Add bibtex inspections for addbibresource

- README.md
- src/nl/rubensten/texifyidea/action/sumatra/ConfigureInverseSearchAction.kt
Fixes #809 and actually fixes #104 properly now as well, the way this is implemented is that we check the system property `sun.arch.data.model`, and if it returns 64 I think we can be sure a 64-bit java is installed. That means that we can use (the equivalent of) `idea64.exe`, because that uses a 64-bit java (see for example [this SO answer](https://stackoverflow.com/a/33010846/4126843)). Otherwise we use `idea.exe` like before.
I tested this when I didn't have a 32-bit JDK installed separately (previously this was a situation which produced the error in #104 ). Also tested it after I uninstalled my 64-bit JDK, however the system property still returned 64 and idea64.exe still worked, I guess IDEA has a 64-bit JRE bundled or something. So in practice I think we are replacing idea.exe by …
> Configure inverse search correctly when no 32-bit Java is available

- src/nl/rubensten/texifyidea/structure/latex/LatexStructureViewElement.kt
Changed adding commands to display ```\bibitem``` and ```\label``` again.
Now userdefined commands displayed on first load, not only the icon.
The problem started in 322304a41f667c911db4d457113fd69c138238b2. I could not find an Issue or PR related to this commit. Could anyone explain why these changes were made? I couldn't figure it out, not even by looking into previous commits in this branch.
Especially the change to pass the first parameter casted as a command to ```LatexStructureViewCommandElement.newCommand()``` and not the command itself  which worked properly beffore.
> Fix label not shown in structure view

- .gitignore
- README.md
- build.gradle
- gradle/credentials.properties
* Added Gradle task
* Added instructions how to subscribe
You can view alpha releases at https://plugins.jetbrains.com/plugin/9473-texify-idea (I renamed the latest one to alpha instead of nightly, I think it will be approved next week)
Note I had to add the .properties file otherwise the Gradle build fails.
Apparently I averaged about one alpha build per week in the last four months, I think I'll keep around that average for the coming time.
> Add Gradle task to upload to the alpha channel

- resources/META-INF/plugin.xml
- src/nl/rubensten/texifyidea/navigation/GotoSectionDefinitionSymbolContributor.kt
- src/nl/rubensten/texifyidea/navigation/NavigationItemUtil.kt
- src/nl/rubensten/texifyidea/util/Labels.kt
- src/nl/rubensten/texifyidea/util/PsiCommands.kt
Continuation of #771 and #789.
* Goto symbol functionality also works for section markers now.
> Added 'Goto symbol' support for section markers.

- src/nl/rubensten/texifyidea/run/LatexCompiler.kt
Fixes #827.
Compiler options are almost equal to the pdflatex ones, so this was not too difficult.
Tested on Linux and Windows.
> Add xelatex compiler

- src/nl/rubensten/texifyidea/inspections/latex/LatexNonBreakingSpaceInspection.kt
Fixes #865 
- Fixed `\citet` commands (and variants) without non-breaking spaces being flagged by the inspection.
- Fixed display name (internally) of the LatexNonBreakingSpace inspection being wrong.
> \citet commands (and variants) without non-breaking space being flagged

- src/nl/rubensten/texifyidea/inspections/latex/LatexCiteBeforePeriodInspection.kt
Fixes #861.
- Quick fix no longer tries to access non-existent characters with index larger than the document length.
> Fixed crash #861: LatexCiteBeforePeriod quickfix at the end of a file.

- src/nl/rubensten/texifyidea/action/analysis/WordCountAction.kt
Fixes #860.
- Word count only analyses LaTeX files now (ignores TikZ).
- Text in `\bibliography` and `\bibliographystyle` gets ignored.
> Word count only analyses LaTeX files

- src/nl/rubensten/texifyidea/util/Magic.kt
Added the `\newtheorem` command to the list of commands that define a new environment (from the list #260).
Note that `\newtheorem` does not require the `amsthm` package.
> Added the \newtheorem command to the auto complete

- .travis.yml
- src/nl/rubensten/texifyidea/inspections/latex/LatexNonBreakingSpaceInspection.kt
Hey,
great project, thank you so much! :tada: 
I've been bothered by a few false alarms and this is my attempt to fix a few of them. :wink:
The commands `\cref`, `\cpageref` and `\autoref` automatically produce the name of the section/figure/etc..
Therefore there is no need for a non-breaking space before them.
> Ignore cref and autoref for nbsp inspection

- src/nl/rubensten/texifyidea/editor/UpDownAutoBracket.kt
Resolves #868 
I think the functionality here is the same, but please point out if I've missed something that required this regex check to be where it was.
When I tested, this does fix the issue with the opening backslash (though it's still as slow when you type the next character - need to spend some more time looking at UpDownAutoBracket).
> Improve performance by failing fast if regex doesn't match

- src/nl/rubensten/texifyidea/util/Files.kt
Removes the dependency on the Plexus Utils library for retrieving the file extension from a file name.
Removes the dependency since it apparently is not present in some environments (observed in PyCharm 2019.1 on Linux). Fixes #919. Changed the implementation to use the IJ OpenAPI util function instead.
> Remove Plexus Utils library dependency

- src/nl/rubensten/texifyidea/insight/LatexLineMarkerProvider.kt
- src/nl/rubensten/texifyidea/util/Magic.kt
Resolves #901.
...\part lines are darker than \section lines are darker than \paragraph
lines etc.
> Method separator colours for sections are now based on the structure level

- src/nl/rubensten/texifyidea/highlighting/LatexPairedBraceMatcher.kt
Added `\begin` and `\end` paired brace matching.
N/A
N/A
> Brace matcher also matches "\begin" / "\end" pairs

- .travis.yml
- build.gradle
- src/nl/rubensten/texifyidea/inspections/TexifyRegexInspection.kt
- src/nl/rubensten/texifyidea/inspections/latex/LatexCiteBeforePeriodInspection.kt
- src/nl/rubensten/texifyidea/inspections/latex/LatexEnDashInspection.kt
- src/nl/rubensten/texifyidea/inspections/latex/LatexExtremeInequalityInspection.kt
- src/nl/rubensten/texifyidea/inspections/latex/LatexPrimitiveEquationInspection.kt
- src/nl/rubensten/texifyidea/run/evince/EvinceConversation.kt
- src/nl/rubensten/texifyidea/util/General.kt
- test/nl/rubensten/texifyidea/inspections/TexifyRegexInspectionTest.kt
Fixes #826 
The problem was that RegexFixes have a fixed location. That means, when there are multiple problem descriptors in a file, and the user selects Fix All, that IntelliJ will apply the fixes one by one for all problem descriptors. That means that when a fix or a certain problem replaces text with other text _of a different length_, all the locations of all subsequent problem descriptors will be wrong.
One solution would be to rescan the complete file after each fix, but for performance reasons (and because I didn't know how to rescan a file anyway) I chose to calculate a cumulative displacement, which is then taken into account when applying the next fixes in the file.
The implementation is a bit more roundabout, because the loop which loops over all problem descriptors in a file …
> Fix all the Fix All fixes

- src/nl/rubensten/texifyidea/run/evince/EvinceForwardSearch.kt
Fixes #940 
Now you can actually run the run config when your cursor is not in the main file. Also, forward search actually works now in that case. Because of the first part, consider adding the fix to 0.6.6.
When you have a file open that doesn't belong to the fileset of the run config, it simply won't forward search.
> Fix error when trying to compile from non-main file (and fix the forward search) for Evince

- src/nl/hannahsten/texifyidea/inspections/latex/LatexFileNotFoundInspection.kt
(only on MiKTeX)
includes resource folders
> Also check content roots for file not found inspection

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- gradlew
- gradlew.bat
Looks to be no breaking changes this time, as far as I tested.
> Update to 2019.3 and update dependencies

- src/nl/hannahsten/texifyidea/inspections/latex/LatexDuplicateLabelInspection.kt
Fixes #1104
```latex
\label{dupe}
\input{included}
\end{document}
```
```latex
\label{dupe}
```
> Do not create a problem descriptor for commands in other files (LatexDuplicateLabelInspection)

- resources/META-INF/plugin.xml
- src/nl/hannahsten/texifyidea/ui/tablecreationdialog/TableCreationDialogWrapper.kt
- src/nl/hannahsten/texifyidea/ui/tablecreationdialog/TableCreationEditColumnDialog.kt
Fixes #1093 (list of changes is over there)
Note that when editing a cell, you first have to press enter to finish editing and then again to advance to the next row. Since I just registered a key handler for enter, the first step seems to be default behaviour which wants to stay that way.
The text next to the icons is also a bit small, but don't see an easy way to change that.
> Table creation wizard ui improvements

- build.gradle
- resources/META-INF/grazie.xml
- resources/META-INF/plugin.xml
- src/nl/hannahsten/texifyidea/inspections/LatexGrammarCheckingStrategy.kt
Support of JetBrains Grazie plugin (https://plugins.jetbrains.com/plugin/12175-grazie/).
Adds support of grammar checking in Latex documents. 
Remove bundled Kotlin, use provided by IntelliJ Platform. (Needed since Grazie uses provided, decreases size by 1mb)
> Add support of Grazie plugin

- build.gradle
- gen/nl/hannahsten/texifyidea/grammar/BibtexLexer.java
- src/nl/hannahsten/texifyidea/grammar/BibtexLexer.flex
Fixes #1105 
Introduces a new state in the bibtex lexer to first handle the identifier before continuing
To test this PR: check that a bibtex entry like this one does not produce errors:
```bibtex
@Book{1990,
author    = abc,
title     = {The {\TeX}book },
year      = {1990},
isbn      = {0-201-13447-0},
publisher = {Addison\,\textendash\,Wesley},
}
```
> Allow number-only bibtex identifiers

- src/nl/hannahsten/texifyidea/inspections/latex/LatexSpaceAfterAbbreviationInspection.kt
- src/nl/hannahsten/texifyidea/util/Magic.kt
Fixes #1033
To test:
Check that with 
```latex
E.g me $N$.
\end{document}
```
the inspection is not triggered, but it is triggered when using `e.g.` and the quickfix works.
> Only trigger LatexSpaceAfterAbbreviationInspection on abbreviations ending with a .

- src/nl/hannahsten/texifyidea/index/IndexUtilBase.kt
- src/nl/hannahsten/texifyidea/inspections/latex/LatexMissingImportInspection.kt
- src/nl/hannahsten/texifyidea/lang/LatexRegularCommand.kt
- src/nl/hannahsten/texifyidea/lang/Package.kt
- src/nl/hannahsten/texifyidea/settings/TexifyConfigurable.kt
- src/nl/hannahsten/texifyidea/settings/TexifySettings.kt
- src/nl/hannahsten/texifyidea/settings/TexifySettingsState.kt
- src/nl/hannahsten/texifyidea/util/Magic.kt
- src/nl/hannahsten/texifyidea/util/Packages.kt
- src/nl/hannahsten/texifyidea/util/files/Files.kt
Fixes #1101 
This PR
- Adds a global setting to disable auto insertion of package requirements (and also disables LatexMissingImportInspection)
- The root file when using the subfiles package is now correct, so package imports will be added to the correct preamble and imports will be resolved correctly (try using autocomplete for something in section1.tex)
- Added the subfile command
- Do not add the class in the list of included packages, otherwise it thinks that subfiles is included twice.
https://github.com/Hannah-Sten/TeXiFy-IDEA/wiki/Automatic-package-importing
```latex
\usepackage{subfiles}
\section{One}\label{sec:one}
\subfile{section1}
\end{document}
```
```latex
\documentclass[main.tex]{subfiles} …
```
> Add option to disable auto package insert (and some subfiles support)

- src/nl/hannahsten/texifyidea/inspections/latex/LatexNonBreakingSpaceInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/LatexUnresolvedReferenceInspection.kt
- src/nl/hannahsten/texifyidea/lang/LatexRegularCommand.kt
- src/nl/hannahsten/texifyidea/lang/Package.kt
- src/nl/hannahsten/texifyidea/util/Magic.kt
Fixes #1124
The `\cref` and `\Cref` commands allow empty references to locally prevent reference compression, like this:
```latex
\usepackage{cleveref}
\section{section1}\label{refSection1}
\section{section2}\label{refSection2}
\section{section3}\label{refSection3}
\cref{refSection1,refSection2,refSection3}
% is typeset as Sec. 1 to 3
% note the double comma here
\cref{refSection1,refSection2,,refSection3}
% is typeset as Sec. 1, Sec. 2 and Sec. 3
~\ref{refSection1,,refSection2}
% should give warning
\end{document}
```
> Add support for compression prevention from cleveref

- src/nl/hannahsten/texifyidea/inspections/latex/LatexMissingLabelInspection.kt
Fixes #1097
The bug occurred when a command like \subsection was directly after another command like \section, because then the index entry of the second would not be removed. It would be removed when there was text inbetween. When the entry was not removed, the `\input` command would be there but the missing label inspection would think it was the `\subsection` command because that was in the index.
Anyway, the move section contents to file will not trigger the missing label inspection anymore:
```latex
\section{One}\label{sec:one}
\subsection{Two}\label{subsec:two}
```
> Use real instead of indexed command name for missing label inspection

- build.gradle
- src/nl/hannahsten/texifyidea/TexifyIcons.java
- src/nl/hannahsten/texifyidea/gutter/LatexNavigationGutter.kt
- src/nl/hannahsten/texifyidea/lang/LatexRegularCommand.kt
Fixes #1135
When showing a gutter icon, it now first tries to get the icon based on the file extension (if this is available) before using the default icon for the given command.
Try the following snippet and notice the TikZ (instead of pdf) and cls (instead of sty) icons in the gutter:
main.tex
```latex
\usepackage{tikz}
\usepackage{tikzscale}
\usepackage{graphicx}
\includegraphics{figure.tikz}
\end{document}
```
figure.tikz
```latex
\begin{tikzpicture}
\draw (0, 0) -- (1, 1);
\end{tikzpicture}
```
> Show the real gutter icon

- resources/META-INF/plugin.xml
- src/nl/hannahsten/texifyidea/startup/AnalyzeMenuRegistration.kt
- src/nl/hannahsten/texifyidea/startup/StartEvinceInverseSearchListener.kt
Fixes #1141
The problem was that the registering of the analyze menu action group was done using the deprecated plugin component, which made it load too early in the process hence cause the stateError.
Now it is registered using a service.
Maybe this allows TeXiFy to update without restart? Need to check if more needs to be done for that.
Docs:
https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_components.html
https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_services.html#sample-plugin
https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_extensions.html
To test this PR:
- Check that in the Analyze menu the LaTeX group is still there with the word count action.
> Register analyze menu action group using a service instead of a deprecated application component

- resources/META-INF/plugin.xml
- src/nl/hannahsten/texifyidea/formatting/LatexBlock.kt
- src/nl/hannahsten/texifyidea/formatting/LatexFormattingModelBuilder.kt
- src/nl/hannahsten/texifyidea/formatting/LatexSpacingBuilder.kt
- src/nl/hannahsten/texifyidea/formatting/LatexSpacingRules.kt
- src/nl/hannahsten/texifyidea/formatting/LatexWrappingStrategy.kt
- src/nl/hannahsten/texifyidea/inspections/latex/LatexCollapseCiteInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/LatexLabelConventionInspection.kt
- src/nl/hannahsten/texifyidea/lang/DefaultEnvironment.kt
- src/nl/hannahsten/texifyidea/lang/Package.kt
- src/nl/hannahsten/texifyidea/settings/codestyle/LatexCodeStyleSettings.kt
- src/nl/hannahsten/texifyidea/settings/codestyle/LatexCodeStyleSettingsProvider.kt
- src/nl/hannahsten/texifyidea/settings/codestyle/LatexLanguageCodeStyleSettingsProvider.kt
- src/nl/hannahsten/texifyidea/util/Magic.kt
- src/nl/hannahsten/texifyidea/util/Strings.kt
Defines code style settings and provides the standard IJ settings with respect to indent size and text wrapping. In particular:
- Select the `Comment at first column` option in the `Wrapping` tab to let the formatter ignore the indents of comments.
- Set `Wrap on typing` to `yes`, and select the `Ensure right margin is not exceeded` to let the formatter hard break text that exceeds the right margin guide (#250)
Use <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>L</kbd> on 
```latex
\tikzset{
mystyle/.style={
draw,
circle,
label={[fill=yellow]0:#1}
}
}
```
to get
```latex
\tikzset{
mystyle/.style={
draw,
circle,
label={[fill=yellow]0:#1}
}
}
```
Unfortunately, when typing `\tikzset{}` and hitting enter in the braces, the cursor goes to the beginning of the line (without indent). I haven't found a …
> Group indents

- resources/META-INF/plugin.xml
- src/nl/hannahsten/texifyidea/action/group/SkimActionGroup.kt
- src/nl/hannahsten/texifyidea/action/skim/ConfigureInverseSearchAction.kt
- src/nl/hannahsten/texifyidea/action/skim/ForwardSearchAction.kt
- src/nl/hannahsten/texifyidea/run/latex/LatexCommandLineState.kt
- src/nl/hannahsten/texifyidea/run/linuxpdfviewer/PdfViewer.kt
- src/nl/hannahsten/texifyidea/run/linuxpdfviewer/ViewerConversation.kt
- src/nl/hannahsten/texifyidea/run/linuxpdfviewer/skim/SkimConversation.kt
- src/nl/hannahsten/texifyidea/ui/SkimConfigureInverseSearchDialog.kt
Support for sync using Skim
Pretty much inspired by the recent addition of the Okular viewer.
The change in `String.runCommand` might break on Linux or Windows. On MacOS I am testing the availability of Skim using open -Ra which returns an error if Skim was not found. Thus I need to check the errorStream as well. Skim is found if there is nothing in the output so I just appended the error message to the run command as well. I'm not sure if this breaks viewer detection on Linux, so help is appreciated here.
> Add support for sync using Skim on OSX

- resources/META-INF/plugin.xml
- src/nl/hannahsten/texifyidea/settings/codestyle/LatexCodeStyleSettingsProvider.kt
- src/nl/hannahsten/texifyidea/settings/codestyle/LatexGenerationSettingsProvider.kt
- src/nl/hannahsten/texifyidea/settings/codestyle/LatexLanguageCodeStyleSettingsProvider.kt
Adds the _Code Generation_ tab to the LaTeX code style settings. With the settings in this tab it is possible to change the behaviour of using <kbd>Ctrl</kbd> + <kbd>/</kbd> to comment out LaTeX. Using the line
```latex
I am a sentence.
```
as an example, the option _Line comment at first column_ will produce
```latex
%    I am a sentence.
```
and the option _Add a space at comment start_ will produce
```latex
% I am a sentence.
```
**Note** that this setting is only for comment generation, and does not affect the formatter.
Somewhat relates to #610.
> Generation code style settings

- src/nl/hannahsten/texifyidea/formatting/BibtexBlock.kt
- src/nl/hannahsten/texifyidea/formatting/BibtexFormattingModelBuilder.kt
- src/nl/hannahsten/texifyidea/formatting/BibtexSpacingRules.kt
- src/nl/hannahsten/texifyidea/formatting/LatexBlock.kt
- src/nl/hannahsten/texifyidea/formatting/LatexSpacingRules.kt
- src/nl/hannahsten/texifyidea/formatting/TexSpacingBuilder.kt
> Fixes #1027

- src/nl/hannahsten/texifyidea/gutter/LatexNavigationGutter.kt
- test/nl/hannahsten/texifyidea/gutter/LatexGutterTest.kt
- test/nl/hannahsten/texifyidea/lang/magic/MagicCommentTest.kt
- testData/gutter/ShowMethodSeparators.tex
- testData/gutter/ShowNavigationGutter.tex
None
Fix LatexNavigationGutter LineMarker to use leaf elements (note added TODO) #1197 
None
It would be nice to find a more robust way of testing the gutters than using the tooltip text (e.g. also assert the referenced file), but I couldn't find one.
> Fix linemarker errors

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/other-issues.md
- .github/PULL_REQUEST_TEMPLATE.md
Apparently there are new issue templates with default labels, which allow people to choose issue type (bug/feature) themselves.
Not entirely convinced it is better, but why not.
> Create issue templates

- src/nl/hannahsten/texifyidea/util/Magic.kt
Fixes #1219
* \ifoot was assumed as if condition start but should be ignored. 
* I tested in Sandbox and it worked. 
Tested with:
IntelliJ IDEA 2019.3.2 (Ultimate Edition)
Build #IU-193.6015.39, built on January 21, 2020
Operating System:
Fedora 31 x64
Kernel: 5.4.13-201.fc31.x86_64
> added \ifoot to ignoredIfs to prevent error on default-footer change

- resources/META-INF/plugin.xml
- src/nl/hannahsten/texifyidea/editor/InlineMathBackspaceHandler.kt
Fixes #1206
* Hardcode removal of second $ when the first one of $$ is removed. Given how much I type $$ and then realise I don't want math after all, a definite typing experience improvement.
* Type `$`, possibly some more, then use backspace to remove all of that.
nah
:
> Add backspace handler to delete empty inline math

- resources/META-INF/plugin.xml
- src/nl/hannahsten/texifyidea/editor/ControlTracker.kt
- src/nl/hannahsten/texifyidea/editor/InlineMathBackspaceHandler.kt
- src/nl/hannahsten/texifyidea/editor/InsertEnumerationItem.kt
- src/nl/hannahsten/texifyidea/run/linuxpdfviewer/PdfViewer.kt
- src/nl/hannahsten/texifyidea/run/linuxpdfviewer/ViewerConversation.kt
- src/nl/hannahsten/texifyidea/run/linuxpdfviewer/evince/EvinceInverseSearchListener.kt
- src/nl/hannahsten/texifyidea/startup/StartEvinceInverseSearchListener.kt
- src/nl/hannahsten/texifyidea/util/Strings.kt
Fixes #262
* Now you can split a line while in an itemize, by using Ctrl+Enter.
Shift+Enter is already in use by IntelliJ as 'create new line', so to keep things consistent we hijacked Ctrl+Enter instead.
* Try using enter/shift+enter/ctrl+enter in itemize-like environments
> Use ctrl+enter to break line in itemize

- src/nl/hannahsten/texifyidea/psi/LatexCommandsImplUtil.kt
- test/nl/hannahsten/texifyidea/inspections/latex/LabelMissingInspectionTest.kt
- test/nl/hannahsten/texifyidea/psi/LatexPsiImplUtilTest.kt
Fixes #1259 
* Trim optional parameters and their keys when asking for the label
The following doesn't trigger the missing label inspection:
```latex
% @formatter:off
\begin{lstlisting}[language=Python, label={lst:lstlisting}]
Hallo
\end{lstlisting}
% @formatter:on
```
> Fix #1259 by trimming optional parameters

- src/nl/hannahsten/texifyidea/psi/LatexNormalTextUtil.kt
- src/nl/hannahsten/texifyidea/reference/LatexEnvironmentReference.kt
Fixes #575, fixes #1158
This is implemented by making the text in \end resolve to the text in \begin.
* Shift+F6 on environment name
* Also check if renaming/find usages of labels still works
> Refactor environments

- codecov.yml
- resources/META-INF/plugin.xml
- resources/inspectionDescriptions/LatexPackageNotInstalled.html
- src/nl/hannahsten/texifyidea/inspections/latex/LatexPackageCouldNotBeFound.kt
- src/nl/hannahsten/texifyidea/inspections/latex/LatexPackageNotInstalledInspection.kt
- src/nl/hannahsten/texifyidea/startup/TexLivePackageListInitializer.kt
- src/nl/hannahsten/texifyidea/util/Packages.kt
* On TeX Live:
* Adds inspection that checks if package is installed, and provides a quick fix to install a missing package (in the background).
* On anything not TeX Live:
* The inspection is disabled by default and does nothing when enabled. 
* Use a package (with `\usepackage` or `\RequirePackage`) that is not installed and use the quick fix to install it.
* Verify that it is disabled by default on MiKTeX.
* Verify that when enabled on MiKTeX, it does nothing.
> Texlive install packages

- src/nl/hannahsten/texifyidea/util/Packages.kt
Fixes #1274
* Insert in PSI tree instead of document
* Use quickfix of any command/environment which requires a package
> Insert usepackage correctly

- build.gradle
- resources/META-INF/plugin.xml
- src/nl/hannahsten/texifyidea/editor/CommandSelectionFilter.kt
- src/nl/hannahsten/texifyidea/editor/LatexCommandSelectioner.kt
- src/nl/hannahsten/texifyidea/settings/TexifyConfigurable.kt
- src/nl/hannahsten/texifyidea/settings/TexifySettings.kt
- src/nl/hannahsten/texifyidea/settings/TexifySettingsState.kt
Fixes #1314
* When setting is enabled, double-click or ctrl+w for example on a latex command will also select the backslash
> Add option to include backslash in word selection

- src/nl/hannahsten/texifyidea/highlighting/LatexTypedHandler.java
* Only automatically insert the second `$` when the just typed `$` opens an inline math environment.
* Play with typing and removing dollar signs.
> Fix auto insert of second $

- src/nl/hannahsten/texifyidea/editor/LatexCommenter.kt
- src/nl/hannahsten/texifyidea/inspections/bibtex/BibtexDuplicateBibliographyInspection.kt
- src/nl/hannahsten/texifyidea/ui/PreviewFormUpdater.kt
Fixes #1328
Fixes #1330 
Fixes #1331 
* Disable support for block comments
* ctrl + shift + / vs ctrl + /
> Fix hanging when block comments shortcut is used (and fix some crashes)

- src/nl/hannahsten/texifyidea/inspections/latex/LatexInclusionLoopInspection.kt
- src/nl/hannahsten/texifyidea/util/files/RootFile.kt
* Instead of using DFS on all file inclusions in the project, loop over commands index once and try to find file inclusion loops. Unfortunately this means we can only detect loops involving two files, but the old way was really hurting performance too much relative to the importance of the inspection (delayed all inspections for 20s in a large project for me).
* Two files that include each other, inspection only shown on one of them
> Speed up LatexInclusionLoopInspection

- resources/postfixTemplates/LatexWrapWithTypewriterPostfixTemplate/after.tex.template
- resources/postfixTemplates/LatexWrapWithTypewriterPostfixTemplate/before.tex.template
- resources/postfixTemplates/LatexWrapWithTypewriterPostfixTemplate/description.html
- src/nl/hannahsten/texifyidea/editor/postfix/LatexPostFixTemplateProvider.kt
- src/nl/hannahsten/texifyidea/editor/postfix/LatexStringBasedPostfixTemplates.kt
Simply adds another default postfix template for \texttt
> Add typewriter (\texttt) postfix template

- src/nl/hannahsten/texifyidea/action/preview/PreviewAction.kt
- src/nl/hannahsten/texifyidea/action/preview/ShowEquationPreview.kt
- src/nl/hannahsten/texifyidea/action/preview/ShowTikzPreview.kt
- src/nl/hannahsten/texifyidea/completion/LatexMagicCommentValueProvider.kt
- src/nl/hannahsten/texifyidea/completion/TexifyCompletionContributor.kt
- src/nl/hannahsten/texifyidea/lang/DefaultEnvironment.kt
- src/nl/hannahsten/texifyidea/lang/Package.kt
- src/nl/hannahsten/texifyidea/lang/magic/DefaultMagicKeys.kt
- src/nl/hannahsten/texifyidea/ui/PreviewFormUpdater.kt
- src/nl/hannahsten/texifyidea/util/Magic.kt
Fixes #1052 
* Add magic comments to surround preamble of math or tikz preamble of the preview: `%! begin preamble = tikz`
* Add magic comments to include entire file in preamble of the preview: `%! preview preamble = tikz`
**main.tex**
```latex
\usepackage{packages/mypackage}
%! Begin preamble = math
\newcommand{\ha}{\pi\xi\alpha}
%! End preamble = math
\begin{tikzpicture}[>=Latex]
\bla
\node[right = of 0] (1) {2};
\draw[->] (0) -- (1);
\end{tikzpicture}
\[
\ha \phi
\]
\end{document}
```
**packages/mypackage.sty**
```latex
%! preview preamble = tikz
\NeedsTeXFormat{LaTeX2e}
\ProvidesPackage{packages/mypackage}[My Package]
\RequirePackage{tikz}
\usetikzlibrary{positioning}
\usetikzlibrary{arrows.meta}
\newcommand{\bla}{\node[draw, circle] (0) …
```
> Custom preamble in preview

- gen/nl/hannahsten/texifyidea/grammar/LatexLexer.java
- src/nl/hannahsten/texifyidea/grammar/LatexLexer.flex
- src/nl/hannahsten/texifyidea/parser/LatexParserUtil.kt
Fixes #101
* \begin are now also command tokens in lexer, because brace matcher using lexer tokens and otherwise gets confused. Still broken if you do `\begin{verbatim}\end{stuff}\end{verbatim}`
> Workaround for \begin \end matching in verbatim

- src/nl/hannahsten/texifyidea/inspections/latex/LatexEscapeUnderscoreInspection.kt
- src/nl/hannahsten/texifyidea/util/Magic.kt
- test/nl/hannahsten/texifyidea/inspections/latex/LatexEscapeUnderscoreInspectionTest.kt
Fixes #1405 
Rather than having the inspection everywhere and only disallowing it in certain places I switched it now to be the other way around. I think it is a lot simpler now and will not trigger false positives but rather only miss some cases, which is a better trade-off imo.
It now only triggers the unescaped underscore inspection in normal text, and commands like `\section`, `\textit`, `\caption`, etc.
I added some tests, but I might have missed cases, so please have a look and tell me what you think.
No need to update the wiki
> #1405: confines underscore inspection to fewer places

- src/nl/hannahsten/texifyidea/completion/LatexMagicCommentKeyProvider.kt
- src/nl/hannahsten/texifyidea/completion/TexifyCompletionContributor.kt
- src/nl/hannahsten/texifyidea/lang/magic/DefaultMagicKeys.kt
- src/nl/hannahsten/texifyidea/lang/magic/TextBasedMagicCommentParser.kt
- src/nl/hannahsten/texifyidea/run/compiler/LatexCompiler.kt
- src/nl/hannahsten/texifyidea/run/latex/LatexRunConfiguration.kt
- src/nl/hannahsten/texifyidea/run/latex/LatexRunConfigurationProducer.kt
* Adds magic comments to specify the LaTeX and BibTeX compiler, including compiler arguments.
```latex
%! Compiler = latexmk -lualatex
```
or
```latex
%! BibTeX Compiler = biber
```
Check if I didn't break any of the other magic comments.
> Compiler magic comments

- src/nl/hannahsten/texifyidea/inspections/latex/LatexEllipsisInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/LatexEscapeAmpersandInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/LatexEscapeUnderscoreInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/LatexLineBreakInspection.kt
- test/nl/hannahsten/texifyidea/inspections/latex/LatexEscapeUnderscoreInspectionTest.kt
- test/nl/hannahsten/texifyidea/inspections/latex/LatexLineBreakInspectionTest.kt
Fixes #1417
Edit: Currently fixing build.
* The LatexLineBreakInspection does no longer trigger in comments.
* The LatexEllipsisInspection does no longer trigger in comments.
* The LatexEscapeUnderscoreInspection does no longer trigger in comments.
* The LatexEscapeAmpersandInspection does no longer trigger incomments.
```latex
% Starting. Comment...
% Some text. Break trigger.
Something... Of nie a.u.b. of wat. \csname one_two \endcsname or H&M
% Text comment... ofnie. Of wa. Hehe. a.u.b. of wat? H&M
% Of niet \"i \csname one_two \endcsname
% Of toch wel... one_two
Meer tekst...
OF niet, soms?
\end{document}
```
> Fixed certain inspections triggering inside comments

- src/nl/hannahsten/texifyidea/editor/LatexQuoteInsertHandler.kt
- src/nl/hannahsten/texifyidea/util/Packages.kt
- test/nl/hannahsten/texifyidea/editor/LatexQuoteInsertHandlerTest.kt
Fixes #1425
* Don't replace quotes after a backslash, so you can always type `\"`
* Handle insertion at end of document properly
* Assume opening quotes are needed for csquotes whenever a close brace is not next
```latex
test typing \enquote{quoted} text and ``ligatures'' and \lq\lq{}commands\rq\rq{} and "offf"
```
> Improve quote insert handler 

- src/nl/hannahsten/texifyidea/gutter/LatexNavigationGutter.kt
- src/nl/hannahsten/texifyidea/reference/InputFileReference.kt
- src/nl/hannahsten/texifyidea/util/files/LatexPackageLocationCache.kt
Fixes #1424
* Cache locations in memory (as String)
* Multiple calls to kpsewhich may still occur while adding to the cache concurrently
Have lots of usepackages, I guess
> Cache for LaTeX package locations

- src/nl/hannahsten/texifyidea/lang/LatexRegularCommand.kt
- src/nl/hannahsten/texifyidea/util/Magic.kt
Fixes #1435
- Add `\subfileinclude` as include command, with supported extension `.tex`.
- As for `\include`, the file extension should not be provided (only the base name).
Create a `main.tex` file with `\subfileinclude{test}`, and another file `test.tex` with
```latex
\documentclass[main.tex]{subfiles}
Test!
\end{document}
```
> Support for \subfileinclude

- resources/META-INF/plugin.xml
- src/nl/hannahsten/texifyidea/action/preview/PreviewAction.kt
Fix #1503
I didn't check whether we need to unregister them on plugin unload, and how we would need to do that.
> Only register equation and tikz preview tool windows when needed

- src/nl/hannahsten/texifyidea/psi/LatexParameterTextUtil.kt
- src/nl/hannahsten/texifyidea/util/Magic.kt
- test/nl/hannahsten/texifyidea/inspections/latex/NonAsciiCharactersInspectionTest.kt
- test/nl/hannahsten/texifyidea/reference/LatexEnvironmentReferenceTest.kt
Fix #1499
* Return null in `getNameIdentifier` for commands that do not have identifiers as parameter 
* Fix environment rename and add test for it
> Disable non-ascii inspection in non-identifiers

- src/nl/hannahsten/texifyidea/inspections/latex/LatexFigureNotReferencedInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/LatexFileNotFoundInspection.kt
- src/nl/hannahsten/texifyidea/lang/CommandManager.kt
- src/nl/hannahsten/texifyidea/lang/LabelingCommandInformation.kt
- src/nl/hannahsten/texifyidea/psi/LatexParameterTextUtil.kt
- src/nl/hannahsten/texifyidea/util/Labels.kt
- test/nl/hannahsten/texifyidea/inspections/latex/LatexFigureNotReferencedInspectionTest.kt
- test/nl/hannahsten/texifyidea/inspections/latex/LatexLabelConventionInspectionTest.kt
- test/nl/hannahsten/texifyidea/inspections/latex/LatexUnresolvedReferenceInspectionTest.kt
- test/nl/hannahsten/texifyidea/psi/LatexParameterTextUtilTest.kt
Fix #1493
* Handle label prefixes
* Fix some other false positives in newcommand definitions
```latex
\usepackage{graphicx}
\newcommand{\includenamedimage}[2]{
\begin{figure}
\centering
\includegraphics[width=\textwidth]{#1}
\caption{#2}
\label{fig:#1}
\end{figure}
}
\includenamedimage{test2.png}{caption}
some text~\ref{fig:test2.png} more text.
\end{document}
```
> Add support for label prefixing to commandmanager

- resources/META-INF/plugin.xml
- src/nl/hannahsten/texifyidea/folding/LatexEscapedSymbolFoldingBuilder.kt
Fix #1505
* Added code folding for `\$`, `\#`, `\%`, `\&` and `\_`
* Each command will be folded to the character it is producing 
The commands in the following snipped are all foldable (pressing <kbd>cmd</kbd> + <kbd>-</kbd> on one of them)
```latex
100\% 
H\&M
\#hashtag
\$50
some\_thing
```
> Fix: #1505 Added folding behavior to escaped symbols

- src/nl/hannahsten/texifyidea/inspections/LatexGrammarCheckingStrategy.kt
@fberlakovich The problem is that (if you remove the `getIgnoredRuleGroup` method I just added) this is a false positive:
`Text before $\alpha$ inline math`
because LatexNormalText is a context root, which ends right before the inline math. If this is the only text in a file, there is no psi element which spans everything, so I don't know a good context root candidate. But perhaps it can be solved in a different way.
> Temporarily disable punctuation rulegroup to avoid false positive

- src/nl/hannahsten/texifyidea/util/files/ReferencedFileSetCache.kt
- test/nl/hannahsten/texifyidea/reference/LatexLabelCompletionTest.kt
Fix #1543
* ReferencedFileSetCache now waits for the ReadAction to complete before returning the cache result. As the result is required directly after the coroutine operation, running in a non blocking way does not bring any advantages.
Completion tests should not be flaky anymore.
> Fix a race condition in ReferencedFileSetCache

- src/nl/hannahsten/texifyidea/inspections/latex/LatexInclusionLoopInspection.kt
- src/nl/hannahsten/texifyidea/util/Magic.kt
- src/nl/hannahsten/texifyidea/util/files/PsiFile.kt
- test/nl/hannahsten/texifyidea/inspections/latex/LatexInclusionLoopInspectionTest.kt
- test/resources/inspections/latex/inclusionloop/extensioninclusion.tex
Fix #1560 
* The FileInclusionLoopInspect now takes into account the file extension of include commands
The example in #1560 now works as expected. A test is included in the P.
> Fix file inclusion loop inspection to honor file extensions

- src/nl/hannahsten/texifyidea/run/latex/logtab/LatexFileStack.kt
- src/nl/hannahsten/texifyidea/util/Labels.kt
> Include optional parameters in position when looking for labels from redefined commands

- src/nl/hannahsten/texifyidea/action/preview/PreviewAction.kt
- src/nl/hannahsten/texifyidea/run/compiler/LatexCompiler.kt
- src/nl/hannahsten/texifyidea/util/LatexmkRcFileFinder.kt
Fix #1586
* Don't add compiler arguments for latexmk if latexmkrc file is found
Create .latexmkrc with for example `$pdf_mode = 5;` and check it builds with xelatex
> Add support for latexmkrc files, 

- src/nl/hannahsten/texifyidea/inspections/latex/LatexPackageNotInstalledInspection.kt
- src/nl/hannahsten/texifyidea/util/Packages.kt
- test/nl/hannahsten/texifyidea/reference/LatexEnvironmentReferenceTest.kt
Previously, the inspection was running `tlmgr search` on every inspection run when there was a \usepackage statement in the file containing a package which was not installed.
> Speed up LatexPackageNotInstalledInspection.kt

- src/nl/hannahsten/texifyidea/inspections/latex/LatexMissingLabelInspection.kt
- src/nl/hannahsten/texifyidea/run/compiler/LatexCompiler.kt
- src/nl/hannahsten/texifyidea/run/latex/LatexRunConfiguration.kt
- src/nl/hannahsten/texifyidea/util/LatexmkRcFileFinder.kt
- src/nl/hannahsten/texifyidea/util/Magic.kt
Fix #1592
* Default to 'default' when latexmkrc is used, but keeps possibility to override output format
> Add 'default' option to run config UI for latexmkrc

- src/nl/hannahsten/texifyidea/lang/CommandManager.kt
- src/nl/hannahsten/texifyidea/psi/LatexParameterTextUtil.kt
- src/nl/hannahsten/texifyidea/reference/LatexLabelParameterReference.kt
- src/nl/hannahsten/texifyidea/util/Labels.kt
- src/nl/hannahsten/texifyidea/util/Magic.kt
- test/nl/hannahsten/texifyidea/inspections/latex/LatexDuplicateLabelInspectionTest.kt
- test/nl/hannahsten/texifyidea/inspections/latex/LatexUnresolvedReferenceInspectionTest.kt
Fix #1594 
* Optional parameters are ignored for now
* Fix environment rename (was broken when renaming from \begin)
see issue/test
> Ignore optional parameters for newcommand definitions

- .editorconfig
- build.gradle.kts
- resources/META-INF/plugin.xml
- resources/inspectionDescriptions/LatexDocumentclassNotInRoot.html
- src/nl/hannahsten/texifyidea/inspections/latex/LatexDocumentclassNotInRootInspection.kt
- src/nl/hannahsten/texifyidea/util/files/FileSet.kt
- src/nl/hannahsten/texifyidea/util/files/ReferencedFileSetCache.kt
- src/nl/hannahsten/texifyidea/util/files/ReferencedFileSetService.kt
- src/nl/hannahsten/texifyidea/util/files/RootFile.kt
- src/nl/hannahsten/texifyidea/util/files/impl/ReferencedFileSetServiceImpl.kt
- test/nl/hannahsten/texifyidea/inspections/latex/LatexDocumentclassNotInRootInspectionTest.kt
- test/resources/inspections/latex/documentclassnotinroot/main.tex
- test/resources/inspections/latex/documentclassnotinroot/preamble.sty
Fix #1612. 
* Use the document environment to determine root files instead of the document class.
* Add an inspection that warns you when you have separated the document environment and document class.
* Introduces a cache to store the root file**s** for each file. Note that it is perfectly fine for LaTeX documents to have multiple root files. Other than the introduction of this cache, TeXiFy does not handle multiple root files anywhere (yet). However, the function `PsiFile.findRootFile()` is now deprecated in favor of `PsiFile.findRootFiles()` to encourage/force us to explicitly handle the cases of multiple root files. E.g., including a use package in all root files instead of in just one of the root files.
* To my knowledge, the `root` magic comment works fine at the moment, see the …
> Root files

- src/nl/hannahsten/texifyidea/reference/InputFileReference.kt
- src/nl/hannahsten/texifyidea/util/Magic.kt
- src/nl/hannahsten/texifyidea/util/files/LatexPackageLocationCache.kt
Fix #1616 
* kpsewhich was only used for sty/cls files, but it actually works for other file types like bib/tex as well
Create a LaTeX file, for example `~/texmf/tex/latex/included.tex` and input it.
> Don't only use kpsewhich for sty/cls files

- build.gradle.kts
- src/nl/hannahsten/texifyidea/inspections/TexifyRegexInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/LatexMissingLabelInspection.kt
- src/nl/hannahsten/texifyidea/intentions/LatexAddLabelIntention.kt
- test/nl/hannahsten/texifyidea/inspections/TexifyInspectionTestBase.kt
- test/nl/hannahsten/texifyidea/inspections/latex/LatexMissingLabelInspectionTest.kt
* Pass the command from the inspection to the `LatexAddLabelIntention`. Before, the intention could only guess which command to apply the fix to by looking at the position of the cursor. As a result, when using the fix all intention, it would try to fix all the missing label warnings on the command the cursor is currently on.
```latex
\section{one<caret>}
\section{two}
```
Use the `fix all ... problems in file` intention of the missing label inspection.
> Fix the fix all problems in file for the missing label inspection

- resources/inspectionDescriptions/LatexNonMatchingIf.html
- src/nl/hannahsten/texifyidea/inspections/latex/LatexNonMatchingIfInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/LatexUnresolvedReferenceInspection.kt
- src/nl/hannahsten/texifyidea/lang/LatexRegularCommand.kt
- src/nl/hannahsten/texifyidea/util/Magic.kt
- test/nl/hannahsten/texifyidea/inspections/latex/LatexNonMatchingIfInspectionTest.kt
* Fix #1635 negative offset in LatexUnresolvedReferenceInspection
* Fix #1628 by only requiring known \if-like commands to be closed
> Negative offset and unclosed \if inspection

- src/nl/hannahsten/texifyidea/run/latex/LatexOutputPath.kt
... because that leads to using the Jetbrains /bin folder as output path.
> Avoid empty output paths

- src/nl/hannahsten/texifyidea/highlighting/LatexTypedHandler.kt
- src/nl/hannahsten/texifyidea/inspections/latex/LatexMathOperatorEscapeInspection.kt
- test/nl/hannahsten/texifyidea/inspections/latex/LatexMathOperatorEscapeInspectionTest.kt
* `$bl<caret>a`, type <kbd>$</kbd> now produces `$bl$<caret>a` instead of `$bla<caret>`
* Fix that `$\text{max}$` triggered the unescaped math operator inspection even though `max` is inside text and does not have to be escaped.
```latex
$cos$
$\cos$
$\text{cos}$
\[
\begin{cases}
1 & \text{if $cos(x) = 1$} \\
0 & \text{otherwise}
\end{cases}
\]
```
> Closing $ and escaping math operator

- resources/liveTemplates/LaTeX.xml
Copied them from exported IntelliJ settings
Fix #1700
* Added 2 new live templates for enquote and for footcite
Write enq, should expand to 
```latex
\enquote{} 
```
and cursor should be convenient.
Write fc, should expand to 
```latex
\footcite[]{}
```
and cursors should be convenient.
Relevant wiki Link would be https://github.com/Hannah-Sten/TeXiFy-IDEA/wiki/Live-templates, but there is also no description of existing templates so I guess documenting this would not fit
> Added my templates to fix #1700

- resources/nl/hannahsten/texifyidea/icons/bibliography-file_smaller.svg
- resources/nl/hannahsten/texifyidea/icons/class-file_smaller.svg
- resources/nl/hannahsten/texifyidea/icons/doc-latex-file_smaller.svg
- resources/nl/hannahsten/texifyidea/icons/dvi-file_smaller.svg
- resources/nl/hannahsten/texifyidea/icons/file_smaller.svg
- resources/nl/hannahsten/texifyidea/icons/latex-file_smaller.svg
- resources/nl/hannahsten/texifyidea/icons/pdf-file_smaller.svg
- resources/nl/hannahsten/texifyidea/icons/style-file_smaller.svg
- resources/nl/hannahsten/texifyidea/icons/synctex-file_smaller.svg
- resources/nl/hannahsten/texifyidea/icons/text-file_smaller.svg
- resources/nl/hannahsten/texifyidea/icons/tikz-file_smaller.svg
- src/nl/hannahsten/texifyidea/TexifyIcons.kt
- src/nl/hannahsten/texifyidea/gutter/LatexNavigationGutter.kt
Fixed #1706: Gutter icons for file navigation changed to 12x12.
- New 'smaller' variants added of file icons: does not feature the extension, but just an empty bar. The colours match the larger variant.
- getIconFromExtension now accepts a smaller flag.
- Added DVI to the getIconFromExtension.
- The icon used for the gutter setting now uses the smaller icon.
- Use the VirtualFile's extension property instead of our util.
- synctex.gz is now recognised as extension by the gutter.
> Fixed #1706: Gutter icons for file navigation changed to 12x12.

- src/nl/hannahsten/texifyidea/util/files/LatexPackageLocationCache.kt
Fixes #1424 variant: PackageLocationCache kept calling kpsewhich when the cache contains a null value.
- Replaced the use of 'getOrPut' by custom code using 'containsKey'. getOrPut re-evaluates the defaultValue function when the value is null, which happens when the key is absent, or when there is a key with a null-value => unnecessary kpsewhich calls.
- See https://youtrack.jetbrains.com/issue/KT-21392
> Fixed PackageLocationCache calling kpsewhich when the cache contains a null value.

- src/nl/hannahsten/texifyidea/intentions/LatexAddLabelIntention.kt
- test/nl/hannahsten/texifyidea/intentions/LatexAddLabelIntentionTest.kt
Fix #1718
* Fix the test class by specifying the intended intention action. The testcases were failing on my computer because the "Add label" intention was not the first intetion in the list
* Fix the "Add label" intention for commands that are neither labeled with parameters nor have a required parameter to determine the label name.
See the included testcase and the description in #1718.
> Fix add label intention for items

- src/nl/hannahsten/texifyidea/gutter/LatexCompileGutter.kt
Fixed #1734 
Compile gutter icon now only targets the \begin token, not all parameters.
> Compile gutter icons now only show up at the \begin token

- resources/META-INF/plugin.xml
- resources/liveTemplates/LaTeX.xml
- src/nl/hannahsten/texifyidea/templates/macros/LatexFormatAsLabelMacro.kt
Add live templates for sectioning commands that automatically also inserts a label.
The prefix with `\` is intentional: as to not bother the user with too many live template popups during normal typing (and accidentally activating them).
Demo: For some reason the GIF is just a bit too slow for comfort (it's definitely not due to my typing speed)
> Sectioning commands with label live template

- src/nl/hannahsten/texifyidea/reference/InputFileReference.kt
- src/nl/hannahsten/texifyidea/util/files/FileSet.kt
- src/nl/hannahsten/texifyidea/util/files/PsiFile.kt
- src/nl/hannahsten/texifyidea/util/files/ReferencedFileSetCache.kt
- test/nl/hannahsten/texifyidea/run/logtab/LatexOutputListenerTest.kt
* Previously, refreshing fileset cache was taking about 10 seconds for my test project (460 include commands in hundreds of files), but I found out 9 seconds of that were taken by the code which resolves graphics files (because of finding `\graphicspath` commands in the file set), however I don't think we use graphics files being in the file set anywhere, so I disabled it for file set resolves.
> Performance improvement for fileset cache creation

- gen/nl/hannahsten/texifyidea/parser/LatexParser.java
- src/nl/hannahsten/texifyidea/grammar/Latex.bnf
- src/nl/hannahsten/texifyidea/inspections/latex/LatexDuplicateLabelInspection.kt
- test/nl/hannahsten/texifyidea/inspections/latex/LatexDuplicateLabelInspectionTest.kt
- test/nl/hannahsten/texifyidea/psi/LatexCommandsImplUtilTest.kt
Addresses additions suggested in #1698
* Allow empty keyval values (e.g., `\lstinputlisting[caption=,label=somelabel]`)
* Correctly parse trailing comma in optional parameters (e.g., `\lstinputlisting[label=somelabel,]`)
* Support labels in optional parameters in duplicate label inspection
Observe the inspection error in 
```latex
\lstinputlisting[label=somelabel]{some/file}
\begin{lstlisting}[label=somelabel]
\end{lstlisting}
\end{document}
```
No more errors in 
```latex
\lstinputlisting[caption=,label=somelabel]{some/file}
\lstinputlisting[label=someotherlabel,]{some/file}
\end{document}
```
See also the included test cases.
The PR only fixes issues / extends existing features.
> Support lstinputlisting label

- src/nl/hannahsten/texifyidea/completion/LatexCommandProvider.kt
- src/nl/hannahsten/texifyidea/lang/LatexPackage.kt
- src/nl/hannahsten/texifyidea/util/General.kt
- src/nl/hannahsten/texifyidea/util/Strings.kt
[TEX-96](https://texify-idea.myjetbrains.com/youtrack/issue/TEX-96). @`master` bde9600650292d1896862c2a218ee3ab17a3c91f
Not an issue on `b0.7.3`.
See video. Autocompletion of `\begin` results in:
```latex
\begin Package{}{<caret>}
\end{}
```
* Fixed \begin AC inserting extra Package{}
* Fixed GeneralKt String.repeat().
What went wrong:
https://user-images.githubusercontent.com/17410729/106025044-aef5c480-60c8-11eb-8082-279f5565e635.mp4
> Fixed \begin AC inserting extra Package{}

- resources/liveTemplates/LaTeX.xml
- src/nl/hannahsten/texifyidea/editor/LatexQuoteInsertHandler.kt
- src/nl/hannahsten/texifyidea/templates/LatexContext.kt
- src/nl/hannahsten/texifyidea/util/Psi.kt
- src/nl/hannahsten/texifyidea/util/magic/EnvironmentMagic.kt
Fixes [TEX-22](https://texify-idea.myjetbrains.com/youtrack/issue/TEX-22).
* Disabled smart quote substitution in verbatim environments.
* Disabled default intentions in verbatim environments (fig, tab, etc.)
- Updated [Features](https://github.com/Hannah-Sten/TeXiFy-IDEA/wiki/Features), fixed smart quotes link.
- Updated [Global settings](https://github.com/Hannah-Sten/TeXiFy-IDEA/wiki/Global-settings#option-to-enable-smart-quote-substitution)
- Updated [Live templates](https://github.com/Hannah-Sten/TeXiFy-IDEA/wiki/Live-templates)
> Disable smart quotes and default live templates in verbatim.

- src/nl/hannahsten/texifyidea/completion/LatexCommandProvider.kt
- src/nl/hannahsten/texifyidea/index/file/LatexExternalCommandDataIndexer.kt
- src/nl/hannahsten/texifyidea/index/file/LatexExternalCommandIndex.kt
- test/nl/hannahsten/texifyidea/index/file/LatexExternalCommandDataIndexerTest.kt
Fix #1760
* Add commands defined in packages with \def to autocompletion
* When the same command, both from LaTeX base, is already added to autocompletion, don't add it to avoid duplicates (you would get like 8 \par commands in the autocompletion otherwise)
I kept the commands from other packages:
> Add commands defined with \def to autocompletion

- build.gradle.kts
- resources/META-INF/plugin.xml
- src/nl/hannahsten/texifyidea/action/analysis/WordCountAction.kt
- src/nl/hannahsten/texifyidea/inspections/latex/LatexCollapseCiteInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/LatexCommandAlreadyDefinedInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/LatexDuplicateDefinitionInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/LatexMissingImportInspection.kt
- src/nl/hannahsten/texifyidea/run/latex/LatexRunConfiguration.kt
- src/nl/hannahsten/texifyidea/settings/sdk/MiktexSdk.kt
- src/nl/hannahsten/texifyidea/util/Strings.kt
- src/nl/hannahsten/texifyidea/util/SystemEnvironment.kt
- test/nl/hannahsten/texifyidea/inspections/latex/LatexCollapseCiteInspectionTest.kt
- test/nl/hannahsten/texifyidea/inspections/latex/LatexCommandAlreadyDefinedInspectionTest.kt
Fix  [TEX-93](https://texify-idea.myjetbrains.com/youtrack/issue/TEX-93)
Fix #1757
Fix #1723 
Fix #1753 
Fix #1765 (well, workaround)
* Apparently the 'where' command on Windows can return multiple paths
I think the bug is already in 0.7.3, but I assume it can only happen if you have multiple MiKTeX installs.
* Add BSTINPUTS by default to bibtex run config, similar to BIBINPUTS
* Use texcount for word count if available. Not perfect, but good enough for now.
* Fix false positive for missing import inspection: when command is being defined
* Make 'command already defined' a warning, because the original command may not be imported (maybe we should check for this)
> Support multiple MiKTeX installations in MiktexSDK, bstinputs, texcount and command redefinitions

- resources/META-INF/plugin.xml
- src/nl/hannahsten/texifyidea/action/wizard/graphic/InsertGraphicWizardAction.kt
- src/nl/hannahsten/texifyidea/action/wizard/table/LatexTableWizardAction.kt
* Added Graphic wizard action to generate menu.
* Added Table wizard action to generate menu.
* Graphic and table wizard items get hidden outside Latex contexts.
- Updated [Menu Entries](https://github.com/Hannah-Sten/TeXiFy-IDEA/wiki/Menu-entries)
> Added Graphic/Table Wizards in generate actions

- resources/META-INF/plugin.xml
- src/nl/hannahsten/texifyidea/completion/handlers/LatexCommandArgumentInsertHandler.kt
- src/nl/hannahsten/texifyidea/completion/handlers/LatexNoMathInsertHandler.kt
- src/nl/hannahsten/texifyidea/index/file/LatexIndexableSetContributor.kt
- src/nl/hannahsten/texifyidea/settings/sdk/LatexSdk.kt
- src/nl/hannahsten/texifyidea/settings/sdk/LatexSdkUtil.kt
- src/nl/hannahsten/texifyidea/settings/sdk/MiktexLinuxSdk.kt
- src/nl/hannahsten/texifyidea/settings/sdk/MiktexWindowsSdk.kt
- src/nl/hannahsten/texifyidea/settings/sdk/NativeTexliveSdk.kt
Fix #1761
* MiKTeX on Linux (and I think the one for Mac is similar) is very different from anything else I've seen so far.
* Interestingly, it seems to work pretty well so far, including indexing package sources (didn't find docs yet though)
* Fix MiKTeX SDK not being suggested 
* Fix autocomplete not removing package for pseudocode commands ([TEX-105](https://texify-idea.myjetbrains.com/youtrack/issue/TEX-105))
See wiki
> Add SDK type for MiKTeX on Linux

- README.md
- gen/nl/hannahsten/texifyidea/grammar/BibtexLexer.java
- src/nl/hannahsten/texifyidea/BibtexParserDefinition.kt
- src/nl/hannahsten/texifyidea/action/ClearGeneratedFiles.kt
- src/nl/hannahsten/texifyidea/grammar/BibtexLexer.flex
- src/nl/hannahsten/texifyidea/inspections/latex/LatexLineBreakInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/LatexSpaceAfterAbbreviationInspection.kt
- src/nl/hannahsten/texifyidea/settings/sdk/LatexSdkUtil.kt
- src/nl/hannahsten/texifyidea/settings/sdk/MiktexWindowsSdk.kt
- src/nl/hannahsten/texifyidea/settings/sdk/NativeTexliveSdk.kt
- src/nl/hannahsten/texifyidea/util/General.kt
- src/nl/hannahsten/texifyidea/util/Projects.kt
- src/nl/hannahsten/texifyidea/util/files/RootFile.kt
- src/nl/hannahsten/texifyidea/util/magic/PatternMagic.kt
- test/nl/hannahsten/texifyidea/inspections/latex/LatexLineBreakInspectionTest.kt
Fix #1783
Fix [TEX-31](https://texify-idea.myjetbrains.com/youtrack/issue/TEX-31)
Fix #1785
Fix #1786
Fix #1789
* Add quick fix for normal space to line break inspection
* Look in run configurations for possible paths to latex executables when using pycharm on a mac
* Fix #1786 (underscore in bibtex type)
* First sentence now has two quickfixes, second one still has only one.
```latex
In the uneven section, nondescript agencies of the note is found. Applications can also be appended by Sophie on Friday.
On average 77 quietly abject persons are objecting markets during these basements! However, it is various that, after the waiting time has been dealt, the vengeful lorem ipsum of the following need expect to insult it.
```
* Buy a mac, install pycharm, check kpsewhich is actually working
> Add quick fix for normal space to line break inspection

- src/nl/hannahsten/texifyidea/completion/LatexCommandProvider.kt
- src/nl/hannahsten/texifyidea/reference/InputFileReference.kt
- src/nl/hannahsten/texifyidea/settings/sdk/MiktexWindowsSdk.kt
- src/nl/hannahsten/texifyidea/settings/sdk/NativeTexliveSdk.kt
- src/nl/hannahsten/texifyidea/settings/sdk/TexliveSdk.kt
Fix #1793 (invalid windows path)
Fix #1795 (NPE rootFile)
Fix #1796 (executable path for native tex live)
* Improve autocompletion speed especially for texlive-full installations by caching lookupbuilders in memory (not sure if this is the way to go for performance improvements, but it works)
> Fix invalid windows path, NPE and wrong executable path for native tex live

- src/nl/hannahsten/texifyidea/index/file/LatexDocsRegexer.kt
- test/nl/hannahsten/texifyidea/index/file/LatexDocsRegexerTest.kt
- test/nl/hannahsten/texifyidea/index/file/LatexExternalCommandDataIndexerTest.kt
- test/nl/hannahsten/texifyidea/index/file/LatexExternalEnvironmentDataIndexerTest.kt
Fix [TEX-91](https://texify-idea.myjetbrains.com/youtrack/issue/TEX-91)
* Use HTML formatting in documentation popups, instead of removing the latex markup.
Try the quick documentation popup on some commands that have bold, italics, or verbatim text:
```latex
\RubikRotation
\labelformat
```
> Replace tex formatting with html formatting in documentation popup

- build.gradle.kts
- src/nl/hannahsten/texifyidea/LatexErrorReportSubmitter.kt
- src/nl/hannahsten/texifyidea/LatexParserDefinition.kt
Fix [TEX-122](https://texify-idea.myjetbrains.com/youtrack/issue/TEX-122)
When submitting an error report, automatically fill in:
- IntelliJ version and build number
- OS name, version, architecture
- TeXiFy version
---
Note: this is based on the [`sectioning-indent`](https://github.com/Hannah-Sten/TeXiFy-IDEA/tree/sectioning-indent) branch, so ideally that should be merged first.
> Auto fill error report

- src/nl/hannahsten/texifyidea/gutter/LatexElementColorProvider.kt
Fix #1858 
* Fix index out of bounds exception when color values are out of the range that their color model supports.
* Add support for setting a color definition by using the color picker from the color icon in the gutter.
```latex
\definecolor{jkl}{RGB}{300, 7, 7}
\definecolor{crashycrash}{RGB}{0.918, 0.439, 0.020}
\definecolor{blueish}{RGB}{229, 225, 15}
\definecolor{bloop}{HTML}{4cbb23}
\definecolor{whaaa}{cmy}{0.537, 0.063, 0.133}
\definecolor{help}{hsb}{0.800, 0.425, 0.655}
\definecolor{moon}{gray}{0.188}
```
> Change color in color definition via gutter

- src/nl/hannahsten/texifyidea/inspections/LatexGrammarCheckingStrategy.kt
- test/nl/hannahsten/texifyidea/inspections/grazie/GrazieInspectionTest.kt
- test/resources/inspections/grazie/MultilineCheckGrammar.tex
Fix #1857 
* Fix an off by one error which caused Grazie to see a cut off version of the first/last sentence (without the first/last character)
See the included test case or the example in #1857
> Fix Grazie LatexGrammarCheckingStrategy off by one error

- build.gradle.kts
- src/nl/hannahsten/texifyidea/ui/PreviewFormUpdater.kt
- src/nl/hannahsten/texifyidea/util/SystemEnvironment.kt
- src/nl/hannahsten/texifyidea/util/files/LatexPackageLocationCache.kt
Fix #1874, now for real.
Fix #962 (same cause)
Fix #1407 (same cause)
I found something to resolve the issue that we cannot run any latex executables on Mac because PATH is not known to us, see `EnvironmentUtil.getEnvironmentMap()`, but it seems to break all the tests.
> Executing commands on Mac

- src/nl/hannahsten/texifyidea/psi/LatexPsiHelper.kt
- test/nl/hannahsten/texifyidea/inspections/latex/codestyle/LatexMissingLabelInspectionTest.kt
Fix #1947
* `LatexPsiHelper#createFromText` returns a PsiFile, but when creating a psi element for a comma this PsiFile was actually inserted in the psi tree which was then automatically replaced by a DummyHolder, which then caused the WalkingState to fail because DummyHolder's `prevSibling` is not correct. So the error would actually only show when you walk the psi tree, which is why the test originally passed. Fixed it by inserting the actual element of the comma token.
@fberlakovich This was a quite hard to find bug, so maybe good to take note.
See `LatexMissingLabelInspectionTest#test quick fix in listings with other parameters`
> Fix bug in updating psi tree when inserting an optional label parameter for an environment

- src/nl/hannahsten/texifyidea/action/ForwardSearchAction.kt
- src/nl/hannahsten/texifyidea/run/linuxpdfviewer/InternalPdfViewer.kt
- src/nl/hannahsten/texifyidea/run/linuxpdfviewer/OpenViewerListener.kt
- src/nl/hannahsten/texifyidea/run/sumatra/SumatraConversation.kt
- src/nl/hannahsten/texifyidea/run/sumatra/SumatraForwardSearchListener.kt
Fix #1896
* It got disabled when the workflow was changed for other pdf viewers, and sumatra is handled separately. This should be improved with the new run configuration, but at least it works now again.
Install Sumatra, compile, try to forward search.
> Re-enable forward search action for sumatra

- resources/META-INF/extensions/run-configurations.xml
- src/nl/hannahsten/texifyidea/run/LatexProjectTaskRunner.kt
Fix #1965 
* The 'build project' button will now run all run configurations in the project (because I had to choose something, and this seemed the most sensible thing)
Click 'build project'
> Implement 'build project' button

- build.gradle.kts
- src/nl/hannahsten/texifyidea/completion/pathcompletion/LatexGraphicsPathProvider.kt
- src/nl/hannahsten/texifyidea/index/stub/LatexCommandsStubElementType.kt
- src/nl/hannahsten/texifyidea/reference/InputFileReference.kt
Fix #1842 
Fix #1952 
Fix #1979
We were indexing commands from all package sources also in the normal commands index (instead of only in external commands index), but we loop over all keys (200k) e.g. when finding all commands in one file, so this happens for basically every inspection but takes 3 seconds for 200k keys.
* When adding a command to the index, first check if it's being indexed because it's a package source.
This makes indexing between five and ten times slower, unfortunately, because of the string match check.
> Avoid indexing commands in latex package sources, maybe fixes #1842

- src/nl/hannahsten/texifyidea/TeXception.kt
- src/nl/hannahsten/texifyidea/highlighting/LatexAnnotator.kt
- src/nl/hannahsten/texifyidea/inspections/LatexGrammarCheckingStrategy.kt
* Change annotation with empty message to silent annotation
* Fix #1981 (stealthy ranges off by one)
Old situation:
> Remove empty tooltip

- build.gradle.kts
- src/nl/hannahsten/texifyidea/LatexErrorReportSubmitter.kt
- test/nl/hannahsten/texifyidea/util/LatestTexifyVersionTest.kt
Fix #1980 
* Get the latest available TeXiFy version from the JetBrains Marketplace instead of from our GitHub releases. 
* Marketplace API responds with XML instead of JSON, so this needed a different parser.
Create error and use the error submitter.
> Get plugin version from JetBrains Marketplace API instead of from our GitHub releases

- src/nl/hannahsten/texifyidea/lang/commands/LatexCommand.kt
- src/nl/hannahsten/texifyidea/run/compiler/LatexCompiler.kt
I inadvertently broke the Tectonic compilation, I forgot it's not installed with LaTeX but separately.
> Do not prefix Tectonic executable with SDK path

- src/nl/hannahsten/texifyidea/ui/PreviewFormUpdater.kt
- src/nl/hannahsten/texifyidea/util/SystemEnvironment.kt
Fix #2012
* When we timeout a command, there may still be error output, so that should be shown as well.
> Also return error output in case of timeout when running a command

- src/nl/hannahsten/texifyidea/formatting/LatexSpacingRules.kt
- test/nl/hannahsten/texifyidea/formatting/LatexFormattingTest.kt
Fix #2041 
* Check if section-like command is inside a definition on formatting, and do nothing when it is
Cases from issue:
```latex
\newcommand{\sectionlorem}[2]{\section{#1}\label{#2}}
\sectionlorem{Title}{sec:label}
\end{document}
```
```latex
\newenvironment{sectionitemize}[2]{\section{#1}\label{#2}\begin{itemize}}{\end{itemize}}
\begin{sectionitemize}{Title}{sec:label}
\item Lorem
\item Ipsum
\end{sectionitemize}
\end{document}
```
Nothing to add
> Fix #2041 formatting of section-like commands used in definitions

- src/nl/hannahsten/texifyidea/completion/LatexCommandProvider.kt
- src/nl/hannahsten/texifyidea/completion/LatexXColorProvider.kt
- src/nl/hannahsten/texifyidea/index/LatexIncludesIndex.kt
- src/nl/hannahsten/texifyidea/util/Commands.kt
- src/nl/hannahsten/texifyidea/util/Packages.kt
Fix #2027
* When TeX Live  is the system default, the autocompletion will only contain external commands from packages that are included anywhere in the project, directly or indirectly.
Since commands are only added to autocompletion during certain initialisation phases (at least startup, that I checked), commands will not directly be added when you add an extra package.
This at least avoids the many duplicates of the same commands, and also avoids putting commands in the autocompletion that nobody uses.
Now, this is still not ideal, because sometimes you _do_ want to suggest commands from not-included packages. But I don't see this happen unless we have some statistics on how much all commands are used (texstudio is maintaining that information manually, I believe) and from which …
> Reduce number of commands in autocompletion for TeX Live

- resources/META-INF/actions/actions.xml
- src/nl/hannahsten/texifyidea/action/reformat/ExternalReformatAction.kt
- src/nl/hannahsten/texifyidea/action/reformat/ReformatWithBibtexTidy.kt
- src/nl/hannahsten/texifyidea/action/reformat/ReformatWithLatexindent.kt
- src/nl/hannahsten/texifyidea/util/SystemEnvironment.kt
Fix #2030
* Add action to run bibtex-tidy on the contents of a bib file (depending on the bibtex-tidy version, it will replace the psi tree or just run it on the actual file)
Open bib file
code > reformat with bibtex-tidy
> Add 'reformat with bibtex-tidy' action

- build.gradle.kts
- gen/nl/hannahsten/texifyidea/parser/LatexParser.java
- gen/nl/hannahsten/texifyidea/psi/LatexAngleParam.java
- gen/nl/hannahsten/texifyidea/psi/LatexAngleParamContent.java
- gen/nl/hannahsten/texifyidea/psi/LatexParameter.java
- gen/nl/hannahsten/texifyidea/psi/LatexTypes.java
- gen/nl/hannahsten/texifyidea/psi/LatexVisitor.java
- gen/nl/hannahsten/texifyidea/psi/impl/LatexAngleParamContentImpl.java
- gen/nl/hannahsten/texifyidea/psi/impl/LatexAngleParamImpl.java
- gen/nl/hannahsten/texifyidea/psi/impl/LatexParameterImpl.java
- src/nl/hannahsten/texifyidea/grammar/Latex.bnf
- src/nl/hannahsten/texifyidea/run/compiler/LatexCompiler.kt
- src/nl/hannahsten/texifyidea/settings/sdk/LatexSdkUtil.kt
- test/nl/hannahsten/texifyidea/formatting/LatexFormattingTest.kt
Fix #2044
* Apparently beamer decided that using yet another symbol for parameters is a good idea: `<...>`
Formatting now doesn't break the document anymore:
```latex
\documentclass{beamer}
\begin{frame}
\begin{block}{1-}<1->
Contents 1.
\end{block}
\begin{block}{Title}<2->
Contents 2.
\end{block}
\end{frame}
\end{document}
```
> Add angular bracket parameter to parser

- src/nl/hannahsten/texifyidea/util/files/ReferencedFileSetCache.kt
Fix #2074, hopefully. I'm just guessing, as not sure what is causing the warning.
> Avoid slow operations on EDT for fileset cache update

- gen/nl/hannahsten/texifyidea/parser/BibtexParser.java
- gen/nl/hannahsten/texifyidea/psi/impl/BibtexEntryImpl.java
- src/nl/hannahsten/texifyidea/BibtexParserDefinition.kt
- src/nl/hannahsten/texifyidea/grammar/Bibtex.bnf
Fix [TEX-130](https://texify-idea.myjetbrains.com/youtrack/issue/TEX-130)
* Allow a bibtex field given in `{...}` to be empty.
```bibtex
@Book{knuth1990,
author    = {Knuth, Donald E.},
title     = {The {\TeX}book },
year      = {1990},
isbn      = {},
publisher = {Addison\,\textendash\,Wesley},
}
```
should not give a parse error.
> TEX-130: allow empty bib field

- resources/META-INF/extensions/intentions.xml
- src/nl/hannahsten/texifyidea/intentions/LatexVerbatimToggle.kt
- src/nl/hannahsten/texifyidea/lang/commands/LatexListingCommand.kt
- src/nl/hannahsten/texifyidea/psi/LatexPsiHelper.kt
- src/nl/hannahsten/texifyidea/ui/PopupChooserCellRenderer.kt
- src/nl/hannahsten/texifyidea/util/magic/CommandMagic.kt
- src/nl/hannahsten/texifyidea/util/magic/EnvironmentMagic.kt
Fix [TEX-41](https://texify-idea.myjetbrains.com/youtrack/issue/TEX-41)
* Added intention to toggle between different verbatim environments/commands (similar to the math environments toggle)
```latex
Have some \verb|\verb?test?| in this sentence
\end{document}
```
> Add verbatim toggle intention

- src/nl/hannahsten/texifyidea/completion/LatexCommandsAndEnvironmentsCompletionProvider.kt
Fix #2106
* Number the required parameters in autocompletion, which fixes #2106.
```latex
\newcommand{\test}[3][1]{#1#2#3}
\newcommand{\foo}[2]{#1#2}
% Document
\test
\foo
\end{document}
```
Unfortunately it's not possible to write a test that checks for two arguments in the tail text of the autocompletion. The `LookupElementPresentation` that contains the tail text is private in the `LookupElementBuilder`, and we cannot access it.
> Number required parameters in auto completion (#2106)

- src/nl/hannahsten/texifyidea/run/latex/LatexRunConfiguration.kt
Fix https://github.com/Hannah-Sten/TeXiFy-IDEA/issues/2165
* Use File.pathSeparator as path separator for BIBINPUTS.
Refer to https://github.com/Hannah-Sten/TeXiFy-IDEA/issues/2165
> Use File.pathSeparator as path separator for BIBINPUTS.

- src/nl/hannahsten/texifyidea/file/BibtexFileType.kt
- src/nl/hannahsten/texifyidea/file/ClassFileType.kt
- src/nl/hannahsten/texifyidea/file/LatexFileType.kt
- src/nl/hannahsten/texifyidea/file/LatexSourceFileType.kt
- src/nl/hannahsten/texifyidea/file/StyleFileType.kt
- src/nl/hannahsten/texifyidea/file/TikzFileType.kt
- test/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexUnresolvedReferenceInspectionTest.kt
Fix #2193
Fix #2195
* There must be something really odd going on with localisation, otherwise I can't image how this occurred.
> Override display names of filetypes to avoid conflict

- src/nl/hannahsten/texifyidea/inspections/latex/redundancy/LatexDuplicateDefinitionInspection.kt
- test/nl/hannahsten/texifyidea/inspections/latex/redundancy/LatexDuplicateDefinitionInspectionTest.kt
Per issue #2199, a strict command definition followed by a non-strict command definition is valid LaTeX. This change ensures this use case is not incorrectly flagged as an error by the plugin inspector.
Fix #2199.
* Duplicate definition inspection will now only inspect strict command definitions instead of all command definitions.
* A single `\renewcommand` for an undefined command will not compile, but is not flagged as an error by the inspector. This was an issue before this PR, and is addressed by #2201, so this is not a regression.
* Placing the `\renewcommand` before the `\newcommand` before a particular command will not be flagged as an error, but will not compile. This is _technically_ a regression, as this would be flagged before this PR, but the _correct_ ordering of …
> Inspect only strict duplicated command definitions.

- src/nl/hannahsten/texifyidea/inspections/latex/codestyle/LatexUsePackageInPackageInspection.kt
- test/nl/hannahsten/texifyidea/inspections/TexifyInspectionTestBase.kt
- test/nl/hannahsten/texifyidea/inspections/latex/TexifyRegexInspectionTestBase.kt
- test/nl/hannahsten/texifyidea/inspections/latex/codestyle/LatexUsePackageInPackageInspectionTest.kt
The `\usepackage in package` inspection only checked for a required argument, while the `\usepackage` syntax is
```latex
\usepackage[<options>]{<package name>}[<version info>]
```
I've added the missing cases to the inspection. Tests included.
* See test cases.
* Try the quick fis in a sty file:
```latex
\usepackage{xcolor}
\usepackage[colorlinks]{hyperref}
```
> Add missing cases in usepackage in package inspection

- resources/META-INF/actions/actions.xml
- resources/META-INF/actions/editmenu.xml
- resources/META-INF/actions/toolsmenu.xml
- src/nl/hannahsten/texifyidea/startup/AnalyzeMenuRegistration.kt
Fix #2206 
* Override the names of the different LaTeX menu groups so they are distinguishable in the find actions dialog. 
* Removed the action group that surrounded the word count action. It's not needed, we only show the word count action when a LaTeX file is active anyway. To avoid confusion, I have overridden the name of the action to be `LaTeX Word Count` in the find actions dialog.
Search for `latex` in the find actions dialog.
> Override names of LaTeX action groups in find action dialog

- build.gradle.kts
- src/nl/hannahsten/texifyidea/util/text/TexifyIpsumGenerator.kt
Fix #2189
* The plugin was built on Linux, but the line separator of the user was used so Windows users couldn't read the dummy text file.
> Fix newlines in reading dummy text input

- src/nl/hannahsten/texifyidea/run/latex/ui/LatexSettingsEditor.kt
Fix #2114 
* Auxil path won't be overwritten anymore when using placeholders
Open the Run configuration template for LaTeX files and change the auxiliary path to something that uses the placeholder
> Auxil path won't be overwritten anymore when using placeholders

- src/nl/hannahsten/texifyidea/completion/LatexCommandsAndEnvironmentsCompletionProvider.kt
- src/nl/hannahsten/texifyidea/settings/sdk/LatexSdkUtil.kt
- src/nl/hannahsten/texifyidea/settings/sdk/MiktexLinuxSdk.kt
- src/nl/hannahsten/texifyidea/settings/sdk/MiktexWindowsSdk.kt
- src/nl/hannahsten/texifyidea/settings/sdk/NativeTexliveSdk.kt
- src/nl/hannahsten/texifyidea/settings/sdk/TexliveSdk.kt
Fix #2184
* Don't give a notification in case the path that is checked probably comes from TeXiFy and not from the user.
* Fix autocompletion filtering for texlive, which caused indexed commands from the default package not to be included
> Don't send notification for SDK paths that are checked in the background

- resources/META-INF/extensions/editor/editor.xml
- src/nl/hannahsten/texifyidea/editor/typedhandlers/LatexEnterInEnumerationHandler.kt
- test/nl/hannahsten/texifyidea/editor/typedhandlers/LatexEnterInEnumerationHandlerTest.kt
Fix #2137
* Ignore nested items when finding the last \item in an environment
```latex
\begin{enumerate}
\item foo
\item[bla] bar
\begin{itemize}
\item[floo]
\end{itemize} <caret>
\end{enumerate}
\end{document}
```
> Ignore nested enumerations when finding the item marker

- src/nl/hannahsten/texifyidea/action/preview/JlatexmathPreviewer.kt
- src/nl/hannahsten/texifyidea/completion/LatexCompletionContributor.kt
- src/nl/hannahsten/texifyidea/formatting/spacingrules/TableAlignRule.kt
- src/nl/hannahsten/texifyidea/inspections/latex/codestyle/LatexLabelConventionInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexEscapeAmpersandInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/redundancy/LatexDuplicateLabelInspection.kt
- src/nl/hannahsten/texifyidea/lang/DefaultEnvironment.kt
- src/nl/hannahsten/texifyidea/lang/alias/AliasManager.kt
- src/nl/hannahsten/texifyidea/lang/alias/CommandManager.kt
- src/nl/hannahsten/texifyidea/lang/alias/EnvironmentManager.kt
- src/nl/hannahsten/texifyidea/psi/LatexCommandsImplUtil.kt
- src/nl/hannahsten/texifyidea/psi/LatexEnvironmentUtil.kt
- src/nl/hannahsten/texifyidea/structure/latex/LatexLabelPresentation.kt
- src/nl/hannahsten/texifyidea/util/labels/LabelExtraction.kt
- src/nl/hannahsten/texifyidea/util/labels/ProjectLabels.kt
- src/nl/hannahsten/texifyidea/util/magic/CommandMagic.kt
- src/nl/hannahsten/texifyidea/util/magic/EnvironmentMagic.kt
- test/nl/hannahsten/texifyidea/inspections/latex/codestyle/LatexFigureNotReferencedInspectionTest.kt
- test/nl/hannahsten/texifyidea/inspections/latex/codestyle/LatexMissingLabelInspectionTest.kt
- test/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexEscapeAmpersandInspectionTest.kt
- test/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexUnresolvedReferenceInspectionTest.kt
- test/nl/hannahsten/texifyidea/inspections/latex/redundancy/LatexDuplicateLabelInspectionTest.kt
- test/nl/hannahsten/texifyidea/lang/CommandManagerTest.kt
- test/nl/hannahsten/texifyidea/psi/LatexParameterTextUtilTest.kt
Fixes #2162 
Fix #2223
* Add EnvironmentManager similar to CommandManager, migrate common code to AliasManager
* Moved the CommandManager class
* Register the tabular-like environments
* Added the `tabulary` environment to the default table environments
No inspection warning, and table formatting works:
```latex
\newenvironment{table2}
{ \begin{tabular}{ c c c } }
{ \end{tabular} }
\begin{table2}
a      & b & c \\
bbbbbb & c & d \\
\end{table2}
\end{document}
```
> Recognise custom environments as defining a tabular environment

- resources/META-INF/extensions/inspections/latex/probablebugs/probablebugs.xml
- resources/inspectionDescriptions/LatexUndefinedCommand.html
- src/nl/hannahsten/texifyidea/completion/LatexCommandsAndEnvironmentsCompletionProvider.kt
- src/nl/hannahsten/texifyidea/inspections/latex/codestyle/LatexFigureNotReferencedInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexFileNotFoundInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexUndefinedCommandInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexUnresolvedReferenceInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/packages/LatexUndefinedCommandInspection.kt
- src/nl/hannahsten/texifyidea/reference/CommandDefinitionReference.kt
- src/nl/hannahsten/texifyidea/structure/latex/LatexStructureViewElement.kt
- src/nl/hannahsten/texifyidea/util/Commands.kt
- src/nl/hannahsten/texifyidea/util/PsiCommands.kt
- src/nl/hannahsten/texifyidea/util/files/PsiFile.kt
- src/nl/hannahsten/texifyidea/util/magic/CommandMagic.kt
- test/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexUndefinedCommandInspectionTest.kt
Fix #2201
We already have the missing import inspection, but it only works on commands that are already hardcoded in TeXiFy. There is a good reason it doesn't error on the other unknown commands: many of the valid commands are not yet indexed.
This PR adds an inspection which does just that, and which is then of course disabled by default.
It is mainly useful for finding issues with the external commands data indexer, at the moment. (e.g. #2190)
Example command that is in index but not hardcoded: `\branch` from koma-script.
> Add undefined commands inspection

- build.gradle.kts
- src/nl/hannahsten/texifyidea/editor/folding/LatexImportFoldingBuilder.kt
- src/nl/hannahsten/texifyidea/util/files/PsiFile.kt
After #2232 I received some errors from `SlowOperations#assertSlowOperationsAreAllowed`, but they came only from the folding builders that accessed the index. I ensured they do not do that anymore, and now the error seems gone.
It remains to be seen whether there is any performance impact.
> Folding builders do not access index anymore

- test/nl/hannahsten/texifyidea/gutter/LatexGutterTest.kt
- test/nl/hannahsten/texifyidea/inspections/latex/codestyle/LatexFigureNotReferencedInspectionTest.kt
- test/nl/hannahsten/texifyidea/inspections/latex/codestyle/LatexTooLargeSectionInspectionTest.kt
- test/nl/hannahsten/texifyidea/inspections/latex/codestyle/LatexUsePackageInPackageInspectionTest.kt
- test/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexFileNotFoundInspectionTest.kt
- test/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexUnicodeInspectionTest.kt
- test/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexUnresolvedReferenceInspectionTest.kt
- test/nl/hannahsten/texifyidea/inspections/latex/probablebugs/packages/LatexMissingImportInspectionTest.kt
- test/nl/hannahsten/texifyidea/psi/LatexParserTest.kt
@fberlakovich Please check if this helps in fixing the `java.lang.AssertionError: File accessed outside allowed roots`.
At least when I check the function return value, it doesn't refer to my local `inputenc.sty` anymore in LatexGutterTest, which mimics what happens in GitHub Actions.
I have no clue why you got the error but I don't, so I can't say for sure if this is enough.
> Mock runCommand() in tests to avoid access to local LaTeX installation

- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexFileNotFoundInspection.kt
- src/nl/hannahsten/texifyidea/reference/CommandDefinitionReference.kt
- src/nl/hannahsten/texifyidea/util/Projects.kt
- test/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexFileNotFoundInspectionTest.kt
- test/nl/hannahsten/texifyidea/reference/CommandDefinitionReferenceTest.kt
Fix #2235 Index access on uninitialized project
Fix #2238 false positive in FileNotFoundInspection
Fix #2225 resolve to command definition inside definition when not the first parameter
> Project initialized check, FileNotFoundInspection and command definition reference inside definition

- src/nl/hannahsten/texifyidea/inspections/latex/typesetting/LatexEncloseWithLeftRightInspection.kt
- test/nl/hannahsten/texifyidea/inspections/latex/typesetting/LatexEncloseWithLeftRightInspectionTest.kt
Fix [TEX-149](https://texify-idea.myjetbrains.com/youtrack/issue/TEX-149)
* We use two descriptors for one `\left(...\right)` fix. This works fine as long as the user only applies one of those quick fixes, but not when they apply both (via the "apply all quick fixes" action). In that case the fix of each descriptor will be applied, which here means that each fix will be applied twice (and brackets and `\left`, `\right` commands will appear in strange numbers and places). Fixed this by keeping track of whether or not a fix has been applied already, and applying a fix by doing replacements in the psi tree instead of replacing text ranges.
```latex
\[
u_k = (s \cos(\frac{2k\pi}{5}), s \sin(\frac{2k\pi}{5}), t)
\]
```
Use the fix all intention to change all `(...)` pairs to …
> Apply each fix once instead of twice when using the fix all action

- src/nl/hannahsten/texifyidea/lang/commands/LatexCommand.kt
Fix #2335
Ctrl+Q on \usepackage will now show the urls for the package documentation.
> Fix urls not showing in documentation for packages

- src/nl/hannahsten/texifyidea/gutter/LatexElementColorProvider.kt
- src/nl/hannahsten/texifyidea/util/PsiCommands.kt
Fix #2305
* Avoid an SO by getting the color from the correct argument of the `\definecolorseries` command.
Does not take into account any other fancy color series stuff (see [TEX-150](https://texify-idea.myjetbrains.com/youtrack/issue/TEX-150)).
```latex
\usepackage{xcolor}
\definecolorseries{gfcolors}{hsb}{grad}[hsb]{.650,1,1}{.987,-.234,0}
```
Doesn't crash and does show the first color in the gutter icon.
> Fix stackoverflow when defining color series

- resources/META-INF/extensions/startup.xml
- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexFileNotFoundInspection.kt
- src/nl/hannahsten/texifyidea/startup/LatexPackageLocationCacheInitializer.kt
- src/nl/hannahsten/texifyidea/util/Packages.kt
- src/nl/hannahsten/texifyidea/util/files/LatexPackageLocationCache.kt
Fix #2307
Instead of caching lazily and executing system commands for every (partial) package name, we now fill the cache up front.
We cannot fill lazily in background because we might need the result immediately (resolving reference by user).
> Improve speed of caching mechanism for package location cache

- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexUnicodeInspection.kt
- src/nl/hannahsten/texifyidea/settings/sdk/MiktexWindowsSdk.kt
I don't know exactly when unicode support was enabled by default, but it was supposedly in 2018 so I've guessed a MiKTeX version.
> Also check MiKTeX version for unicode support

- src/nl/hannahsten/texifyidea/util/Strings.kt
- test/nl/hannahsten/texifyidea/inspections/latex/codestyle/LatexMissingLabelInspectionTest.kt
Fix #2359
* Normalize label string
```latex
\section{~Ação –função}
```
> Normalize string when generating label names

- resources/META-INF/extensions/editor/editor.xml
- src/nl/hannahsten/texifyidea/editor/typedhandlers/InlineMathBackspaceHandler.kt
- src/nl/hannahsten/texifyidea/editor/typedhandlers/LatexTypedHandler.kt
- src/nl/hannahsten/texifyidea/highlighting/LatexPairedBraceMatcher.kt
- test/nl/hannahsten/texifyidea/editor/typedhandlers/LatexTypedHandlerTest.kt
Fix #2322
* In verbatim, typing `$` will not insert a second `$` and also will not delete it - similar for `\[` and `\(`.
> Disable inline math completion in verbatim

- src/nl/hannahsten/texifyidea/run/makeindex/MakeindexCommandLineState.kt
- src/nl/hannahsten/texifyidea/run/makeindex/MakeindexRunConfiguration.kt
- src/nl/hannahsten/texifyidea/run/makeindex/MakeindexSettingsEditor.kt
Fix #2342
* Quick fix to have command line arguments in the stable version of the run configs
> Add command line arguments for makeindex run config

- src/nl/hannahsten/texifyidea/editor/typedhandlers/LatexEnterInEnumerationHandler.kt
- test/nl/hannahsten/texifyidea/editor/typedhandlers/LatexEnterInEnumerationHandlerTest.kt
Fix #2231
* Use live template to place caret in optional param of next \item, with as suggested text the previous item label.
```latex
\begin{description}
\item[Label A] A description of Label A
\end{description}
\end{document}
```
> Use live template for labels in itemize enter handler

- src/nl/hannahsten/texifyidea/inspections/grazie/LatexTextExtractor.kt
- test/nl/hannahsten/texifyidea/inspections/grazie/GrazieInspectionTest.kt
Fix #2314
* I don't know if I broke something else, but tests pass. At least the conversion from inclusive end to exclusive end is making slightly more sense now.
```latex
% Preamble
% Document
\subsubsection{Something}
The hardware requirements
\end{document}
```
> Fix off-by-one error in Grazie text extractor

- src/nl/hannahsten/texifyidea/completion/BibtexCompletionContributor.kt
Fix #2353 
* Add file completion for the bibsource field
afaik this field is not in any 'official' entry type, but it's a convention by dblp which I agree to adopt. 
```latex
@inproceedings{DBLP:conf/mdm/ValdesGO16,
author    = {Fabio Vald{\'{e}}s and
Ralf Hartmut G{\"{u}}ting and
Federico Ossi},
title     = {Efficient Trajectory Analysis for Several Time-Dependent Attributes:
{A} Case Study for Roe Deer},
booktitle = {{IEEE} 17th International Conference on Mobile Data Management, {MDM}
2016, Porto, Portugal, June 13-16, 2016},
bibsource = {main.pdf}
}
```
> Add file completion for bibsource field

- src/nl/hannahsten/texifyidea/inspections/latex/codematurity/LatexDiscouragedUseOfDefInspection.kt
- src/nl/hannahsten/texifyidea/structure/latex/BibitemPresentation.kt
- src/nl/hannahsten/texifyidea/util/Psi.kt
- test/nl/hannahsten/texifyidea/inspections/latex/codematurity/LatexDiscouragedUseOfDefInspectionTest.kt
Fix #2370
Fix #2376 \bibitem without parameters in structure view
Fix #2380 invalid psi element access
* Add support for quickfixing `\def \command {definition with braces}`
There are of course many pathological examples in which this is going to fail because we're not parsing this correctly, so this PR just fixes this one issue.
```latex
\def\a1
\def \indentpar {\hangindent=1cm \hangafter=0}
\setlength{\parskip}{0.5em}
```
> Support \def to \newcommand quickfix with braced definition

- gen/nl/hannahsten/texifyidea/parser/LatexParser.java
- gen/nl/hannahsten/texifyidea/psi/LatexCommands.java
- gen/nl/hannahsten/texifyidea/psi/LatexEnvironment.java
- gen/nl/hannahsten/texifyidea/psi/LatexKeyvalKey.java
- gen/nl/hannahsten/texifyidea/psi/LatexParameter.java
- gen/nl/hannahsten/texifyidea/psi/LatexParameterGroupText.java
- gen/nl/hannahsten/texifyidea/psi/impl/LatexCommandsImpl.java
- gen/nl/hannahsten/texifyidea/psi/impl/LatexEnvironmentImpl.java
- gen/nl/hannahsten/texifyidea/psi/impl/LatexKeyvalKeyImpl.java
- gen/nl/hannahsten/texifyidea/psi/impl/LatexMagicCommentImpl.java
- gen/nl/hannahsten/texifyidea/psi/impl/LatexParameterGroupTextImpl.java
- gen/nl/hannahsten/texifyidea/psi/impl/LatexParameterImpl.java
- src/nl/hannahsten/texifyidea/grammar/Latex.bnf
- src/nl/hannahsten/texifyidea/psi/LatexCommandsImplUtil.kt
- src/nl/hannahsten/texifyidea/psi/LatexPsiImplUtil.java
Fix #2445
* Restrict the possible values for keys in key/val pairs
The changes are based on the assumption that keys in key/val pairs are never references because now they are no longer `parameter_text`.
> Improve parser performance

- src/nl/hannahsten/texifyidea/formatting/LatexSpacingRules.kt
- src/nl/hannahsten/texifyidea/inspections/grazie/LatexTextExtractor.kt
- src/nl/hannahsten/texifyidea/lang/alias/AliasManager.kt
- test/nl/hannahsten/texifyidea/formatting/LatexFormattingTest.kt
This PR was tested on a 8000-line LaTeX file, the inspections were around 50x faster.
The second commit improves formatter performance (pressing enter)
> Improve performance of inspections and formatting

- build.gradle.kts
- src/nl/hannahsten/texifyidea/formatting/spacingrules/TableAlignRule.kt
- src/nl/hannahsten/texifyidea/index/file/LatexIndexableSetContributor.kt
- src/nl/hannahsten/texifyidea/index/stub/LatexCommandsStubElementType.kt
- src/nl/hannahsten/texifyidea/reference/LatexLabelReference.kt
- src/nl/hannahsten/texifyidea/util/Packages.kt
Fix #2433
* Exclude some more stub indexes from indexing package files, which greatly reduces index size and improves performance
This does not fix the root of the problem, which is that package file shouldn't be indexed at all.
> Exclude more stub indexes from indexing package files

- src/nl/hannahsten/texifyidea/index/file/LatexIndexableSetContributor.kt
- src/nl/hannahsten/texifyidea/settings/sdk/LatexSdkUtil.kt
Fix #2387
* For some reason, only dtx file source paths were attempted to be found when no SDKs are configured, now this also holds for sty file sources.
> Support non-IntelliJ IDEs also for package-file based indexes

- src/nl/hannahsten/texifyidea/lang/DefaultEnvironment.kt
- src/nl/hannahsten/texifyidea/lang/LatexPackage.kt
- src/nl/hannahsten/texifyidea/util/magic/EnvironmentMagic.kt
Similar to PR #2245
Add the `blockarray` and `block` environments provided by the  `blkarray` package.
Inspection was triggered suggesting to escape ampersands and underscores within `blockarray` and `block` contexts.
```latex
\begin{equation*}
\B{A} =
\begin{blockarray}{ccccc}
& 1 & 2 & & m \\
\begin{block}{c(cccc)}
1 & a_{1,1} & a_{1,2} & \cdots & a_{1,m} \\
2 & a_{2,1} & a_{2,2} & \cdots & a_{2,m} \\
& \vdots  & \vdots  & \ddots & \vdots \\
n & a_{n,1} & a_{n,2} & \cdots & a_{n,m} \\
\end{block}
\end{blockarray}
\end{equation*}
```
At least the inspection to replace `&` with `\&` should not be triggered.
I have 0 experience with this project and with Kotlin/Java in general and don't have the setup to build/test this fix. I tried to deduce which files/lines to add/edit from a similar PR …
> Add `blockarray` and `block` environments

- src/nl/hannahsten/texifyidea/formatting/BibtexSpacingRules.kt
Fix [TEX-155](https://texify-idea.myjetbrains.com/youtrack/issue/TEX-155)
* Add blank line
```latex
@book{knuth1990,
author = {Knuth, Donald E.},
title = {The {\TeX}book},
year = {1990},
isbn = {},
publisher = {Addison\,\textendash\,Wesley}
}@article{greenwade1993,
author = "George D. Greenwade",
title = "The {C}omprehensive {T}ex {A}rchive {N}etwork ({CTAN})",
year = "1993",
journal = "TUGBoat",
volume = "14",
number = "3",
pages = "342--351",
note = mytext
}
```
After formatting, a blank line is added.
> Add line break between bibtex entries

- build.gradle.kts
- src/nl/hannahsten/texifyidea/action/preview/EquationPreviewToolWindow.kt
- src/nl/hannahsten/texifyidea/reference/InputFileReference.kt
Fix #2518 whitespace around file name
Fix #2526 NPE EquationPreviewToolWindow
> Trim whitespace when resolving file name

- build.gradle.kts
- src/nl/hannahsten/texifyidea/index/file/LatexExternalPackageInclusionCache.kt
- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexInclusionLoopInspection.kt
- src/nl/hannahsten/texifyidea/util/files/ImportPackage.kt
Fix #2523
Fix #2537 Dumb mode in LatexPackageLocationCache
* LatexInclusionLoopInspection was using this expensive method for the import package, I just removed that part as that's not worth it
* Improve the check if the import package is used: move it before the expensive calls
Tested on project with 160 files and 50k lines of tex: inspections take one minute the first time (building fileset), then only two seconds afterwards.
> Improve inspection performance when import package is used

- src/nl/hannahsten/texifyidea/inspections/latex/codestyle/LatexMightBreakTexifyInspection.kt
- src/nl/hannahsten/texifyidea/util/Psi.kt
- src/nl/hannahsten/texifyidea/util/PsiCommands.kt
- test/nl/hannahsten/texifyidea/inspections/latex/codestyle/LatexMightBreakTexifyInspectionTest.kt
Fix #2542
* The code for finding the command after a \def wasn't very up to date, this should be better now.
Also the CommandAlreadyDefinedInspection used the same code.
* Clearer inspection message
See tests and issue
> Fix inspection false positives related to \def redefinitions

- src/nl/hannahsten/texifyidea/lang/commands/LatexGlossariesCommand.kt
- src/nl/hannahsten/texifyidea/lang/commands/LatexRegularCommand.kt
- test/nl/hannahsten/texifyidea/completion/LatexGlossaryCompletionTest.kt
- test/resources/completion/glossary/LoadExternalGlossary.tex
- test/resources/completion/glossary/glossar.tex
Fix #2563 
* Add support for the \loadglsentries command
See the included testcase
> add support for glossary entries loaded via loadglsentries command

- build.gradle.kts
- src/nl/hannahsten/texifyidea/index/file/LatexIndexableSetContributor.kt
- src/nl/hannahsten/texifyidea/settings/sdk/MiktexWindowsSdk.kt
Fix #2190 but now also for MiKTeX on Windows.
* Add style file root
https://plugins.jetbrains.com/files/9473/206710/TeXiFy-IDEA-0.7.21-alpha.3.zip
It might be necessary to add the SDK.
> Index style files also for miktex on windows

- src/nl/hannahsten/texifyidea/action/library/mendeley/AddMendeleyAction.kt
- src/nl/hannahsten/texifyidea/remotelibraries/mendeley/MendeleyAuthenticator.kt
- src/nl/hannahsten/texifyidea/remotelibraries/mendeley/MendeleyCredentials.kt
Fix #2595
Fix #2599
* Our Mendeley server (stupidly) used port 8080. When something was already running on that port the authentication server could not start and thus users could not login. I would have preferred to let Jetty automatically select a free port ([this is possible](https://youtrack.jetbrains.com/issue/KTOR-686)), but Mendeley requires us to configure a redirect url which must include the port when running on localhost.
* Added a warning when trying to OK the Mendeley login dialog while you are not logged in yet, see https://github.com/Hannah-Sten/TeXiFy-IDEA/issues/2599#issuecomment-1214429173
* Try to add Mendeley while you don't have something running on port 59473 :)
* "Accidentally" hit enter. It should be a bit less annoying than it was.
> Change the port of the server for Mendeley authentication

- src/nl/hannahsten/texifyidea/run/linuxpdfviewer/zathura/ZathuraConversation.kt
Fix #2622 
* Zathura now uses the `%{input}` argument instead of always inverse searching to the file that was compiled from
See #2622 for a detailed description
> Fix #2622: Zathura inverse search goes to correct file

- src/nl/hannahsten/texifyidea/editor/typedhandlers/LatexEnterHandler.kt
- src/nl/hannahsten/texifyidea/formatting/LatexBlock.kt
- test/nl/hannahsten/texifyidea/formatting/LatexFormattingTest.kt
Fix #2617
* Do not indent in the document environment on enter when that setting is disabled
```latex
\begin{test}
Indent the next line<caret>
\end{test}
Don't indent the next line<caret>
\end{document}
```
> Add 'indent document environment' setting to enter handler

- src/nl/hannahsten/texifyidea/settings/sdk/MiktexWindowsSdk.kt
> Fix home path check for MiKTeX on Windows for non-English system language

- gen/nl/hannahsten/texifyidea/parser/LatexParser.java
- gen/nl/hannahsten/texifyidea/psi/LatexCommands.java
- gen/nl/hannahsten/texifyidea/psi/LatexEnvironment.java
- gen/nl/hannahsten/texifyidea/psi/LatexKeyvalKey.java
- gen/nl/hannahsten/texifyidea/psi/LatexParameter.java
- gen/nl/hannahsten/texifyidea/psi/LatexParameterGroupText.java
- gen/nl/hannahsten/texifyidea/psi/LatexRequiredParam.java
- gen/nl/hannahsten/texifyidea/psi/LatexStrictKeyvalPair.java
- gen/nl/hannahsten/texifyidea/psi/LatexTypes.java
- gen/nl/hannahsten/texifyidea/psi/LatexVisitor.java
- gen/nl/hannahsten/texifyidea/psi/impl/LatexCommandsImpl.java
- gen/nl/hannahsten/texifyidea/psi/impl/LatexEnvironmentImpl.java
- gen/nl/hannahsten/texifyidea/psi/impl/LatexKeyvalKeyImpl.java
- gen/nl/hannahsten/texifyidea/psi/impl/LatexMagicCommentImpl.java
- gen/nl/hannahsten/texifyidea/psi/impl/LatexParameterGroupTextImpl.java
- gen/nl/hannahsten/texifyidea/psi/impl/LatexParameterImpl.java
- gen/nl/hannahsten/texifyidea/psi/impl/LatexRequiredParamImpl.java
- gen/nl/hannahsten/texifyidea/psi/impl/LatexStrictKeyvalPairImpl.java
- src/nl/hannahsten/texifyidea/grammar/Latex.bnf
- test/nl/hannahsten/texifyidea/inspections/grazie/GrazieInspectionTest.kt
Fix #2660
* `( ) { }` are now part of normal text, so we don't exclude them from the Grazie inspections.
```latex
a (in this case) . aa
```
In the old case, removing the first `a`, or a character within the parentheses, or one of the last `a`'s would trigger Grazie's unpaired symbol inspection.
> Fix #2660: include parens in normal_text

- src/nl/hannahsten/texifyidea/inspections/LatexSpellcheckingStrategy.kt
- test/nl/hannahsten/texifyidea/inspections/latex/LatexSpellCheckingStrategyTest.kt
Fix #2578
* Do not spellcheck command parameters unless they are known to contain text (fix logic and parameter retrieval)
```latex
\usepackage{aligned-overset} % no typo
\section{aligned-overset}\label{sec:aligned-overset} % typo
\citep{citekey}
Aligned overset.
```
> Fix spellcheck in command parameters

- src/nl/hannahsten/texifyidea/util/labels/LabelExtraction.kt
Fix #2704
I couldn't reproduce the NPE, but it had a logical fix: return `""` when `null` like in other places in the same method.
> Fix #2704 NPE

- src/nl/hannahsten/texifyidea/editor/typedhandlers/LatexTypedHandler.kt
Fix #2685
* IntelliJ uses scopes to maintain when tab can exit something, so all we have to do is create a scope for inline math.
Note: scopes behave like live templates, if you go out of the scope it disappears and using tab to exit won't work anymore.
Type `$x^3` then use tab to exit.
> Exit inline math with tab

- gen/nl/hannahsten/texifyidea/parser/LatexParser.java
- gen/nl/hannahsten/texifyidea/psi/LatexKeyvalContent.java
- gen/nl/hannahsten/texifyidea/psi/impl/LatexKeyvalContentImpl.java
- src/nl/hannahsten/texifyidea/grammar/Latex.bnf
- src/nl/hannahsten/texifyidea/highlighting/TextidoteAnnotator.kt
- test/nl/hannahsten/texifyidea/formatting/LatexFormattingTest.kt
Fix #2684
This is just a quick fix, we should probably restructure some things in the parser to avoid more of these missing token problems.
> Quick workaround for missing parser tokens in keyval_value

- gradle.properties
- src/nl/hannahsten/texifyidea/action/InsertEditorAction.kt
- src/nl/hannahsten/texifyidea/lang/magic/MagicComments.kt
- src/nl/hannahsten/texifyidea/util/Psi.kt
- test/nl/hannahsten/texifyidea/lang/magic/MagicCommentPsiTest.kt
Fix [TEX-158](https://texify-idea.myjetbrains.com/youtrack/issue/TEX-158)
Fix [TEX-148](https://texify-idea.myjetbrains.com/youtrack/issue/TEX-148)
* Due to (I think) a change in parser structure the next magic comment is no longer a sibling
```latex
%! suppress = NonBreakingSpace
%! suppress = UnresolvedReference
I \ref{nolabel}
```
> Fix ignored file-level magic comments

- src/nl/hannahsten/texifyidea/run/sumatra/SumatraConversation.kt
Fix #2730 
Modified ```isSumatraInstalled()``` to check correctly if Sumatra is in PATH during initialization phase.
Added checks when opening a file in SumatraPDF ```openFile()``` to remove the Windows error popup when custom path to SumatraPDF isn't valid.
Open TeXiFy with only global PATH set to Sumatra (no registry keys)
Under LaTeX configuration, under "PDF viewer", "Sumatra" should appear.
Under Tools/LaTeX, option to "Configure Inverse Search" should appear.
Set no PATH and no registry keys to Sumatra.
Set custom path to Sumatra in Run Configuration to real Sumatra install.
Run LaTeX project, Sumatra should open.
Set custom path to Sumatra in Run Configuration to a real folder that doesn't contain Sumatra.
Run LaTeX project, Sumatra shouldn't open and no error popup should appear. …
> Fixed issues with PATH and Sumatra

- src/nl/hannahsten/texifyidea/inspections/latex/codestyle/LatexTooLargeSectionInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexFileNotFoundInspection.kt
- src/nl/hannahsten/texifyidea/intentions/LatexMoveSectionToFileIntention.kt
- src/nl/hannahsten/texifyidea/intentions/LatexMoveSelectionToFileIntention.kt
- src/nl/hannahsten/texifyidea/util/files/Files.kt
- test/nl/hannahsten/texifyidea/intentions/LatexMoveSectionToFileIntentionTest.kt
Fix #2724 
* Fixes bug outlined in #2724 
* Changed the semantics behind `nl.hannahsten.texifyidea.inspections.latex.codestyle.LatexTooLargeSectionInspection#findNextSection(LatexCommands)` to require a section/chapter. I don't think it is the *best*, but I am unsure what else it is used for. If the function is only used to find the next section, from a section, then there will be no issue.
* Note there is no guard to verify that the passed command is actually a valid section. I did this because I wanted to steer away from backsearching for one, since that requires more intimate knowledge of the usage than a basic "Find Usages" will provide.
```latex
\chapter{Foo}
\section{SubFoo}
Bar
\subsubsection{SubbFoo}
Barr …
```
> Fix "Move Section Contents to Seperate File" intention

- src/nl/hannahsten/texifyidea/psi/LatexCommandsImplUtil.kt
- src/nl/hannahsten/texifyidea/refactoring/LatexNamesValidator.kt
Minimal fix to #2752 
* Help prevent the user from renaming the command to an illegal or incomplete command name
```latex
\newcommand{\mycommand}{my command}
```
> Guarantee slash in rename

- src/nl/hannahsten/texifyidea/highlighting/LatexColorSettingsPage.kt
Fix #2758 
* Reorder the examples in the color menu to agree with the order of the settings
If this is viewed as not being necessary, important, or that the ordering of the demo (presumably by importance/use frequency) is better as is, i will not be sad to see the request rejected. It is simply here because the fix was easy.
> Reorder demo text styles

- src/nl/hannahsten/texifyidea/refactoring/inlinefile/LatexInlineFileHandler.kt
I didn't make an issue, but after my #2741 I didnt realize that IJ would *offer* to inline everything, but ignore the request on almost everything. This will prefent `inline` from showing up on top of nearly anything (notice the old else branch). Kind of embarrassing that I missed it, but now it will be fixed.
> Stop offering to inline when impossible

- src/nl/hannahsten/texifyidea/highlighting/LatexAnnotator.kt
Fix #2760 
* Highlighting now works (sort of). Cannot nest highlights
Make sure to have a different-than-standard style for the following
```latex
\textbf{BOLD}
\textit{italics}
\underline{underline}
```
beae610744f53bc8c7138eb971b0a073d8ee63a8 has the minimal oneline solution, the following commits make it more robust ?
> Fix syntax highlighting for bold & other text formatting commands

- src/nl/hannahsten/texifyidea/run/linuxpdfviewer/ViewerForwardSearch.kt
Fix #2710 
* Use the main file as default file for forward search in case there is no file open in the editor. Tested with Zathura, Okular, Evince, and the Built-in PDF Viewer on linux.
Run a run configuration when no tex file is open in the editor.
> Fix #2710: open pdf viewer when no tex file is open in editor

- src/nl/hannahsten/texifyidea/util/magic/CommandMagic.kt
- test/nl/hannahsten/texifyidea/reference/InputFileReferenceTest.kt
Fix #2745 
* Added `input` to the list of commands that have an illegal extension.
I also stumbled across a really annoying bug, wherein if the extension was implied *before* creating a new file, then you can't undo the process, but if an necessary extension was present, then undoing is possible. 
I have no idea why.
```latex
\input{otherfile.tex} % will drop the tex
```
```latex
\input{otherfile}
```
> Remove extension on input command

- src/nl/hannahsten/texifyidea/inspections/bibtex/BibtexMissingBibliographystyleInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/codestyle/LatexMissingLabelInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/typesetting/LatexIncorrectSectionNestingInspection.kt
- src/nl/hannahsten/texifyidea/run/linuxpdfviewer/ViewerForwardSearch.kt
- src/nl/hannahsten/texifyidea/run/sumatra/SumatraForwardSearchListener.kt
- src/nl/hannahsten/texifyidea/util/files/PsiFile.kt
- src/nl/hannahsten/texifyidea/util/files/VirtualFile.kt
* Fixes a bug in `PsiFile#openedEditor()`. This opened the editor currently selected in the IDE, which often wasn't the editor of the file we were requesting. 
* Fixed the forward search code that relied on this method working incorrectly.
* This method is also used in some other places where it looks like we assume that it does what the comments claim it does (and what it didn't always do before). I don't expect any of this to malfunction now, but the tests don't cover it because they always have only one editor (or there are no tests at all), so no guarantees. I suppose that if there's some case where it doesn't work anymore, it's rare, and it might be another four years before someone stumbles upon it.
> File editor forward search

- resources/META-INF/extensions/editor/editor.xml
- src/nl/hannahsten/texifyidea/editor/folding/LatexFootnoteFoldingBuilder.kt
- src/nl/hannahsten/texifyidea/util/magic/CommandMagic.kt
Fix #2782 
* Add a footnotes folder.
Seeing how there is not currently a registry of "footnote-like" commands, it is hardcoded for \footnote only
```latex
\footnote{this is a footnote}
```
Note to collapse anything in IDEA can be done with a shortcut, or from the right click menu
> Fold footnotes

- src/nl/hannahsten/texifyidea/action/sumatra/ConfigureInverseSearchAction.kt
- src/nl/hannahsten/texifyidea/run/latex/LatexCommandLineState.kt
- src/nl/hannahsten/texifyidea/run/latex/LatexRunConfiguration.kt
- src/nl/hannahsten/texifyidea/run/latex/ui/LatexSettingsEditor.kt
- src/nl/hannahsten/texifyidea/run/linuxpdfviewer/InternalPdfViewer.kt
- src/nl/hannahsten/texifyidea/run/sumatra/SumatraAvailabilityChecker.kt
- src/nl/hannahsten/texifyidea/run/sumatra/SumatraConversation.kt
- src/nl/hannahsten/texifyidea/run/sumatra/SumatraForwardSearchListener.kt
- src/nl/hannahsten/texifyidea/util/SystemEnvironment.kt
Fix #2737
Added full support when inputting a custom Sumatra path, so that it appears in PDF Viewer ComboBox, and making it work with Forward Search and the Configure Inverse Search.
1. Changed isSumatraAvailable in SumatraConversation to a singleton object that checks if Sumatra is available.
2. Added an InputVerifier on the TextField of Custom Sumatra Path that checks the validity of the path, and updates the value of isSumatraAvailable and updates the items in the PDF Viewer ComboBox.
3. Changed the availability in the InternalPdfViewer to a function so that it can be changed during execution.
4. Removed the lines checking if the Sumatra Custom Path was null in addOpenViewerListener so that the user can select which PDF Viewer to open, even if a Sumatra Custom Path is present.
5. Added …
> Full compatibility for Sumatra custom path

- build.gradle.kts
- resources/intentionDescriptions/LatexLanguageInjectionIntention/after.tex.template
- resources/intentionDescriptions/LatexLanguageInjectionIntention/before.tex.template
- src/nl/hannahsten/texifyidea/intentions/LatexAddLabelIntention.kt
- src/nl/hannahsten/texifyidea/intentions/LatexAddLabelToCommandIntention.kt
- src/nl/hannahsten/texifyidea/intentions/LatexAddLabelToEnvironmentIntention.kt
- src/nl/hannahsten/texifyidea/intentions/LatexLanguageInjectionIntention.kt
- src/nl/hannahsten/texifyidea/util/files/PsiFile.kt
- test/nl/hannahsten/texifyidea/intentions/LatexAddLabelIntentionTest.kt
Fix #2742
* Some previews were not working, fixed with overriding default behaviour
Ctrl+Q on the intention in the popup should bring up a preview
`\section{blub}`
> Fix some intention previews

- CHANGELOG.md
- build.gradle.kts
- gradle.properties
- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexUnicodeInspection.kt
- src/nl/hannahsten/texifyidea/util/LatexmkRcFileFinder.kt
- src/nl/hannahsten/texifyidea/util/Projects.kt
Fix #2839 well not really, but now at least we will see the actual error
Also: Fix #2836
Fix #2800
* Something weird in the IntelliJ SDK: in this case the error message will be completely hidden if you use a lazy val. Couldn't reproduce it in the intellij plugin template, maybe it has to do with the calling location.
> Don't use a lazy val with a non-trivial initializer in an object

- CHANGELOG.md
- resources/META-INF/extensions/editor/editor.xml
- src/nl/hannahsten/texifyidea/editor/LatexLineWrapStrategy.kt
- test/nl/hannahsten/texifyidea/formatting/LatexFormattingTest.kt
- test/nl/hannahsten/texifyidea/formatting/LatexLineWrapStrategyTest.kt
Fix #2725
* Add line wrapping strategy to wrap after urls in \url-like commands and comments
Set line width to 30 and reformat:
```latex
\section{This includes permissions.}
\href{https://the-very-very-long.url}{This includes} permissions and basements.
% https://the-very-very-long-long.url with long text
% and the https://the-very-very-long.url
It appears to rely more inspiring during
% On average 59 precisely inbound
Petra indicates clears to relate the selection's systems.
```
> Don't wrap urls

- src/nl/hannahsten/texifyidea/highlighting/LatexPairedBraceMatcher.kt
- src/nl/hannahsten/texifyidea/run/latex/LatexRunConfiguration.kt
- src/nl/hannahsten/texifyidea/structure/latex/LatexChapterPresentation.kt
- src/nl/hannahsten/texifyidea/structure/latex/LatexPresentationFactory.kt
- test/nl/hannahsten/texifyidea/editor/typedhandlers/LatexTypedHandlerTest.kt
Fix #2788
Fix #2843 NPE 
Fix #2871 IOOB in structure view
* Mistakenly introduced in #2362
> Revert accidental removal of inline math paired delimiter

- CHANGELOG.md
- src/nl/hannahsten/texifyidea/ui/CreateFileDialog.kt
- src/nl/hannahsten/texifyidea/util/Strings.kt
> Reformat suggested filename before showing it to the user, instead of afterwards

- src/nl/hannahsten/texifyidea/lang/LatexPackage.kt
- src/nl/hannahsten/texifyidea/util/magic/PackageMagic.kt
Fixes #2925.
In the thread of #2925 I said that pointing `newtx` to `amssymb` and `stmaryrd` did not resolve the issue when using `acmart`, but that's because `acmart` loads `newtxmath`, not `newtx`. Which makes sense, because it's specifically `newtxmath` that provides the commands we're interested in for this issue.
* Use magic to show that `newtxmath` is equivalent to `amssymb` and `stmaryrd`
Each of the following snippets should show 0 warnings and 0 errors in the IDE.
* _Baseline: Already worked before this PR_
```latex
\usepackage{amssymb}
\usepackage{stmaryrd}
$\llbracket$
$\nexists$
\end{document}
```
* _Direct: Check if newtxmath is considered the same as amssymb and stmaryrd_
```latex
\usepackage{newtxmath} …
```
> Provide resolution magic for newtxmath

- src/nl/hannahsten/texifyidea/util/files/ImportPackage.kt
…inputs the file in a different file set
Fix #2750 
* If you have another command in the project inputting a file with the same name as your main file with the \subimport, the code would get confused and just skip it. Now we're still confused but we just try all paths and the first one that resolves wins.
main.tex
```latex
\usepackage{import}
\input{preamble}
\subimport{chapters/}{chapter-one.tex}
\end{document}
```
preamble.tex
```
\usepackage{hyperref}
```
chapters/chapter-one.tex
```
\url{blub}
\input{included.tex}
```
chapters/included.tex
> Fix bug when resolving \subimport

- gen/nl/hannahsten/texifyidea/grammar/LatexLexer.java
- src/nl/hannahsten/texifyidea/grammar/LatexLexer.flex
- src/nl/hannahsten/texifyidea/intentions/LatexInsertFormatterCommentsIntention.kt
- src/nl/hannahsten/texifyidea/psi/LatexLanguageInjector.kt
- src/nl/hannahsten/texifyidea/psi/LatexParserUtil.kt
- src/nl/hannahsten/texifyidea/util/magic/EnvironmentMagic.kt
Fix #2847
* Environments defined with \newminted will end with `code` so are easy to auto-detect for the lexer, and inject language.
```latex
\usepackage{minted}
\newminted{kotlin}{linenos}
\begin{kotlincode}
val blub = 3
fun getBlub() {
return 3 // a comment {
}
\end{kotlincode}
\end{document}
```
> Add \newminted code blocks as verbatim environments

- resources/META-INF/extensions/editor/editor.xml
- src/nl/hannahsten/texifyidea/editor/folding/LatexCodeFoldingOptionsProvider.kt
- src/nl/hannahsten/texifyidea/editor/folding/LatexCodeFoldingSettings.kt
- src/nl/hannahsten/texifyidea/editor/folding/LatexImportFoldingBuilder.kt
Fix #2854
* Add setting to configure default folding of imports. I used Editor > General > Code Folding
Disable setting, open a file you haven't opened before after last restart
> Add setting to configure default folding of imports

- resources/META-INF/extensions/inspections/latex/probablebugs/probablebugs.xml
- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexBibinputsRelativePathInspection.kt
Fix #2885
* I cannot reproduce this problem anymore, maybe it was a bug in bibtex that has been fixed?
https://github.com/PHPirates/bibtex-mwe/tree/2885
> Disable LatexBibinputsRelativePathInspection

- CHANGELOG.md
- build.gradle.kts
- gradle.properties
- src/nl/hannahsten/texifyidea/run/FileCleanupListener.kt
- src/nl/hannahsten/texifyidea/run/latex/LatexCommandLineState.kt
- src/nl/hannahsten/texifyidea/run/latex/LatexOutputPath.kt
Fix #2968
* Instead of only creating empty output directories for directories in the file set, to improve performance we now create all subdirectories of the source root. 
* Bonus: after compilation, we delete any unnecessary empty directories
Use pdflatex on TeX Live
> Avoid expensive file set checks in run configuration process

- CHANGELOG.md
- resources/META-INF/extensions/editor/editor.xml
- src/nl/hannahsten/texifyidea/editor/folding/LatexCommentFoldingBuilder.kt
- src/nl/hannahsten/texifyidea/highlighting/LatexAnnotator.kt
- test/nl/hannahsten/texifyidea/editor/LatexFoldingTest.kt
- test/nl/hannahsten/texifyidea/psi/LatexParserTest.kt
- test/resources/editor/folding/comments.tex
Fix #2965 
Fix #2963 
* Added a folder for comments
This works by pulling all of the comments and all of the whitespaces. 
Then, it fuses adjacent whitespace ranges (not sure if required), then it finds each comment and attempts to find a whitespace that fully connects the comment block to another comment block. 
If so, it will increment the fold range to include the separating whitespace and the following comment and continue until there is not a continuous whitespace or no more comments.
```latex
% This is a
% block of comment
```
use ctrl + - to collapse the block (windows keybind, may be different for others)
> Fold Comments Fix

- gradle.properties
Fix #2992 
The ProjectActivity class, which replaced StartupActivity deprecated in 231, is apparently not present in IDEA 223.
The inspection that usually warns for this, didn't do its work this time.
> Update since version to 231

- CHANGELOG.md
- gradle/wrapper/gradle-wrapper.properties
- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexUnicodeInspection.kt
Fix #3008 
* Explicitly generate the preview of the fix, because the `applyFix` uses `showErrorHint` which crashes when called from the preview editor but by default `applyFix` is used to generate the preview.
```latex
$3x^2 Ξ A$
$¨ A$
```
Use <kbd>Alt</kbd> + <kbd>Enter</kbd> on the inspection. This used to give an exception while loading the preview.
> Generate preview for unicode inspection, fixes #3008

- CHANGELOG.md
- resources/nl/hannahsten/texifyidea/ipsum/texify.txt
- src/nl/hannahsten/texifyidea/action/sumatra/ConfigureInverseSearchAction.kt
- src/nl/hannahsten/texifyidea/run/latex/LatexCommandLineState.kt
- src/nl/hannahsten/texifyidea/run/linuxpdfviewer/InternalPdfViewer.kt
- src/nl/hannahsten/texifyidea/run/sumatra/SumatraAvailabilityChecker.kt
- src/nl/hannahsten/texifyidea/run/sumatra/SumatraConversation.kt
- src/nl/hannahsten/texifyidea/run/sumatra/SumatraForwardSearchListener.kt
* Until now, we only detect installs "for all users" of Sumatra. Now installs "for this user only" will also be detected by guessing the installation path. Sumatra will be opened after compilation, but forward/inverse search is not supported.
I cannot test it right now, so good luck to Windows users.
> Detect and open user-installed SumatraPDF

- resources/META-INF/extensions/files-and-project.xml
- src/nl/hannahsten/texifyidea/action/analysis/WordCountAction.kt
- src/nl/hannahsten/texifyidea/algorithm/BFS.kt
- src/nl/hannahsten/texifyidea/completion/LatexXColorProvider.kt
- src/nl/hannahsten/texifyidea/editor/postfix/LatexPostFixTemplateProvider.kt
- src/nl/hannahsten/texifyidea/editor/postfix/LatexPostfixTemplateFromPackageProvider.kt
- src/nl/hannahsten/texifyidea/gutter/LatexElementColorProvider.kt
- src/nl/hannahsten/texifyidea/index/BibtexEntryIndex.kt
- src/nl/hannahsten/texifyidea/index/BibtexEntryIndexKey.java
- src/nl/hannahsten/texifyidea/index/stub/BibtexEntryStubElementType.kt
- src/nl/hannahsten/texifyidea/inspections/bibtex/BibtexDuplicateIdInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexEscapeAmpersandInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexEscapeUnderscoreInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexFileNotFoundInspection.kt
- src/nl/hannahsten/texifyidea/lang/SimpleBibtexEntryField.kt
- src/nl/hannahsten/texifyidea/lang/magic/CustomMagicKey.kt
- src/nl/hannahsten/texifyidea/lang/magic/MagicComment.kt
- src/nl/hannahsten/texifyidea/modules/LatexModuleType.kt
- src/nl/hannahsten/texifyidea/psi/BibtexIdUtil.kt
- src/nl/hannahsten/texifyidea/reference/BibtexIdReference.kt
- src/nl/hannahsten/texifyidea/reference/InputFileReference.kt
- src/nl/hannahsten/texifyidea/run/latex/LatexRunConfiguration.kt
- src/nl/hannahsten/texifyidea/run/pdfviewer/PdfViewer.kt
- src/nl/hannahsten/texifyidea/settings/sdk/LatexSdkUtil.kt
- src/nl/hannahsten/texifyidea/util/Container.kt
- src/nl/hannahsten/texifyidea/util/Numbers.kt
- src/nl/hannahsten/texifyidea/util/Projects.kt
- src/nl/hannahsten/texifyidea/util/files/FileSet.kt
- src/nl/hannahsten/texifyidea/util/labels/BibtexLabels.kt
- src/nl/hannahsten/texifyidea/util/labels/ProjectLabels.kt
* Deregister the LaTeX Module Type, as module types are deprecated. The ModuleBuilder still exists, so you can still create a LaTeX module, except that at the end it's not going to be a LaTeX module but a generic one.
* Do not use PsiReference in field of quickfix
> Various code improvements

- CHANGELOG.md
- src/nl/hannahsten/texifyidea/run/latex/LatexRunConfiguration.kt
Fix #2975 
* Check for availability of the selected/stored pdf viewer when reading the run configuration. For example, when running a (linux) run configuration that used Evince on Windows we would happily try to run Evince even though it obviously isn't available on Windows.
> Reset pdf viewer to default when the saved pdf viewer is not available.

- src/nl/hannahsten/texifyidea/action/ForwardSearchAction.kt
Fix #3066
- Added check in `ForwardSearchAction#actionPerformed` to ensure `fileType` is `LatexFileType`
- Added condition in `ForwardSearchAction#update` to disable and hide action unless `fileType` is `LatexFileType`
- Create an arbitrary LaTeX file and an arbitrary non-LaTeX file
- Compile the LaTeX file, having the built-in PDF viewer enabled
- Verify that the `Forward Search` action can be triggered from the LaTeX file (either with a bound shortcut or directly through `Search Everywhere/Actions`), and it works properly
- Verify that the `Forward Search` action cannot be triggered (in any of the two ways) from the non-LaTeX file
<details><summary>Any files will do</summary>
> `test.tex`
```latex
test
\newpage
test
\end{document}
```
> `test.kt` …
> Disable "Forward Search" action in non-LaTeX files

- CHANGELOG.md
- gradle.properties
- src/nl/hannahsten/texifyidea/run/LatexProjectTaskRunner.kt
Fix #3079
* The previous PR accidentally removed the check instead of replacing it by the proper check
> Fix an issue with the canRun check in the LaTeX Project Task Runner

- src/nl/hannahsten/texifyidea/highlighting/TextidoteAnnotator.kt
Fix #3086, fix #3089 
* Check if range of annotation is within document range (#3086)
* Add null-check for containing directory (#3089)
> Fix some small exceptions in textidote implementation

- .gitignore
- src/nl/hannahsten/texifyidea/inspections/grazie/LatexTextExtractor.kt
- test/nl/hannahsten/texifyidea/inspections/grazie/GrazieInspectionTest.kt
- test/resources/inspections/grazie/MultilineCheckGrammar.tex
Fix #2931 issue with sentence ending with } 
Fix #2972 whitespace/newlines after a command between sentences
Fix #3021 or at least could not reproduce
Fix an issue with Grazie not being able to handle text starting with a newline
Add text parameters of commands to grammar checked text
Improve my knowledge of German
> Grazie fixes

- CHANGELOG.md
- build.gradle.kts
- gradle.properties
- src/nl/hannahsten/texifyidea/TeXception.kt
- src/nl/hannahsten/texifyidea/documentation/LatexDocumentationProvider.kt
This PR doesn't fix anything (yet), but at least the command now should time out after three seconds instead of blocking the UI indefinitely.
Regarding debugging any issues, it may also help to go to Help > Diagnostic Tools > Debug Log Settings and add `#nl.hannahsten.texifyidea.util.Log`, so that you can see in idea.log exactly which commands TeXiFy runs in the background.
Note that the documentation provider is already triggered when hovering over a psi element (though for me, it doesn't block the UI while running).
Tested with MiKTeX, not sure if it still works for TeX Live.
https://plugins.jetbrains.com/plugin/download?rel=true&updateId=350496
> Refactor command execution in documentation provider

- CHANGELOG.md
- build.gradle.kts
- gradle.properties
- src/nl/hannahsten/texifyidea/highlighting/LatexAnnotator.kt
- src/nl/hannahsten/texifyidea/index/LatexIndexUtil.kt
- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexFileNotFoundInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/packages/LatexMissingImportInspection.kt
- src/nl/hannahsten/texifyidea/psi/impl/LatexCommandsImplMixin.kt
- src/nl/hannahsten/texifyidea/util/parser/LatexCommandsImplMixinUtil.kt
* Fix some performance bugs introduced in recent versions. The root issue remains, however. Currently inspecting a 7000 line file takes about 20 seconds.
https://plugins.jetbrains.com/plugin/download?rel=true&updateId=357446
> Inspection performance

- src/nl/hannahsten/texifyidea/completion/pathcompletion/LatexPathProviderBase.kt
- src/nl/hannahsten/texifyidea/lang/commands/LatexGenericRegularCommand.kt
- src/nl/hannahsten/texifyidea/lang/commands/RequiredFileArgument.kt
- src/nl/hannahsten/texifyidea/lang/commands/RequiredPicturePathArgument.kt
- src/nl/hannahsten/texifyidea/reference/InputFileReference.kt
- src/nl/hannahsten/texifyidea/run/latex/logtab/LatexOutputListener.kt
- src/nl/hannahsten/texifyidea/util/files/PsiFile.kt
- src/nl/hannahsten/texifyidea/util/files/VirtualFile.kt
- src/nl/hannahsten/texifyidea/util/magic/FileMagic.kt
- src/nl/hannahsten/texifyidea/util/parser/LatexCommandsImplMixinUtil.kt
Fix #3142
Added `jpeg`, and allow `JPG`, `JPg` and such to be valid.
Why though, does https://github.com/Hannah-Sten/TeXiFy-IDEA/blob/cea8254aabefba24a4054d4e42af162f522a3390/src/nl/hannahsten/texifyidea/lang/commands/RequiredFileArgument.kt#L72-L78 have **zero** usages?
I have no idea how to use the already implemented commands, so i did some jank in order to get it to work, please fix
https://github.com/jojo2357/TeXiFy-IDEA/blob/a15853ff8736c5b434546edb677cbe8c50affacf/src/nl/hannahsten/texifyidea/reference/InputFileReference.kt#L169
> Includegraphics resiliency and file extension case de-sensitivity

- src/nl/hannahsten/texifyidea/reference/InputFileReference.kt
- src/nl/hannahsten/texifyidea/util/LatexmkRcFileFinder.kt
Fix https://github.com/Hannah-Sten/TeXiFy-IDEA/issues/3038#issuecomment-1627733061 probably
Fix #3038 by using kpsewhich to read TEXINPUTS directly (instead of just from run config)
> Use TEXINPUTS properly (direct and via .latexmkrc)

- gradle.properties
- src/nl/hannahsten/texifyidea/util/files/ImportPackage.kt
Fix #3156
* When there is a file inclusion loop (or an apparent one) the loop could repeatedly add the same commands as prefix
Didn't reproduce
> Fix infinite loop in resolving imports

- CHANGELOG.md
- build.gradle.kts
- gradle.properties
- src/nl/hannahsten/texifyidea/TexifyIcons.kt
- src/nl/hannahsten/texifyidea/completion/pathcompletion/LatexPathProviderBase.kt
- src/nl/hannahsten/texifyidea/gutter/LatexNavigationGutter.kt
- src/nl/hannahsten/texifyidea/ui/TeXiFyProjectViewNodeDecorator.kt
Fix #3229
* Don't use the default icon if the extension is not known
> Don't overwrite non-LaTeX icons

- src/nl/hannahsten/texifyidea/refactoring/inlinecommand/LatexInlineCommandDescriptor.kt
- src/nl/hannahsten/texifyidea/refactoring/inlinecommand/LatexInlineCommandDialog.kt
- src/nl/hannahsten/texifyidea/refactoring/inlinecommand/LatexInlineDialog.kt
- src/nl/hannahsten/texifyidea/refactoring/inlinefile/LatexInlineFileDescriptor.kt
- src/nl/hannahsten/texifyidea/refactoring/inlinefile/LatexInlineFileDialog.kt
Should work better outside of IJ
Fix #3244
Inlining a command will no longer piggyback off of Java's inline settings, and so will need to be specified every time, but it will work in any ide regardless of the status of the `java` plugin
> Improve inline resilience

- CHANGELOG.md
- build.gradle.kts
- gradle.properties
- src/nl/hannahsten/texifyidea/editor/MathEnvironmentEditor.kt
- src/nl/hannahsten/texifyidea/intentions/LatexInlineDisplayToggleIntention.kt
- test/nl/hannahsten/texifyidea/intentions/LatexInlineDisplayToggleIntentionTest.kt
Fix #3249 
* Reuse the `MathEnvironmentEditor` in the inline/display math toggle intention, so its behaviour is consistent with the other math environment toggle inspection.
* Fix behaviour for the edge cases where a math environment is at the start of end of a document.
See test cases.
> Math toggle intention

- src/nl/hannahsten/texifyidea/structure/latex/LatexStructureViewElement.kt
- test/nl/hannahsten/texifyidea/structure/latex/LatexStructureViewElementTest.kt
Fix #3273 
* Fixes that structure view  elements would be inserted too deep in the tree in some occasions.
* Added a test case for this as well as for #2681 (it seems likely that the change there actually broke this).
```latex
\section{s}
\subsection{ss}
\subsubsection{sss}
\paragraph{p}
\paragraph{p}
\paragraph{p}
\subsection{ss}
```
open the structure view.
> 3273 Fix structure view nesting

- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexUnresolvedReferenceInspection.kt
- src/nl/hannahsten/texifyidea/util/files/LatexPackageLocationCache.kt
Fix #3294
* Include bib files in package location cache, as it is used for input file references for \bibliography commands
> Include bib files in package location cache

- src/nl/hannahsten/texifyidea/index/IndexUtilBase.kt
Fix #3306
* Almost all exceptions thrown on this line are not from TeXiFy, I keep reporting them to youtrack but let's just ignore them.
> Ignore all non-TeXiFy indexing exceptions

- src/nl/hannahsten/texifyidea/util/parser/BibtexPsiUtil.kt
- test/nl/hannahsten/texifyidea/inspections/bibtex/BibtexDuplicateIdInspectionTest.kt
- test/nl/hannahsten/texifyidea/psi/BibtexEntryImplUtilTest.kt
Fixes #3361 and #3360
* Fixed the incorrect warning of duplicate `@string` ids in  bib files. (#3361).
* Fixed that empty items showed up weird in the structure view. (#3360).
* Fixed that empty items all had the same id.
See added tests.
> Fix #3361: false positive on duplicate identifier on @string entries in bib files

- src/nl/hannahsten/texifyidea/documentation/LatexDocumentationProvider.kt
Fix #3335 
I am unable to test the changes, but I presume that since we were calling `mthelp` without checking for its presence, that that hung things up a lot. Feel free to change the error handling
> Check for mthelp before calling it

- resources/inspectionDescriptions/LatexUndefinedCommand.html
- src/nl/hannahsten/texifyidea/run/latex/LatexCommandLineState.kt
- src/nl/hannahsten/texifyidea/run/latex/LatexOutputPath.kt
- src/nl/hannahsten/texifyidea/run/latex/LatexRunConfiguration.kt
Fix #3322
* Never create output directories recursively when creating output paths for #70
* Clean up these created output directories if empty, also when running a run configuration multiple times (e.g. with bibtex inbetween)
> Don't recursively create output directories and remember files to clean up

- src/nl/hannahsten/texifyidea/util/parser/LatexPsiUtil.kt
- test/nl/hannahsten/texifyidea/inspections/latex/codestyle/LatexGatherEquationsInspectionTest.kt
Fix #3321 
Previously, the `\item{\[a=b\]}` was returning true from `isDisplayMath` due to it not caring about the depth that the `DisplayMath` child was. This fix passed all tests locally by requiring the math child to be at a depth of exactly 1. 
What should this do?
```latex
\begin{enumerate}
\item{ \[a=b\] \[b=a\] }
\end{enumerate}
```
right now it does not error and there is no test for it.
> Fix equation gathering

- CHANGELOG.md
- build.gradle.kts
- gradle.properties
- src/nl/hannahsten/texifyidea/completion/LatexCommandsAndEnvironmentsCompletionProvider.kt
- src/nl/hannahsten/texifyidea/completion/LatexExternalCommandsIndexCache.kt
- src/nl/hannahsten/texifyidea/index/IndexUtilBase.kt
- src/nl/hannahsten/texifyidea/lang/commands/LatexCommand.kt
- src/nl/hannahsten/texifyidea/startup/LoadUnloadListener.kt
Fix #3359
* Add indexed commands to the autocompletion in background by only adding the keys/values to a set in the read action and doing the rest outside of the read action
* Don't wait for cache to be filled after ide start
* If indexed commands are not yet available, do show hardcoded commands
* Show progress bar when filling cache
Start IDE, try autocompletion. Hardcoded commands should show up in 1-3 seconds, indexed commands after progress bar is complete
> Add indexed commands to autocompletion in background

- src/nl/hannahsten/texifyidea/formatting/spacingrules/TableAlignRule.kt
- src/nl/hannahsten/texifyidea/util/parser/Psi.kt
- test/nl/hannahsten/texifyidea/formatting/TableAlignTest.kt
Fix #3336 
* Fix alignment of `&` inside tables when used inside a `\url` command.
See tests
> Fix #3336: disable alignment of & in \url commands in table

- src/nl/hannahsten/texifyidea/lang/DefaultEnvironment.kt
Fix #3388
* This configures math mode for the 12 optidef environments 
Optidef environments are now using math mode in the editor. 
```latex
\usepackage{optidef}
\begin{maxi!}|l|[3]
{x}{x}{}{}{}
\addConstraint{x}{\leq 0}{}\label{test}
\end{maxi!}
\end{document}
```
> Define optidev environments

- CHANGELOG.md
- gradle.properties
- src/nl/hannahsten/texifyidea/action/preview/InkscapePreviewer.kt
Previously, when inkscape was not installed (but used because of a custom preamble) the error shown would be 'can't read input file'. With this fix it will display the error that inkscape is missing.
> Improve user feedback for preview when Inkscape is not installed

- CHANGELOG.md
- gradle.properties
- src/nl/hannahsten/texifyidea/index/file/LatexIndexableSetContributor.kt
Fix #3316
* Only try to extract package sources once, even if it fails
* Run extraction in background to avoid blocking UI. This may cause files not to be indexed the first time, but not sure
> Improve extraction of MiKTeX package source files

- src/nl/hannahsten/texifyidea/run/latex/LatexRunConfiguration.kt
- src/nl/hannahsten/texifyidea/run/latex/ui/LatexSettingsEditor.kt
- src/nl/hannahsten/texifyidea/run/linuxpdfviewer/InternalPdfViewer.kt
- src/nl/hannahsten/texifyidea/settings/TexifySettings.kt
- src/nl/hannahsten/texifyidea/settings/TexifySettingsState.kt
- src/nl/hannahsten/texifyidea/util/SystemEnvironment.kt
Fix #3302
* Not sure if this was the root cause of the freeze, but waiting for a timed out command doesn't seem sensible to me
* Cache available pdf viewers to improve startup performance
Not sure
> Fix UI freeze in case of timed out system command

- src/nl/hannahsten/texifyidea/psi/LatexPsiHelper.kt
- src/nl/hannahsten/texifyidea/util/SystemEnvironment.kt
> Improve logging

- .github/actions/insert-youtrack-link/action.yml
- src/nl/hannahsten/texifyidea/completion/pathcompletion/LatexPathProviderBase.kt
- src/nl/hannahsten/texifyidea/util/Strings.kt
- test/nl/hannahsten/texifyidea/completion/LatexPathCompletionRelativeToRootFile.kt
Fix [TEX-153](https://texify-idea.myjetbrains.com/youtrack/issue/TEX-153)
* Improved insertion of file name when using the autocompletion.
* Moved the file extension from the main text to the tail text, so it's clear that this is not inserted when selecting the lookup element.
* Upgraded node version in issue linker Action. 
Create two extra files, `one.tex` and `two.tex`, then add a `main.tex` file with the following contents:
```latex
\input{tw.tex}
\end{document}
```
place the caret like `tw<caret>.tex` and trigger the autocompletion. Complete with <kbd>tab</kbd> or <kbd>enter</kbd>.
> Fix bug with completion of file path arguments when text already present

- src/nl/hannahsten/texifyidea/refactoring/inlinefile/LatexInlineFileProcessor.kt
Fix #3434 
Simply does not attempt to insert random whitespaces
Ensure to keep whitespace
main.tex:
```latex
\documentclass[12pt]{article}
\section{PDF Questions}
\input{evil}
\end{document}
```
evil.tex:
```latex
\subsection{subsection}
```
> Just dont inline whitespaces

- build.gradle.kts
Fix #3274
See https://stackoverflow.com/questions/11677572/dealing-with-xerces-hell-in-java-maven
* managed to reproduce the exception, added a dependency on batik-svg-dom (note: the one from xmlgraphics does not work)
* Exclude xml-apis and xerces from all dependencies to avoid exceptions like https://stackoverflow.com/questions/2661326/java-lang-nosuchmethoderror-org-w3c-dom-document-setdocumenturi
> Xerces hell part 2 (equation preview)

- src/nl/hannahsten/texifyidea/action/preview/PreviewAction.kt
- src/nl/hannahsten/texifyidea/action/preview/PreviewFormUpdater.kt
- src/nl/hannahsten/texifyidea/action/preview/ShowTikzPreview.kt
Fix #3314
* tikz pictures will never work with jlatexmath so no point in trying
```latex
\begin{tikzpicture}
\node{3};
\end{tikzpicture}
```
> Do not use jlatexmath for tikz preview

- CHANGELOG.md
- gradle.properties
- src/nl/hannahsten/texifyidea/remotelibraries/mendeley/MendeleyLibrary.kt
Fix #3315
* The parse exception happens because "error(invalid_token)" is not a valid http auth header. I don't know of any better way to detect this
* I think it can happen in cases similar to this: https://stackoverflow.com/questions/72064782/correct-way-to-retrigger-loadtokens-in-ktor-client
> Destroy credentials in case of invalid token

- Writerside/topics/Tool-Windows.md
- resources/META-INF/extensions/tool-windows.xml
- src/nl/hannahsten/texifyidea/action/library/zotero/AddZoteroGroupAction.kt
- src/nl/hannahsten/texifyidea/remotelibraries/RemoteBibLibraryFactory.kt
- src/nl/hannahsten/texifyidea/remotelibraries/zotero/ZoteroGroupLibrary.kt
- src/nl/hannahsten/texifyidea/util/CredentialAttributes.kt
Fix #3356
* Add Zotero Group library, same as Zotero but with group instead of user id
* Not sure how to show the group id in the treeview, it will just say 'zotero group' now
* It would be possible to use the api to retrieve available groups
Group id to test with: 2608283
> Add Zotero Group to the remote libraries tool window

- src/nl/hannahsten/texifyidea/editor/LatexLineWrapStrategy.kt
- src/nl/hannahsten/texifyidea/editor/LatexLineWrapper.kt
- src/nl/hannahsten/texifyidea/util/parser/Psi.kt
- test/nl/hannahsten/texifyidea/editor/LatexParagraphFillHandlerTest.kt
- test/nl/hannahsten/texifyidea/formatting/LatexLineWrapStrategyTest.kt
Fix #2923
Changes to the formatter:
* Don't break on German characters in the middle of words (why is this even a default?)
* Don't line break in math, commands. Not so sure about this.
See new test
> Avoid line breaking in the middle of commands, math and words

- Writerside/topics/Troubleshooting.md
See #3032 
Includes workaround
> Add a known parser issue to the documentation

- CHANGELOG.md
- Writerside/topics/Run-configuration-settings.md
- build.gradle.kts
- gradle.properties
- src/nl/hannahsten/texifyidea/editor/postfix/LatexPostfixExpressionSelector.kt
- src/nl/hannahsten/texifyidea/run/compiler/LatexCompiler.kt
- src/nl/hannahsten/texifyidea/run/latex/LatexRunConfiguration.kt
- src/nl/hannahsten/texifyidea/run/latex/ui/LatexSettingsEditor.kt
Fix #3040
* Allow running LaTeX before running the main file. There are certainly nicer ways to do this but I want to save that for the new run config
```latex
\usepackage{etoolbox}
\providecommand{\waarde}{true}
\newbool{binair}
\setbool{binair}{\waarde}
\ifbool{binair}{waar}{onwaar}
\end{document}
```
then put `\newcommand{\waarde}{false} ` in run config
> Support running code before compiling the main file

- Writerside/topics/External-tools.md
- src/nl/hannahsten/texifyidea/lang/LatexPackage.kt
- src/nl/hannahsten/texifyidea/run/latex/LatexRunConfiguration.kt
- src/nl/hannahsten/texifyidea/run/latex/MakeindexUtil.kt
- src/nl/hannahsten/texifyidea/run/makeindex/MakeindexCommandLineState.kt
- src/nl/hannahsten/texifyidea/run/makeindex/RunMakeindexListener.kt
- src/nl/hannahsten/texifyidea/settings/sdk/LatexSdk.kt
- src/nl/hannahsten/texifyidea/util/magic/PackageMagic.kt
Fix #3106 
* Automatically create makeindex run config with the correct arguments when using nomencl
See docs
> Add support for nomencl package

- Writerside/topics/Contributing-to-the-source-code.md
- src/nl/hannahsten/texifyidea/lang/LatexPackage.kt
- src/nl/hannahsten/texifyidea/lang/commands/LatexNewDefinitionCommand.kt
- src/nl/hannahsten/texifyidea/util/magic/CommandMagic.kt
Support for 6 commands from `xargs` package.
Also, a little bit documentation for potential contributors. (I'm perfectly fine with throwing this part off the window, if it's deemed garbage - I have no confidence in my doc writing)
Use `\newcommandx` in project, see that it's treated exactly like `newcommand`.
> Add support for commands from xparse package, and document how to do it again

- src/nl/hannahsten/texifyidea/grammar/BibtexLexer.flex
- src/nl/hannahsten/texifyidea/util/Bibtex.kt
- src/nl/hannahsten/texifyidea/util/parser/BibtexPsiUtil.kt
- test/nl/hannahsten/texifyidea/psi/BibtexEntryImplUtilTest.kt
- test/nl/hannahsten/texifyidea/reference/BibtexIdCompletionTest.kt
Fix #3472 
* Finished the implementation of adding verbatim strings to bib elements.
<kbd>Ctrl</kbd> + click the link in
```bibtex
@online{TeXiFy-IDEA,
url="https://github.com/Hannah-Sten/TeXiFy-IDEA"
}
```
> Fix #3472 by finishing implementation of urls in bib as verbatim

- src/nl/hannahsten/texifyidea/formatting/LatexBlock.kt
- src/nl/hannahsten/texifyidea/formatting/LatexWrappingStrategy.kt
- test/nl/hannahsten/texifyidea/formatting/LatexLineWrapStrategyTest.kt
Fix #3491 
* Only break lines at whitespace when wrapping.
* Somehow, wrapping behaviour while typing is still the same as before.
```latex
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore (aaaaa)
\end{document}
```
> When wrapping, only break lines at whitespace

- CHANGELOG.md
- build.gradle.kts
- gradle.properties
- src/nl/hannahsten/texifyidea/grammar/LatexLexer.flex
- src/nl/hannahsten/texifyidea/grammar/LatexParserDefinition.kt
- test/nl/hannahsten/texifyidea/psi/LatexParserTest.kt
- test/nl/hannahsten/texifyidea/refactoring/IntroduceVariableTest.kt
Fix #3101
* Lex \begin and \end in \newcommand and \providecommand as regular commands, as they are often unmatched
```latex
\newcommand{\tableMod}[0]{
\end{multicols}
\insertedObject
\begin{multicols}{2}
}
```
> Ignore \begin and \end commands in \newcommand

- src/nl/hannahsten/texifyidea/editor/pasteproviders/LatexPasteProviderUtil.kt
- src/nl/hannahsten/texifyidea/editor/pasteproviders/StyledTextHtmlToLatexConverter.kt
- test/nl/hannahsten/texifyidea/editor/HtmlPasteProviderTest.kt
Fix #3463
* Disable replacements which would break valid LaTeX (we cannot detect whether something is LaTeX)
* Preserve newlines
_Paste all of this, including this italic text to activate the html handler_
```latex
\newcommand{\mylabel}[1]{\label{#1}}
\section{One}\mylabel{sec:one}
```
> Fix pasting of LaTeX

- src/nl/hannahsten/texifyidea/editor/pasteproviders/ImagePasteProvider.kt
- src/nl/hannahsten/texifyidea/editor/pasteproviders/StyledTextHtmlToLatexConverter.kt
- test/nl/hannahsten/texifyidea/editor/HtmlPasteProviderTest.kt
Fix a part of #3463
* When both paste providers can do a paste, prefer the text instead of the image
Copy from LibreOffice Calc into a .tex file
> Prefer pasting tables as text instead of image

- src/nl/hannahsten/texifyidea/action/library/SyncLibraryAction.kt
- src/nl/hannahsten/texifyidea/run/latex/LatexCommandLineState.kt
Fix #3510
also fix #3462 UninitializedPropertyAccessException: lateinit property expandedPaths has not been initialized
* Apparently getting module info is slow enough to require a model progress bar
> Add progress bar when creating output directories

- resources/META-INF/extensions/files-and-project.xml
- src/nl/hannahsten/texifyidea/index/LatexIndexPatternBuilder.kt
Fix #3456
* Added support for multiline todo's in latex
```latex
% TODO this is a test
%  this is still a test
```
> Fix #3456: Add support for multiline todo's for latex

- CHANGELOG.md
- build.gradle.kts
- gradle.properties
- src/nl/hannahsten/texifyidea/LatexErrorReportSubmitter.kt
- src/nl/hannahsten/texifyidea/grammar/LatexLexer.flex
- test/nl/hannahsten/texifyidea/psi/LatexParserTest.kt
Fix #3488 or at least the example at the end of the discussion
* The two commands happen to be similar to \newcommand in number of parameters
see https://github.com/Hannah-Sten/TeXiFy-IDEA/issues/3488#issuecomment-2075807203
> Allow unmatched \begin and \end commands in \BeforeBeginEnvironment and \AfterEndEnvironment

- README.md
- src/nl/hannahsten/texifyidea/completion/pathcompletion/LatexPathProviderBase.kt
- src/nl/hannahsten/texifyidea/modules/LatexModuleBuilder.kt
- src/nl/hannahsten/texifyidea/reference/InputFileReference.kt
- src/nl/hannahsten/texifyidea/run/bibtex/BibtexRunConfiguration.kt
- src/nl/hannahsten/texifyidea/run/bibtex/BibtexSettingsEditor.kt
- src/nl/hannahsten/texifyidea/run/latex/LatexOutputPath.kt
- src/nl/hannahsten/texifyidea/run/latex/LatexRunConfiguration.kt
- src/nl/hannahsten/texifyidea/run/makeindex/MakeindexSettingsEditor.kt
- src/nl/hannahsten/texifyidea/settings/sdk/MiktexWindowsSdk.kt
- src/nl/hannahsten/texifyidea/settings/sdk/NativeTexliveSdk.kt
- src/nl/hannahsten/texifyidea/util/files/Files.kt
- src/nl/hannahsten/texifyidea/util/files/VirtualFile.kt
Fix #3354
* Don't use findFileByPath on empty strings as that will resolve to jetbrains /bin directory
> Handle empty working directory in bibtex run configuration

- CHANGELOG.md
- build.gradle.kts
- gradle.properties
- src/nl/hannahsten/texifyidea/editor/pasteproviders/HtmlPasteProvider.kt
- src/nl/hannahsten/texifyidea/editor/pasteproviders/LatexPasteProviderUtil.kt
- test/nl/hannahsten/texifyidea/editor/HtmlPasteProviderTest.kt
* Pasting from a pdf was not working on Windows: `java.lang.AssertionError: Wrong line separators: '...Integrity.\r\n' at offset 606`
* Pasting contenting containing html comments did not work, now they are skipped
> Fix copy from pdf file

- src/nl/hannahsten/texifyidea/psi/impl/LatexCommandsImplMixin.kt
- src/nl/hannahsten/texifyidea/structure/latex/LatexNewCommandPresentation.kt
- src/nl/hannahsten/texifyidea/structure/latex/LatexOtherCommandPresentation.kt
- src/nl/hannahsten/texifyidea/structure/latex/LatexPresentationFactory.kt
- src/nl/hannahsten/texifyidea/util/parser/Psi.kt
Fix #3547 
* Show `fileName:lineNumber` in go to defition popup item.
```latex
\newcommand{\tree}{tree}
\renewcommand{\tree}{tr}
\tree
\end{document}
```
> #3547 go to definition view

- resources/META-INF/extensions/files-and-project.xml
- src/nl/hannahsten/texifyidea/LatexRenameProcessor.kt
Fix #3551
So. The simplest solution was to simply make a custom Rename Processor that would gobble up **ALL** PsiFiles and automatically null the editor. This has the side effect of making *every* file refactor not select the extension by default, which covers my issue, but may cause problems?
I tested, every `\input` will have this behavior (which IMO is just another manifestation of this issue), refactoring commands from `\newcommand` is unaffected.
Attempting to refactor a package does *not* work.
Let me know if we need to go ahead and actually implement more logic. If anything, this opens the door to smarter refactoring? 
```latex
\includegraphics{IM<caret>G.jpg}
```
> Do not select the extension when refactoring file names

- CHANGELOG.md
- gradle.properties
- src/nl/hannahsten/texifyidea/completion/handlers/RightInsertHandler.kt
- test/nl/hannahsten/texifyidea/completion/RightInsertHandlerTest.kt
…tched brace pairs)
Fix #3493 
* Don't insert \right when brace is already matched for existing brace pairs
See test
> Don't insert \right when brace is already matched

- src/nl/hannahsten/texifyidea/formatting/LatexBlock.kt
- src/nl/hannahsten/texifyidea/formatting/LatexSpacingRules.kt
- src/nl/hannahsten/texifyidea/grammar/Latex.bnf
- src/nl/hannahsten/texifyidea/grammar/LatexLexer.flex
- src/nl/hannahsten/texifyidea/grammar/LatexParserDefinition.kt
- src/nl/hannahsten/texifyidea/highlighting/LatexPairedBraceMatcher.kt
- src/nl/hannahsten/texifyidea/highlighting/LatexSyntaxHighlighter.kt
- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexNonMatchingIfInspection.kt
- src/nl/hannahsten/texifyidea/lang/LatexPackage.kt
- src/nl/hannahsten/texifyidea/util/magic/CommandMagic.kt
- src/nl/hannahsten/texifyidea/util/magic/PatternMagic.kt
- src/nl/hannahsten/texifyidea/util/parser/LatexCommandsUtil.kt
- test/nl/hannahsten/texifyidea/formatting/LatexFormattingTest.kt
- test/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexNonMatchingIfInspectionTest.kt
Fix #3121
* Support plain TeX \if formatting
* Does not support user defined \ifs, but it will not lead to a parse error, just weird formatting
* I don't know why anyone would use plain TeX instead of e.g. etoolbox
```latex
\ifx\mycmd\undefined
undefed
\else
\if\mycmd1
defed, 1
\else
defed
\fi
\fi
```
> Support plain TeX \if formatting

- src/nl/hannahsten/texifyidea/grammar/LatexLexer.flex
In addition to `\ProvidesExplPackage`, LaTeX3 also introduces `\ProvidesExplClass`
and `\ProvidesExplFile`, which also have the effect of enabling LaTeX3 syntax. This
pr adds support for the latter two.
See the [LaTeX 3 interfaces manual](https://texdoc.org/serve/interface3/0), § 2.1 ‘Using the LaTeX3 modules’.
```latex
\NeedsTeXFormat{LaTeX2e}
\ProvidesExplClass{myclass}{2024/06/08}{v1.0}{A class implemented in LaTeX3}
\cs_new:Npn \__my_internal_class_command:n #1 { Hello, ~ #1 ! }
```
(Ticked the second box on the grounds that there were no tests for `\ProvidesExplPackage` either...)
> [Lexer] Add support for `\ProvidesExpl(Class|File)`

- CHANGELOG.md
- Writerside/topics/Code-completion.md
- gradle.properties
- src/nl/hannahsten/texifyidea/editor/postfix/LatexPostFixTemplateProvider.kt
- src/nl/hannahsten/texifyidea/editor/postfix/LatexPostfixExpressionSelector.kt
- src/nl/hannahsten/texifyidea/editor/postfix/LatexStringBasedPostfixTemplates.kt
- src/nl/hannahsten/texifyidea/editor/postfix/editable/LatexEditablePostfixTemplate.kt
- src/nl/hannahsten/texifyidea/editor/postfix/editable/LatexPostfixTemplateEditor.kt
- src/nl/hannahsten/texifyidea/editor/postfix/editable/LatexPostfixTemplateExpressionCondition.kt
- src/nl/hannahsten/texifyidea/file/LatexFileType.kt
Fix #3466 
* Added simple editor so users can create their own very simple postfix templates. For now users are directed to the [Custom Postfix Templates](https://plugins.jetbrains.com/plugin/9862-custom-postfix-templates) plugin to create more complex postfix templates.
> Editable postfix templates

- src/nl/hannahsten/texifyidea/inspections/latex/codematurity/LatexDiscouragedUseOfDefInspection.kt
- test/nl/hannahsten/texifyidea/inspections/latex/codematurity/LatexDiscouragedUseOfDefInspectionTest.kt
Fix #3576
* Support `#1` syntax in inspection that converts `\def` to `\newcommand`.
See tests.
> Support conversion of arguments in \def -> \newcommand quickfix

- build.gradle.kts
- src/nl/hannahsten/texifyidea/action/ForwardSearchAction.kt
- src/nl/hannahsten/texifyidea/run/linuxpdfviewer/evince/EvinceConversation.kt
- src/nl/hannahsten/texifyidea/run/linuxpdfviewer/evince/EvinceInverseSearchListener.kt
- src/nl/hannahsten/texifyidea/startup/StartEvinceInverseSearchListener.kt
- src/nl/hannahsten/texifyidea/util/Projects.kt
- src/org/gnome/evince/Daemon.kt
- src/org/gnome/evince/SyncViewSourcePointStruct.kt
- src/org/gnome/evince/Window.kt
Fix https://github.com/Hannah-Sten/TeXiFy-IDEA/issues/3590 and refactor the DBus support to use `dbus-java` for all interactions with Evince instead of spawning command line processes. I hope you agree with the changes I made here and thank you for maintaining this plugin!
* Start EvinceInverseSearchListener even if no runConfiguration exists, but the default template has Evince as PDF viewer
* Use `dbus-java` for sending the `SyncView` DBus message and for connection to the `SyncSource` DBus signal
1. Open a latex file and set Evince as PDF viewer for the template, the choose current file and run the configuration
2. Open a latex file and set Evince as PDF viewer for the current runConfiguration
-> In both cases Forward and Backward search should work out of box.
> Fix EvinceListener not starting and refactor DBus support

- CHANGELOG.md
- Writerside/topics/Contributing-to-the-source-code.md
- build.gradle.kts
- gradle.properties
- src/nl/hannahsten/texifyidea/completion/pathcompletion/LatexPathProviderBase.kt
- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexNestedIncludesInspection.kt
- src/nl/hannahsten/texifyidea/lang/commands/LatexGenericRegularCommand.kt
- src/nl/hannahsten/texifyidea/lang/commands/RequiredFileArgument.kt
- src/nl/hannahsten/texifyidea/lang/commands/RequiredPicturePathArgument.kt
- src/nl/hannahsten/texifyidea/reference/InputFileReference.kt
- src/nl/hannahsten/texifyidea/run/bibtex/logtab/BibtexOutputListener.kt
- src/nl/hannahsten/texifyidea/run/latex/LatexRunConfiguration.kt
- src/nl/hannahsten/texifyidea/run/latex/logtab/LatexOutputListener.kt
- src/nl/hannahsten/texifyidea/util/files/PsiFile.kt
- src/nl/hannahsten/texifyidea/util/files/RootFile.kt
- src/nl/hannahsten/texifyidea/util/files/VirtualFile.kt
- src/nl/hannahsten/texifyidea/util/parser/LatexCommandsImplMixinUtil.kt
- test/nl/hannahsten/texifyidea/completion/LatexAbsolutePathCompletionTest.kt
- test/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexFileNotFoundInspectionTest.kt
Fix #3587
* In #3542, the behaviour of findFile() was changed to only accept the found file if the extension is in the provided list. However, this is only correct for commands like \includegraphics, for \input any file extension is fine.
```latex
\usepackage{graphicx}
% works
\input{kameel.*}
% fails
\includegraphics{not-an-image3.nopng}
\end{document}
```
> Make a distinction between commands that can or cannot accept files with any extension

- src/nl/hannahsten/texifyidea/structure/latex/LatexSectionPresentation.kt
Fix #3626
To reproduce: hover over a \section command without a parameter
> Fix crash in structure view if section command has no parameters, fix #3626

- src/nl/hannahsten/texifyidea/lang/commands/LatexSiunitxCommand.kt
In version 3, the siunitx commands changed. This commit adds those commands to LatexSiunitxCommand.kt and removes an old command (numrange), which would conflict with one new command. 
Also, some of the previously implemented commands aren't recommended anymore by the package. I'm not sure, if there is already a way to mark a command completion as deprecated, so I just added a comment.
> Update siunix command completion

- .github/workflows/main.yml
- src/nl/hannahsten/texifyidea/editor/typedhandlers/LatexTypedHandler.kt
- test/nl/hannahsten/texifyidea/editor/typedhandlers/LatexTypedHandlerTest.kt
Fix #3493 
* Fixed behaviour described in https://github.com/Hannah-Sten/TeXiFy-IDEA/issues/3493#issuecomment-2133974052 for `(`, `[`, and `{`.
See test cases:
```kotlin
fun testCorrectPairedParenthesis() {
myFixture.configureByText(LatexFileType, """$\left<caret>$""")
myFixture.type('(')
myFixture.checkResult("""$\left(<caret>\right)$""")
}
fun testCorrectPairedBraces() {
myFixture.configureByText(LatexFileType, """$\left<caret>$""")
myFixture.type('{')
myFixture.checkResult("""$\left{<caret>\right}$""")
}
fun testCorrectPairedBrackets() {
myFixture.configureByText(LatexFileType, """$\left<caret>$""")
myFixture.type('[')
myFixture.checkResult("""$\left[<caret>\right]$""")
}
```
> Insert `\right)` when typing `\left(` without using autocomplete

- CHANGELOG.md
- src/nl/hannahsten/texifyidea/structure/bibtex/BibtexStructureViewElement.kt
> Fix crash if using bibtex structure view when bibtex file type is reassignd to plain text

- src/nl/hannahsten/texifyidea/action/sumatra/ConfigureInverseSearchAction.kt
- src/nl/hannahsten/texifyidea/run/sumatra/SumatraConversation.kt
- src/nl/hannahsten/texifyidea/startup/TexLivePackageListInitializer.kt
- src/nl/hannahsten/texifyidea/util/CommandRunner.kt
- src/nl/hannahsten/texifyidea/util/Strings.kt
- src/nl/hannahsten/texifyidea/util/SystemEnvironment.kt
- src/nl/hannahsten/texifyidea/util/files/LatexPackageLocationCache.kt
Fix #3653
* Add a non-blocking command runner `CommandRunnerKt.runCommandNonBlocking()` and refactor `SystemEnvironmentKt.runCommand()` and `SystemEnvironmentKt.runCommandWithExitCode()` to use it as their base. The main differences are:
* Input pipe is closed, if no input is provided.
* If the output is not discarded, both output streams are read asynchronously. If the called program times out, the streams are still read until the pipe closes even if they are not already ready. This should not lead to problems as long as Java is able to kill the process. One could try to implement the readers in a less blocking way to at least make them abortable before something is read but this does seem to be a pretty complex problem.
* The function is less blocking.
* **[Breaking]** Change parameter …
> Fix `kpsewhich` timeout on Windows using Tex Live Full

- CHANGELOG.md
- gradle.properties
- src/nl/hannahsten/texifyidea/reference/InputFileReference.kt
- test/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexFileNotFoundInspectionTest.kt
- test/resources/inspections/latex/filenotfound/commandexpansion/nest/sub.tex
- test/resources/inspections/latex/filenotfound/subfilestest/main.tex
- test/resources/inspections/latex/filenotfound/subfilestest/subdir/onedown.tex
- test/resources/inspections/latex/filenotfound/subfilestest/subdir/subsubdir/twodown.tex
* Resolve only relative to the current file if the current file is a root file, in particular when using subfiles
> Improve reference resolving when using subfiles

- CHANGELOG.md
- src/nl/hannahsten/texifyidea/run/compiler/LatexCompiler.kt
> Fix default Docker image name when running Dockerized TeX Live without a project SDK

- src/nl/hannahsten/texifyidea/editor/pasteproviders/LatexPasteProviderUtil.kt
> Fix html check when pasting tables from Excel

- CHANGELOG.md
- src/nl/hannahsten/texifyidea/run/linuxpdfviewer/InternalPdfViewer.kt
> Use xdg-mime to choose a default pdf viewer in the run configuration template

- CHANGELOG.md
- src/nl/hannahsten/texifyidea/structure/latex/LatexParagraphPresentation.kt
- src/nl/hannahsten/texifyidea/structure/latex/LatexPartPresentation.kt
- src/nl/hannahsten/texifyidea/structure/latex/LatexStructureViewElement.kt
- src/nl/hannahsten/texifyidea/structure/latex/LatexSubParagraphPresentation.kt
- src/nl/hannahsten/texifyidea/structure/latex/LatexSubSectionPresentation.kt
- src/nl/hannahsten/texifyidea/structure/latex/LatexSubSubSectionPresentation.kt
> Fix exceptions in structure view when command parameters are missing

- CHANGELOG.md
- src/nl/hannahsten/texifyidea/grammar/Latex.bnf
- test/nl/hannahsten/texifyidea/psi/LatexParserTest.kt
> Fix a parser issue with bidirectional arrow in TikZ

- src/nl/hannahsten/texifyidea/TexifyIcons.kt
- src/nl/hannahsten/texifyidea/ui/TeXiFyProjectViewNodeDecorator.kt
Fix #3674
I comment the case for txt, so I think the the icon of txt will use the defualt configuration of clion (CMakeLists.txt will use cmake icon) to solve this issue https://github.com/Hannah-Sten/TeXiFy-IDEA/issues/3674
But I don't know how to build the plugin, so I haven't test the result. Since the changes are very simple(only 1 line), I hope you can test for me:) thanks a lot!
* 
```latex
```
> txt format will use default icon, because CMakeLists.txt should use cmake icon

- CHANGELOG.md
- gradle.properties
- src/nl/hannahsten/texifyidea/run/linuxpdfviewer/evince/EvinceInverseSearchListener.kt
- src/nl/hannahsten/texifyidea/startup/StartEvinceInverseSearchListener.kt
> Disable Evince inverse search on Windows to avoid a UI freeze on opening a second project

- CHANGELOG.md
- src/nl/hannahsten/texifyidea/grammar/Latex.bnf
- src/nl/hannahsten/texifyidea/inspections/latex/redundancy/LatexDuplicateLabelInspection.kt
- test/nl/hannahsten/texifyidea/inspections/latex/redundancy/LatexDuplicateLabelInspectionTest.kt
- test/nl/hannahsten/texifyidea/psi/LatexParserTest.kt
Fix #3397 in some way. No idea how this can be done with parser support
> Fix basic case of false positive of duplicate label inspection when user defined \if commands are used

- CHANGELOG.md
- src/nl/hannahsten/texifyidea/util/files/ReferencedFileSetCache.kt
> Check if file is still valid after retrieving from cache 

- CHANGELOG.md
- gradle.properties
- src/nl/hannahsten/texifyidea/completion/pathcompletion/LatexGraphicsPathProvider.kt
- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexFileNotFoundInspection.kt
- src/nl/hannahsten/texifyidea/lang/LatexPackage.kt
- src/nl/hannahsten/texifyidea/lang/commands/LatexGenericRegularCommand.kt
- src/nl/hannahsten/texifyidea/reference/InputFileReference.kt
- src/nl/hannahsten/texifyidea/util/magic/CommandMagic.kt
> Add support for \includesvg

- CHANGELOG.md
- src/nl/hannahsten/texifyidea/grammar/LatexLexer.flex
- test/nl/hannahsten/texifyidea/psi/LatexParserTest.kt
> Disallow unmatched braces after \@ifnextchar

- CHANGELOG.md
- src/nl/hannahsten/texifyidea/action/preview/InkscapePreviewer.kt
- src/nl/hannahsten/texifyidea/action/preview/JlatexmathPreviewer.kt
- src/nl/hannahsten/texifyidea/action/preview/PreviewFormUpdater.kt
- src/nl/hannahsten/texifyidea/util/UserInterface.kt
Fix #3435
Updated both previewers, the inkscape preview can be triggered by adding
```latex
%! begin preamble = math
%! end preamble = math
```
> Use theme foreground and background colors for equation preview

- CHANGELOG.md
- gradle.properties
- src/nl/hannahsten/texifyidea/index/file/LatexIndexableSetContributor.kt
- src/nl/hannahsten/texifyidea/settings/sdk/TexliveSdk.kt
- src/nl/hannahsten/texifyidea/util/CommandRunner.kt
- src/nl/hannahsten/texifyidea/util/SystemEnvironment.kt
* Cache where/which commands, because one of these was causing UI freezes sometimes (via texlive sdk home paths)
* Ignore indexes not ready exception for absolute file paths retrieval
> Improve performance of finding files to be indexed

- CHANGELOG.md
- build.gradle.kts
- src/nl/hannahsten/texifyidea/inspections/grazie/LatexTextExtractor.kt
- src/nl/hannahsten/texifyidea/lang/commands/LatexGenericRegularCommand.kt
- src/nl/hannahsten/texifyidea/lang/commands/LatexGlossariesCommand.kt
- test/nl/hannahsten/texifyidea/inspections/grazie/GrazieInspectionTest.kt
- test/resources/inspections/grazie/CheckGrammarInConstructs.tex
- test/resources/inspections/grazie/MultilineCheckGrammar.tex
* Fix #3508: argument type of \gls commands
* Fix #3141: parameter text should be kept as it is usually part of a sentence
* Fix #3621: similar to previous one
* Fix #3494: Newlines may be crucial information to know that things are not part of the same sentence, so keep them
* Fix #3700: fix math environment check
* Disable Grazie in tabular as it contains no full sentences usually
> Improve Grazie implementation

- CHANGELOG.md
- src/nl/hannahsten/texifyidea/run/bibtex/BibtexSettingsEditor.kt
- src/nl/hannahsten/texifyidea/run/latex/externaltool/ExternalToolSettingsEditor.kt
- src/nl/hannahsten/texifyidea/run/latex/ui/LatexSettingsEditor.kt
- src/nl/hannahsten/texifyidea/run/makeindex/MakeindexSettingsEditor.kt
Fix #3799
* De-duplicate content roots in main file select field
* Change extension from .tex to tex, I think this broke in 2024.3?
> Fix main file selection

- CHANGELOG.md
- src/nl/hannahsten/texifyidea/completion/LatexBibliographyReferenceProvider.kt
- src/nl/hannahsten/texifyidea/inspections/LatexSpellcheckingStrategy.kt
- test/nl/hannahsten/texifyidea/inspections/latex/LatexSpellCheckingStrategyTest.kt
Fix #3543
Fix #3802 , maybe?
Relies on our hardcoded information about parameter type
> Include optional parameters in spellcheck, if it contains text

- src/nl/hannahsten/texifyidea/index/file/LatexIndexableSetContributor.kt
Attempt to avoid the "Indexing process should not rely on non-indexed file data" error, which is a java.lang.Throwable we cannot catch in Kotlin
> Search for external bib files in background

- CHANGELOG.md
- Writerside/topics/Editing-a-LaTeX-file.md
- src/nl/hannahsten/texifyidea/gutter/LatexNavigationGutter.kt
- src/nl/hannahsten/texifyidea/highlighting/LatexAnnotator.kt
- src/nl/hannahsten/texifyidea/index/stub/LatexCommandsStubElementType.kt
- src/nl/hannahsten/texifyidea/lang/alias/AliasManager.kt
- src/nl/hannahsten/texifyidea/lang/alias/CommandManager.kt
- src/nl/hannahsten/texifyidea/structure/filter/IncludesFilter.kt
- src/nl/hannahsten/texifyidea/structure/filter/LabelFilter.kt
- src/nl/hannahsten/texifyidea/structure/latex/LatexIncludePresentation.kt
- src/nl/hannahsten/texifyidea/structure/latex/LatexLabelPresentation.kt
- src/nl/hannahsten/texifyidea/structure/latex/LatexPresentationFactory.kt
- src/nl/hannahsten/texifyidea/structure/latex/LatexStructureViewElement.kt
- src/nl/hannahsten/texifyidea/util/CommandAlias.kt
- src/nl/hannahsten/texifyidea/util/Commands.kt
- src/nl/hannahsten/texifyidea/util/labels/ProjectLabels.kt
- src/nl/hannahsten/texifyidea/util/magic/CommandMagic.kt
- src/nl/hannahsten/texifyidea/util/parser/LatexCommandsImplMixinUtil.kt
- test/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexFileNotFoundInspectionTest.kt
- test/nl/hannahsten/texifyidea/lang/CommandManagerTest.kt
Fix #3492
Similar to labels, but for all the include commands at once. Due to caching, may only work the second time something happens (type action, highlighting, etc)
> Add support for automatic detection of custom command aliases for include commands

- CHANGELOG.md
- src/nl/hannahsten/texifyidea/structure/latex/LatexBreadcrumbsInfo.kt
Fix #3545, partially. I did not manage to get sections to stick properly: if I add elements to acceptElement so that sections will stick, then other things break, like environments sticking too much. So I guess the only way is to add sections to the parser, but for now I just want to test this a bit.
Breadcrumbs seem to work fine though.
> Add sections to breadcrumbs

- CHANGELOG.md
- src/nl/hannahsten/texifyidea/index/file/LatexExternalPackageInclusionCache.kt
- src/nl/hannahsten/texifyidea/run/compiler/LatexCompiler.kt
- src/nl/hannahsten/texifyidea/util/General.kt
> Fill package inclusion cache in background

- CHANGELOG.md
- gradle.properties
- src/nl/hannahsten/texifyidea/completion/handlers/LatexReferenceInsertHandler.kt
- src/nl/hannahsten/texifyidea/psi/LatexPsiHelper.kt
> Fix line endings for bibtex entry from remote file

- CHANGELOG.md
- src/nl/hannahsten/texifyidea/action/wizard/graphic/InsertGraphicWizardDialogWrapper.kt
Fix #3550
* Hardcoded \linewidth and \textheight, also added option for keepaspectratio
> Add checkboxes to graphic insertion wizard for relative width or height

- CHANGELOG.md
- src/nl/hannahsten/texifyidea/grammar/Latex.bnf
- test/nl/hannahsten/texifyidea/psi/LatexParserTest.kt
> Fix parse error when using parentheses in a group in a key value command argument

- CHANGELOG.md
- src/nl/hannahsten/texifyidea/grammar/LatexLexer.flex
- test/nl/hannahsten/texifyidea/psi/LatexParserTest.kt
> Fix parse error when using commands with arguments in parameter of \href or \url

- CHANGELOG.md
- src/nl/hannahsten/texifyidea/grammar/LatexLexer.flex
- test/nl/hannahsten/texifyidea/psi/LatexParserTest.kt
Fix #3687
Only supports one level of nesting.
> Fix parse erron when using inline math in cases* environment in inline math

- src/nl/hannahsten/texifyidea/structure/latex/BibitemPresentation.kt
- src/nl/hannahsten/texifyidea/structure/latex/LatexChapterPresentation.kt
- src/nl/hannahsten/texifyidea/structure/latex/LatexIncludePresentation.kt
- src/nl/hannahsten/texifyidea/structure/latex/LatexLabelPresentation.kt
- src/nl/hannahsten/texifyidea/structure/latex/LatexParagraphPresentation.kt
- src/nl/hannahsten/texifyidea/structure/latex/LatexPartPresentation.kt
- src/nl/hannahsten/texifyidea/structure/latex/LatexSectionPresentation.kt
- src/nl/hannahsten/texifyidea/structure/latex/LatexStructureViewCommandElement.kt
- src/nl/hannahsten/texifyidea/structure/latex/LatexSubParagraphPresentation.kt
- src/nl/hannahsten/texifyidea/structure/latex/LatexSubSectionPresentation.kt
- src/nl/hannahsten/texifyidea/structure/latex/LatexSubSubSectionPresentation.kt
Fix #3814, caused by mismatch between commandToken.text and .name, which is expected
> Remove unnecessary checks in structure presentation

- CHANGELOG.md
- Writerside/topics/Code-navigation.md
- src/nl/hannahsten/texifyidea/lang/LabelingEnvironmentInformation.kt
- src/nl/hannahsten/texifyidea/lang/alias/EnvironmentManager.kt
- src/nl/hannahsten/texifyidea/lang/commands/LatexNewDefinitionCommand.kt
- src/nl/hannahsten/texifyidea/psi/LatexEnvironmentUtil.kt
- src/nl/hannahsten/texifyidea/reference/LatexLabelReference.kt
- src/nl/hannahsten/texifyidea/util/labels/LabelExtraction.kt
- src/nl/hannahsten/texifyidea/util/labels/Labels.kt
- src/nl/hannahsten/texifyidea/util/magic/CommandMagic.kt
- test/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexUnresolvedReferenceInspectionTest.kt
> Support label references to user defined listings environment

- .github/workflows/main.yml
- CHANGELOG.md
- Writerside/topics/Contributing-to-the-source-code.md
- build.gradle.kts
- gradle.properties
- src/nl/hannahsten/texifyidea/file/listeners/VfsChangeListener.kt
- src/nl/hannahsten/texifyidea/index/IndexUtilBase.kt
- src/nl/hannahsten/texifyidea/index/file/LatexExternalPackageInclusionCache.kt
- src/nl/hannahsten/texifyidea/index/file/LatexIndexableSetContributor.kt
- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/packages/LatexPackageNotInstalledInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/packages/LatexPackageUpdateInspection.kt
- src/nl/hannahsten/texifyidea/run/latex/ui/LatexSettingsEditor.kt
- src/nl/hannahsten/texifyidea/util/General.kt
- src/nl/hannahsten/texifyidea/util/files/FileSet.kt
- src/nl/hannahsten/texifyidea/util/files/PsiFile.kt
- src/nl/hannahsten/texifyidea/util/files/ReferencedFileSetCache.kt
- src/nl/hannahsten/texifyidea/util/files/ReferencedFileSetService.kt
- src/nl/hannahsten/texifyidea/util/files/RootFile.kt
- src/nl/hannahsten/texifyidea/util/files/impl/ReferencedFileSetServiceImpl.kt
- test/nl/hannahsten/texifyidea/TestUtil.kt
- test/nl/hannahsten/texifyidea/completion/LatexGlossaryCompletionTest.kt
- test/nl/hannahsten/texifyidea/inspections/bibtex/BibtexUnusedEntryInspectionTest.kt
- test/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexUnresolvedReferenceInspectionTest.kt
- test/nl/hannahsten/texifyidea/inspections/latex/probablebugs/packages/LatexPackageNameDoesNotMatchFileNameInspectionTest.kt
- test/nl/hannahsten/texifyidea/inspections/latex/probablebugs/packages/LatexPackageNotInstalledInspectionTest.kt
- test/nl/hannahsten/texifyidea/reference/BibtexIdCompletionTest.kt
- test/nl/hannahsten/texifyidea/reference/BibtexIdRemoteLibraryCompletionTest.kt
- test/resources/inspections/latex/unresolvedreference/BibtexReference.tex
Now a file set cache will not be blocking threads anymore but will run in background. This may lead to incorrect behaviour and inspections during the refresh, so a progress bar is shown.
> Refresh file set cache in background

- src/nl/hannahsten/texifyidea/inspections/latex/typesetting/LatexIncorrectSectionNestingInspection.kt
Fix #3853 
* Don't crash when command is not one of the expected commands.
Unable to reproduce, but it seems likely that the index got out of date.
> Don't crash inspection when index out of date, fixes #3853

- src/nl/hannahsten/texifyidea/grammar/LatexLexer.flex
Fix #3840 
* Don't allow whitespace characters as verbatim delimiter. 
In this example the space after the `%` was seen as the closing delimiter of the `\path` command, matching the space that comes right after it.
```latex
\begin{tikzpicture}
\path (0,0)--(1,0);
\some\commands
% Highlighting wrong here
\end{tikzpicture}
```
> Don't allow whitespace characters as verbatim delimiter (fixes #3840)

- src/nl/hannahsten/texifyidea/remotelibraries/RemoteBibLibrary.kt
- src/nl/hannahsten/texifyidea/remotelibraries/mendeley/MendeleyLibrary.kt
Fix #3848 
Attempts to not fail without notification when getting an unexpected response from a remote library.
I'm not sure how to trigger an error, but have verified that logging into Mendeley and syncing the library still works.
> Attempt to show notification of library sync error (fixes #3848)

- src/nl/hannahsten/texifyidea/index/file/LatexExternalEnvironmentDataIndexer.kt
- src/nl/hannahsten/texifyidea/index/file/LatexExternalEnvironmentIndex.kt
- src/nl/hannahsten/texifyidea/util/magic/FileMagic.kt
Fix #3846 maybe
Fix #3866 maybe
> Lazy instantiation of CommandMagic and FileMagic

- src/nl/hannahsten/texifyidea/run/latex/logtab/LatexLogMessageExtractor.kt
- src/nl/hannahsten/texifyidea/run/latex/logtab/LatexOutputListener.kt
- src/nl/hannahsten/texifyidea/run/latex/logtab/messagehandlers/errors/LatexUndefinedControlSequenceHandler.kt
- test/nl/hannahsten/texifyidea/run/logtab/LatexOutputListenerTest.kt
> Improve log parsing of 'undefined control sequence'

- src/nl/hannahsten/texifyidea/inspections/latex/typesetting/LatexMissingGlossaryReferenceInspection.kt
- src/nl/hannahsten/texifyidea/util/files/ReferencedFileSetCache.kt
- test/nl/hannahsten/texifyidea/inspections/latex/typesetting/LatexMissingGlossaryReferenceInspectionTest.kt
> Fix missing glossary reference inspection when using a glossary definition command in a \newcommand

- CHANGELOG.md
- Writerside/topics/Editing-a-LaTeX-file.md
- Writerside/topics/General.md
- src/nl/hannahsten/texifyidea/editor/folding/LatexSectionFoldingBuilder.kt
- test/resources/editor/folding/sections.tex
Fix #3857
* Section folding region ends on the first region or endregion that has no match within the current section
```latex
\titleformat*{\section}{\itshape}
\section{One}
Text.
\subsection{Two}
Text.
\section{Three}
Text.
%! region sections
\section{introduction}
\blindtext
\section{salient point}
%! region section-content
\blindtext
%! endregion
%! endregion
%! region references
\newpage
\printbibliography
%! endregion
\end{document}
```
> Let user defined folding regions override section folding regions by default

- CHANGELOG.md
- src/nl/hannahsten/texifyidea/index/file/LatexExternalPackageInclusionCache.kt
- src/nl/hannahsten/texifyidea/util/files/RootFile.kt
> Fix read action in RootFile

- src/nl/hannahsten/texifyidea/index/IndexUtilBase.kt
Fixes maybe #3886?
* Removed an `it` from an inner lambda, the outer lambda also had implicit parameter `it`.
> Fix shadowing implicit parameter of enclosing lambda

- build.gradle.kts
- src/nl/hannahsten/texifyidea/inspections/grazie/LatexTextExtractor.kt
Fix #3878 
* The text extraction only recognized `$...$` as inline math, but not `\(...\)`. This PR adds `\(...\)`.
```latex
I have some variables \(v_0, v_1\) used in the text.
I have some variables $v_0, v_1$ used in the text.
\end{document}
```
> Include \(\) as inline math for grazie text extraction, fixes #3878

- CHANGELOG.md
- build.gradle.kts
- src/nl/hannahsten/texifyidea/settings/sdk/TectonicSdk.kt
- src/nl/hannahsten/texifyidea/util/files/FileSet.kt
Fix #3879
Assumes that if inputs is present, the unreleased version is used
> Default to 0.15.0 behaviour if inputs field is not found in Tectonic.toml

- CHANGELOG.md
- src/nl/hannahsten/texifyidea/run/bibtex/BibtexCommandLineState.kt
- src/nl/hannahsten/texifyidea/run/bibtex/BibtexRunConfiguration.kt
- src/nl/hannahsten/texifyidea/run/bibtex/BibtexSettingsEditor.kt
- src/nl/hannahsten/texifyidea/run/compiler/BiberCompiler.kt
- src/nl/hannahsten/texifyidea/run/compiler/BibtexCompiler.kt
- src/nl/hannahsten/texifyidea/run/compiler/LatexCompiler.kt
- src/nl/hannahsten/texifyidea/run/latex/LatexRunConfiguration.kt
Fix #3891
When updating from an older version, project sdk will be selected. When a bibtex run config is created by the latex run config, the distribution from the latex run config is used.
> Add WSL support to the bibtex run configuration

- CHANGELOG.md
- src/nl/hannahsten/texifyidea/gutter/LatexElementColorProvider.kt
- test/nl/hannahsten/texifyidea/gutter/LatexGutterTest.kt
> Fix StackOverflowError in color definitions

- CHANGELOG.md
- src/nl/hannahsten/texifyidea/util/CommandRunner.kt
Fix #3909
The timeout was not working properly, as demonstrated by this MWE:
```kotlin
import kotlinx.coroutines.*
import java.util.concurrent.TimeUnit
import kotlin.time.Duration
fun main() {
runBlocking {
val process = ProcessBuilder("sleep", "60").start()
val output = async { process.inputReader().use { it.readText() } }
val timeout = 1000L
val resultCode = withTimeoutOrNull(timeout) {
process.waitFor(timeout, TimeUnit.MILLISECONDS)
} ?: run {
process.destroy()
println("Process destroyed after timeout")
}
val resultOutput = output.await()
println("Process exited with $resultCode and output $resultOutput")
}
}
```
Fixed version:
```kotlin
import kotlinx.coroutines.*
import java.util.concurrent.TimeUnit
import kotlin.time.Duration
fun main() {
runBlocking {
val process = …
```
> Fix timeout in CommandRunner

- CHANGELOG.md
- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexNonMatchingEnvironmentInspection.kt
- test/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexNonMatchingEnvironmentInspectionTest.kt
> Fix a false negative of the non-matching environment name inspection for empty parameters

- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexUnicodeInspection.kt
- src/nl/hannahsten/texifyidea/lang/commands/LatexSiunitxCommand.kt
- src/nl/hannahsten/texifyidea/util/parser/LatexPsiUtil.kt
- src/nl/hannahsten/texifyidea/util/parser/Psi.kt
- test/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexUnicodeInspectionTest.kt
Fix #3916 
* The unicode symbol for Ohm (Ω) has been added to the autocompletion, this also fixes the unicode inspection quick fix for this symbol.
* Fix that the replacement of one of `µΩ` (without space) would delete the other as well.
Note that this doesn't fix (but at least it doesn't make it worse) the problem with multiple descriptors in one psi element, e.g., `µ Ω`, and the "apply all fixes in file". The fix all can't replace the omega because the text range in the descriptor is out-of-date after replacing mu. This is something we should probably fix generally for the texify inspection base (like we have done for the regex inspection base).
```latex
We see that $Ω Ω\neq\emptyset$
\end{document}
```
> Add \ohm to autocomplete, fixes #3916

- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/packages/LatexPackageNotInstalledInspection.kt
> Avoid NPE in LatexPackageNotInstalledInspection

- CHANGELOG.md
- gradle.properties
- src/nl/hannahsten/texifyidea/run/compiler/LatexCompiler.kt
- src/nl/hannahsten/texifyidea/run/latex/LatexCommandLineState.kt
Only select source roots of current module to fix #3956, and improve error message in case the compile command is too long.
> Fix "The filename or extension is too long"

- Writerside/topics/Inspections.md
- Writerside/topics/TeXiFy-settings.md
- src/nl/hannahsten/texifyidea/inspections/LatexSpellcheckingStrategy.kt
- src/nl/hannahsten/texifyidea/settings/TexifyConfigurable.kt
- src/nl/hannahsten/texifyidea/settings/TexifySettings.kt
- src/nl/hannahsten/texifyidea/settings/TexifySettingsState.kt
Fix #3954
* 'code' is on by default, but I think it should be off for e.g. package names, citations (often containing names)
* Allow overriding the default via a TeXiFy setting
> Add setting to enable spellcheck in all code

- CHANGELOG.md
- resources/META-INF/extensions/references-refactoring.xml
- src/nl/hannahsten/texifyidea/refactoring/BibtexNamesValidator.kt
> Fix validation when renaming a bibtex identifier

- src/nl/hannahsten/texifyidea/inspections/TexifyInspectionBase.kt
- src/nl/hannahsten/texifyidea/inspections/TexifyRegexInspection.kt
- src/nl/hannahsten/texifyidea/inspections/bibtex/BibtexDuplicateBibliographyInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/codematurity/LatexPrimitiveEquationInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/codestyle/LatexEquationReferenceInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/codestyle/LatexMathFunctionTextInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/typesetting/LatexCiteBeforePeriodInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/typesetting/LatexCollapseCiteInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/typesetting/LatexEnDashInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/typesetting/LatexEncloseWithLeftRightInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/typesetting/spacing/LatexSpaceAfterAbbreviationInspection.kt
- test/nl/hannahsten/texifyidea/inspections/TexifyRegexInspectionTest.kt
* Fixed [Field blocks intention preview](https://www.jetbrains.com/help/inspectopedia/ActionIsNotPreviewFriendly.html) warnings reported by Qodana for single inspections.
Check that the quick fixes have the correct preview.
```latex
test e.g. terq
\[
aaa (qe'\frac{4}{3} \text{cos}) x = 3
\]
bla \cite{test}~\cite{two}
\end{document}
```
> Fix qodana warnings about blocked intention preview

- CHANGELOG.md
- gradle.properties
- src/nl/hannahsten/texifyidea/psi/impl/LatexCommandsImplMixin.kt
- src/nl/hannahsten/texifyidea/reference/InputFileReference.kt
- src/nl/hannahsten/texifyidea/settings/sdk/LatexProjectSdkSetupValidator.kt
- src/nl/hannahsten/texifyidea/util/files/FileSet.kt
- src/nl/hannahsten/texifyidea/util/files/ImportPackage.kt
- src/nl/hannahsten/texifyidea/util/files/LatexPackageLocationCache.kt
- src/nl/hannahsten/texifyidea/util/files/PsiFile.kt
- src/nl/hannahsten/texifyidea/util/files/ReferencedFileSetCache.kt
If there are a few hundred root files, the refresh could take 30 seconds, now it only takes a few seconds.
> Improve performance of file set cache refresh

- src/nl/hannahsten/texifyidea/completion/handlers/LatexMathInsertHandler.kt
- src/nl/hannahsten/texifyidea/completion/handlers/LatexNoMathInsertHandler.kt
Fix #4051
- Add calling `removeWhiteSpaces`  also in `LatexMathInsertHandler`.
After inspecting the codes, it seems that the extra spaces are introduced because `LatexMathInsertHandler` does not remove the placeholder spaces inserted by the lookup text, but `LatexNoMathInsertHandler` does it correctly by calling `removeWhiteSpaces` at the first place. 
Therefore, the issue is resolved by calling `removeWhiteSpaces`  also in `LatexMathInsertHandler`.
> Fix extra whitespace when inserting commands in math mode

- CHANGELOG.md
- gradle.properties
- src/nl/hannahsten/texifyidea/documentation/LatexDocumentationProvider.kt
- src/nl/hannahsten/texifyidea/editor/typedhandlers/LatexEnterHandler.kt
- src/nl/hannahsten/texifyidea/formatting/LatexBlock.kt
- src/nl/hannahsten/texifyidea/inspections/latex/codestyle/LatexDocumentclassNotInRootInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/codestyle/LatexTooLargeSectionInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexMissingDocumentEnvironmentInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/packages/LatexPackageNameDoesNotMatchFileNameInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/packages/LatexPackageSubdirectoryInspection.kt
- src/nl/hannahsten/texifyidea/inspections/latex/typesetting/LatexQedHereInspection.kt
- src/nl/hannahsten/texifyidea/lang/DefaultEnvironment.kt
- src/nl/hannahsten/texifyidea/lang/LatexPackage.kt
- src/nl/hannahsten/texifyidea/lang/commands/LatexGenericRegularCommand.kt
- src/nl/hannahsten/texifyidea/util/Commands.kt
- src/nl/hannahsten/texifyidea/util/parser/LatexPsiUtil.kt
Before, when asking for documentation for e.g. a command, it would reset the lookup item but only do it once, so if you then asked for docs on another command it would show docs for the first one. Setting the lookup item should only be done when viewing documentation during autocompletion.
> Fix documentation popup showing obsolete information

- CHANGELOG.md
- src/nl/hannahsten/texifyidea/action/wizard/graphic/InsertGraphicWizardAction.kt
Fix #4108
Backslashes are never valid I think, always replace them.
> Always use forward slashes for inserted path in InsertGraphicWizardAction

- src/nl/hannahsten/texifyidea/run/compiler/LatexCompiler.kt
- src/nl/hannahsten/texifyidea/run/latex/LatexOutputPath.kt
- src/nl/hannahsten/texifyidea/run/latex/LatexRunConfiguration.kt
- src/nl/hannahsten/texifyidea/run/latex/ui/LatexSettingsEditor.kt
- test/nl/hannahsten/texifyidea/run/LatexOutputPathTest.kt
- test/nl/hannahsten/texifyidea/run/LatexRunConfigurationTest.kt
Similar to #4131 I encountered a UI freeze, and found one more read action. However this one is actually needed, so I set the main file in the background and hope that works.
> Make read action in LatexRunConfiguration smart

- build.gradle.kts
I found that when compiling the project with a higher version of the JDK, the compilation would fail due to a mismatch between the Java version and the Kotlin JDK target. Therefore, I made some changes to build.gradle.kts. Below is the original commit message:
- **Updated Java version**: Changed `JavaVersion.VERSION_21` to `JavaVersion.toVersion("21")`.
- **Added Kotlin JVM target**: Introduced a variable `kotlinJvmTarget` using `JvmTarget.fromTarget("21")`.
- **Set JVM targets in Kotlin tasks**: Applied the new Kotlin JVM target to compileKotlin and compileTestKotlin tasks.
This refactoring ensures consistency across Java and Kotlin source versions, improving build compatibility and performance.
Fix #
* 
```latex
```
> robustness improvement, refactor Java and Kotlin source compatibility versions

- CHANGELOG.md
- build.gradle.kts
- src/nl/hannahsten/texifyidea/inspections/latex/typesetting/LatexMissingGlossaryReferenceInspection.kt
- test/nl/hannahsten/texifyidea/inspections/latex/typesetting/LatexMissingGlossaryReferenceInspectionTest.kt
Fix #4201
Seems unnecessary to create a separate inspection as glossaries also provides acronyms in the same way.
> Correct quickfix for missing acronym reference for acronym package

- src/nl/hannahsten/texifyidea/editor/autocompile/AutoCompileVfsListener.kt
Since staging is performed via virtual files, it can trigger auto-compilation, which is incorrect as no files on disk actually change. This commit filters out non-physical files to ensure that compilation is performed only when necessary.
Fixes #4235
> Do not trigger auto-compilation when non-physical files are saved
