src/nl/rubensten/texifyidea/run/LatexCommandLineState.java
src/nl/rubensten/texifyidea/run/LatexCompiler.java
src/nl/rubensten/texifyidea/run/LatexConfigurationFactory.java
src/nl/rubensten/texifyidea/run/LatexRunConfiguration.java
src/nl/rubensten/texifyidea/run/LatexRunConfigurationType.java
src/nl/rubensten/texifyidea/run/LatexSettingsEditor.java

Saving a LaTeX run configuration now properly saves the run configuration and without exceptions.
Also added some refactoring to make it more readable.

Fixed LaTeX run configuration save error.

---

resources/META-INF/plugin.xml
src/nl/rubensten/texifyidea/LatexColorSettingsPage.java
src/nl/rubensten/texifyidea/LatexSyntaxHighlighter.java
src/nl/rubensten/texifyidea/highlighting/LatexAnnotator.java
src/nl/rubensten/texifyidea/highlighting/LatexColorSettingsPage.java
src/nl/rubensten/texifyidea/highlighting/LatexSyntaxHighlighter.java
src/nl/rubensten/texifyidea/highlighting/LatexSyntaxHighlighterFactory.java

Added syntax highlighting support for:
- Braces
- Brackets
- Commands in display math mode
- Commands in inline math mode
- Display math
- Inline math
- Optional parameters
- Stars

Added support for more advanced syntax highlighting.

---

src/nl/rubensten/texifyidea/lang/CommandManager.java
test/nl/rubensten/texifyidea/lang/CommandManagerTest.java

See JavaDocs. Seriously. 
Also includes unit tests.

Added command manager

---

src/nl/rubensten/texifyidea/TeXception.java
src/nl/rubensten/texifyidea/modules/LatexModuleBuilder.java
src/nl/rubensten/texifyidea/templates/LatexTemplatesFactory.java

* main.tex files that get created after making a new module/project now get the tex-file template as default text (#27).
* After creating a new module the file system gets refreshed so main.tex actually shows up immediately.

Main tex-file of new modules gets filled with the tex-fileTemplate

---

README.md

added build instructions for building from source

---

gen/nl/rubensten/texifyidea/parser/LatexParser.java
src/nl/rubensten/texifyidea/grammar/Latex.bnf

Fixed bracket syntax error inside mathmode

---

resources/META-INF/plugin.xml
src/nl/rubensten/texifyidea/completion/LatexCharFilter.java
src/nl/rubensten/texifyidea/highlighting/LatexPairedBraceMatcher.java

Fixes #36. See issue thread for more details.

Enabled TypedHandler for `$` completion on closing completion

---

gen/nl/rubensten/texifyidea/grammar/LatexLexer.java
gen/nl/rubensten/texifyidea/parser/LatexParser.java
gen/nl/rubensten/texifyidea/psi/LatexEnvironmentContent.java
gen/nl/rubensten/texifyidea/psi/LatexNoMathContent.java
gen/nl/rubensten/texifyidea/psi/LatexNormalText.java
gen/nl/rubensten/texifyidea/psi/LatexTypes.java
gen/nl/rubensten/texifyidea/psi/LatexVisitor.java
gen/nl/rubensten/texifyidea/psi/impl/LatexEnvironmentContentImpl.java
gen/nl/rubensten/texifyidea/psi/impl/LatexNoMathContentImpl.java
gen/nl/rubensten/texifyidea/psi/impl/LatexNormalTextImpl.java
resources/liveTemplates/hidden/LaTeX.xml
src/nl/rubensten/texifyidea/folding/LatexEnvironmentFoldingBuilder.java
src/nl/rubensten/texifyidea/formatting/LatexBlock.java
src/nl/rubensten/texifyidea/formatting/LatexFormattingModelBuilder.java
src/nl/rubensten/texifyidea/grammar/Latex.bnf
src/nl/rubensten/texifyidea/grammar/LatexLexer.flex

Fixes #24 and #23.
Somewhat incompatible grammar changes:
- normal_text is a virtual token type. It is a nonempty collection of normal_text_word
- normal_text_word is recognized by the lexer. This basically is the old normal_text, but with all whitespace removed.
- environments do not have a flat list of content anymore, but an nonempty and optional environment_content which holds the list.

Fixed formatter

---

src/nl/rubensten/texifyidea/completion/LatexCommandProvider.java
src/nl/rubensten/texifyidea/completion/LatexReferenceProvider.java
src/nl/rubensten/texifyidea/gutter/LatexNavigationGutter.java
src/nl/rubensten/texifyidea/run/LatexCommandLineState.java
src/nl/rubensten/texifyidea/run/LatexCompiler.java
src/nl/rubensten/texifyidea/run/LatexRunConfiguration.java
src/nl/rubensten/texifyidea/structure/LatexStructureViewCommandElement.java
src/nl/rubensten/texifyidea/util/TexifyUtil.java

And some other checks to prevent exceptions as reported in #60.
This resolves #60.

Added null checks to prevent NPEs

---

src/nl/rubensten/texifyidea/run/LatexCommandLineState.java
src/nl/rubensten/texifyidea/util/TexifyUtil.java

Fixes #70.
Creates output folders (including subfolders for included aux files) before compilation.

Create out folders before compilation

---

gen/nl/rubensten/texifyidea/parser/LatexParser.java
gen/nl/rubensten/texifyidea/psi/LatexDisplayMath.java
gen/nl/rubensten/texifyidea/psi/LatexMathContent.java
gen/nl/rubensten/texifyidea/psi/LatexTypes.java
gen/nl/rubensten/texifyidea/psi/LatexVisitor.java
gen/nl/rubensten/texifyidea/psi/impl/LatexDisplayMathImpl.java
gen/nl/rubensten/texifyidea/psi/impl/LatexInlineMathImpl.java
gen/nl/rubensten/texifyidea/psi/impl/LatexMathContentImpl.java
src/nl/rubensten/texifyidea/formatting/LatexBlock.java
src/nl/rubensten/texifyidea/grammar/Latex.bnf
src/nl/rubensten/texifyidea/psi/LatexPsiUtil.java

Formatter fixes

---

src/nl/rubensten/texifyidea/completion/LatexCommandProvider.java
src/nl/rubensten/texifyidea/util/TexifyUtil.java

* Defined command lookup for auto complete now works backwards too (see illustration). Resolves #86.

Fixed autocomplete not working backward.

---

src/nl/rubensten/texifyidea/lang/LatexMathCommand.java

* Added null check to fix #96.

Fixed #96 (added null check).

---

resources/META-INF/plugin.xml
src/nl/rubensten/texifyidea/TexifyIcons.java
src/nl/rubensten/texifyidea/action/analysis/WordCountAction.kt
src/nl/rubensten/texifyidea/action/group/AnalysisActionGroup.kt
src/nl/rubensten/texifyidea/action/group/InsertFontStyleActionGroup.java
src/nl/rubensten/texifyidea/action/group/InsertFontStyleActionGroup.kt
src/nl/rubensten/texifyidea/action/group/InsertSectioningActionGroup.java
src/nl/rubensten/texifyidea/action/group/InsertSectioningActionGroup.kt
src/nl/rubensten/texifyidea/action/group/SumatraActionGroup.java
src/nl/rubensten/texifyidea/action/sumatra/ConfigureInverseSearchAction.kt
src/nl/rubensten/texifyidea/action/sumatra/ForwardSearchAction.kt
src/nl/rubensten/texifyidea/util/FileUtil.kt
src/nl/rubensten/texifyidea/util/GeneralUtil.kt
src/nl/rubensten/texifyidea/util/PsiUtil.kt

- Added word count action. Performs roughly within a 1-3% error margin compared to PDF output and LibreOffice (in my test cases). Word count takes contractions into account and ignores bibliographies. Counts words in all included files.
- Added icons to LaTeX menu groups.
- Added a few Psi utility/extension functions

Word count

---

README.md

Cool little gitter button.

---

src/nl/rubensten/texifyidea/algorithm/IsChildDFS.kt
src/nl/rubensten/texifyidea/completion/LatexFileProvider.java
src/nl/rubensten/texifyidea/gutter/LatexNavigationGutter.java
src/nl/rubensten/texifyidea/util/FileUtil.kt
src/nl/rubensten/texifyidea/util/TexifyUtil.java

- Fixes #117.
- Applies to the navigation gutter and all file-inclusion related functionality.

Fixed file inclusion checking not being done from inclusion root.

---

src/nl/rubensten/texifyidea/gutter/LatexNavigationGutter.java
src/nl/rubensten/texifyidea/run/LatexCompiler.java
src/nl/rubensten/texifyidea/util/TexifyUtil.java

- Added support for different source roots (like resource folders). (#42)
- This goes for autocomplete/labels/compilation with pdflatex etc.

Added support for multiple content roots.

---

src/nl/rubensten/texifyidea/highlighting/LatexAnnotator.kt
src/nl/rubensten/texifyidea/util/PsiUtil.kt

Fixed #176: Some commands not being highlighted in math mode.

---

src/nl/rubensten/texifyidea/completion/LatexCompletionContributor.kt
src/nl/rubensten/texifyidea/highlighting/LatexAnnotator.kt

Fixed autocomplete not showing up in foreign environments.

---

src/nl/rubensten/texifyidea/util/PsiUtil.kt

Fixed #190: Gather not working with environments

---

src/nl/rubensten/texifyidea/editor/InsertEnumerationItem.kt
src/nl/rubensten/texifyidea/util/PsiUtil.kt

Fixed #215: Disabled insertion of \item in math context.

---

src/nl/rubensten/texifyidea/util/TexifyUtil.java

Fixed #219: Files not found where name==extension.

---

src/nl/rubensten/texifyidea/inspections/latex/LatexTooLargeSectionInspection.kt

Part of code is duplicate so I could just copy from #203. In time for b0.5 :)

Copied fix for 'section to file' filename from intention to quickfix

---

src/nl/rubensten/texifyidea/editor/UpDownAutoBracket.kt

- Added 1 character. See title.

Sub/Superscript braces don't get automatically inserted before '('

---

resources/META-INF/plugin.xml
resources/inspectionDescriptions/LatexNestedIncludes.html
src/nl/rubensten/texifyidea/inspections/latex/LatexNestedIncludesInspection.kt

Inspection that signals nested \include commands

---

src/nl/rubensten/texifyidea/run/BibtexRunConfiguration.kt
src/nl/rubensten/texifyidea/run/BibtexSettingsEditor.kt
src/nl/rubensten/texifyidea/run/LatexCompiler.java
src/nl/rubensten/texifyidea/run/LatexRunConfiguration.java
src/nl/rubensten/texifyidea/run/LatexSettingsEditor.java
src/nl/rubensten/texifyidea/run/compiler/BibtexCompiler.kt

- Custom compiler arguments field in LaTeX run configuration settings.
- Same for BibTeX run configurations.
Resolves #225 (support for magic comments will be added later)

Compiler arguments

---

src/nl/rubensten/texifyidea/inspections/latex/LatexDuplicateLabelInspection.kt

See title. Fixes #237.
Example behavior:
and

No more duplicate label crosscheck for \label and \bibitem

---

resources/META-INF/plugin.xml
src/nl/rubensten/texifyidea/components/TexifyProjectComponent.kt
src/nl/rubensten/texifyidea/editor/LatexSoftWrapEditorListener.kt
src/nl/rubensten/texifyidea/settings/TexifyConfigurable.kt
src/nl/rubensten/texifyidea/settings/TexifySettings.kt
src/nl/rubensten/texifyidea/util/FileUtil.kt

Adds an option in global settings to automatically enable soft wraps when opening a LaTeX file. Resolves #243.
Note that this option is _disabled_ by default.

Automatic soft wrap on file open

---

.github/CODEOWNERS
.github/CODE_OF_CONDUCT.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

Public repository management with (mostly) community guidelines
- `CODEOWNERS` file for automatic reviews for pull requests.
- Contributing guidelines
- Code of Conduct
- Issue template
- Pull request template

WIP: Repository management

---

src/nl/rubensten/texifyidea/gutter/LatexLineMarkerProvider.kt
src/nl/rubensten/texifyidea/highlighting/LatexTypedHandler.java
src/nl/rubensten/texifyidea/run/OpenSumatraListener.kt
src/nl/rubensten/texifyidea/run/RunBibtexListener.kt
src/nl/rubensten/texifyidea/settings/TexifyConfigurable.kt
src/nl/rubensten/texifyidea/settings/TexifySettings.kt

- Resolves #275 
- Pair quotes will now only get inserted in BibTeX files. Forgot to include that check earlier.
- Added setting to disable automatically inserting $ for inline math.

Disable/enable auto insertion of '$' and fix double quote insertion

---

README.md

Add a standard document structure example to the FAQ. [Point](https://github.com/PHPirates/TeXiFy-IDEA/tree/FAQ-document-structure#FAQ) to it with `https://github.com/Ruben-Sten/TeXiFy-IDEA#FAQ` .

Add a standard document structure example to the FAQ.

---

src/nl/rubensten/texifyidea/util/GeneralUtil.kt

Added null check in `GeneralUntil.kt:83`. Fixes #279 
Don't know if all these null checks are intended but works for me.

fixed #279 with null check

---

src/nl/rubensten/texifyidea/reference/LatexLabelReference.java

None.
Hello! 
Was writing my thesis today and encountered an error:
```Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(ArrayList.java:653)
at java.util.ArrayList.get(ArrayList.java:429)
at nl.rubensten.texifyidea.reference.LatexLabelReference.lambda$getVariants$2(LatexLabelReference.java:83)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1376)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
at …
```

Array out of bounds exception

---

src/nl/rubensten/texifyidea/inspections/latex/LatexMissingImportInspection.kt
src/nl/rubensten/texifyidea/lang/LatexMathCommand.kt
src/nl/rubensten/texifyidea/lang/Package.kt

I hardcoded the fact that amsfonts is included in amssymb, and mathtools included in amsmath. Didn't encounter similar issues since this was reported.

Package requirements fix

---

README.md

Tested all instructions once again, now on Arch :) 
(Which means I'll soon be able to test the other PR)

Update linux instructions

---

README.md

See discussion in gitter and #767 where I had this issue.

Update faq with corrupt cache fix

---

src/nl/rubensten/texifyidea/inspections/latex/LatexGroupedSubSupScriptInspection.kt
test/nl/rubensten/texifyidea/inspections/latex/LatexGroupedSubSupScriptInspectionTest.kt
test/nl/rubensten/texifyidea/inspections/latex/TexifyRegexInspectionTestBase.kt

Fixes #794. Also added a little unit test & base class for future regex tests.
* Addresses the superscript/subscript edge cases as described in #794. Only fixes these cases for now.

Fixed several wrong triggers of Grouped Sub sup Script inspection.

---

src/nl/rubensten/texifyidea/folding/LatexSectionFoldingBuilder.kt

I hope it fixes #839 and fixes #843, at least the negative text range should not occur anymore here. 
I do not know how it is possible to get a negative text range, but from the issues it seems like it has something to do with having a `$` too few or too many in the document, i.e. having an invalid latex document, so I will assume that if the folding temporarily breaks while the document cannot be parsed that will not be a problem.

Skip negative text ranges when adding folding sections

---

resources/nl/rubensten/texifyidea/icons/tikz-file.svg
src/nl/rubensten/texifyidea/TexifyIcons.java
src/nl/rubensten/texifyidea/action/NewLatexFileAction.java
src/nl/rubensten/texifyidea/file/TikzFileType.kt
src/nl/rubensten/texifyidea/templates/LatexTemplatesFactory.kt
src/nl/rubensten/texifyidea/util/Magic.kt

- Added seperate icon for TikZ files. Long overdue :P Decided on 'TiZ', As 'TikZ' is too much and 'TkZ' looks odd.

Added icon for TikZ files.

---

resources/META-INF/plugin.xml
src/nl/rubensten/texifyidea/action/ClearAuxFiles.kt
src/nl/rubensten/texifyidea/util/Magic.kt

Added menu item to clear the auxiliary files

---

src/nl/rubensten/texifyidea/completion/LatexCharFilter.java
src/nl/rubensten/texifyidea/util/Log.kt

Closes #835.
Modify [LatexCharFilter](src/nl/rubensten/texifyidea/completion/LatexCharFilter.java) so that it forces the completion to continue if a colon is typed in.

Fix completion on a colon

---

resources/META-INF/plugin.xml
resources/inspectionDescriptions/LatexFigureNotReferenced.html
src/nl/rubensten/texifyidea/inspections/latex/LatexFigureNotReferencedInspection.kt
src/nl/rubensten/texifyidea/util/Magic.kt

An inspection checking for figure labels that are not anywhere referenced (#875)
_PS. That is my first inspection, so I probably have missed some better way to implement it._

Add figure not referenced inspection

---

README.md

Add jetbrains plugin version badge

---

src/nl/hannahsten/texifyidea/run/latex/LatexCommandLineState.kt

Open pdf viewer when no extra compiles are needed

---

resources/META-INF/plugin.xml
src/nl/hannahsten/texifyidea/run/latex/ui/LatexSettingsEditor.kt

Default to pdflatex when no compiler is chosen

---

resources/META-INF/plugin.xml
src/nl/hannahsten/texifyidea/inspections/latex/LatexFigureNotReferencedInspection.kt
src/nl/hannahsten/texifyidea/run/latex/ui/LatexSettingsEditor.kt

Find labels in file set for figure not referenced inspection

---

src/nl/hannahsten/texifyidea/inspections/latex/LatexDuplicateLabelInspection.kt
src/nl/hannahsten/texifyidea/util/Labels.kt

LatexDuplicatedLabelInspection findLabels crash

---

src/nl/hannahsten/texifyidea/inspections/latex/LatexUnicodeInspection.kt

Open correct settings page for compiler compatibility quickfix

---

resources/META-INF/plugin.xml
src/nl/hannahsten/texifyidea/run/compiler/LatexCompiler.kt
src/nl/hannahsten/texifyidea/run/compiler/MakeindexProgram.kt
src/nl/hannahsten/texifyidea/run/latex/LatexCommandLineState.kt
src/nl/hannahsten/texifyidea/run/latex/LatexRunConfiguration.kt
src/nl/hannahsten/texifyidea/run/latex/ui/LatexSettingsEditor.kt
src/nl/hannahsten/texifyidea/run/latex/ui/RunConfigurationPanel.kt
src/nl/hannahsten/texifyidea/run/makeindex/MakeindexCommandLineState.kt
src/nl/hannahsten/texifyidea/run/makeindex/MakeindexRunConfiguration.kt
src/nl/hannahsten/texifyidea/run/makeindex/MakeindexSettingsEditor.kt
src/nl/hannahsten/texifyidea/run/makeindex/RunMakeindexListener.kt
src/nl/hannahsten/texifyidea/util/Packages.kt

Fixes #1096 
Fixes #1115 
- Support xindy
- Support different index name
- Add settings page and link to main run config in the same was as bibtex
MWE and docs at https://github.com/Hannah-Sten/TeXiFy-IDEA/wiki/Makeindex

Support imakeidx options

---

build.gradle
resources/META-INF/plugin.xml

Release is uploaded to the plugin repo.

Changenotes 0.6.7

---

.github/ISSUE_TEMPLATE.md
src/nl/hannahsten/texifyidea/action/sumatra/ConfigureInverseSearchAction.kt

Kill Sumatra before starting with new inverse search command

---

resources/META-INF/plugin.xml
src/nl/hannahsten/texifyidea/folding/BibtexEntryFoldingBuilder.kt
src/nl/hannahsten/texifyidea/folding/LatexEnvironmentFoldingBuilder.kt
src/nl/hannahsten/texifyidea/folding/LatexSectionFoldingBuilder.kt

Add folding for bibtex entries

---

gen/nl/hannahsten/texifyidea/parser/LatexParser.java
gen/nl/hannahsten/texifyidea/psi/LatexEnvironment.java
gen/nl/hannahsten/texifyidea/psi/LatexInlineMath.java
gen/nl/hannahsten/texifyidea/psi/impl/LatexEnvironmentImpl.java
gen/nl/hannahsten/texifyidea/psi/impl/LatexInlineMathImpl.java
src/nl/hannahsten/texifyidea/folding/LatexEnvironmentFoldingBuilder.kt
src/nl/hannahsten/texifyidea/grammar/Latex.bnf
src/nl/hannahsten/texifyidea/highlighting/LatexAnnotator.kt
src/nl/hannahsten/texifyidea/intentions/LatexInlineDisplayToggle.kt

See #1157 
I haven't found any problems with these pins, but it should be tested carefully.

Re-add LaTeX parser pins

---

src/nl/hannahsten/texifyidea/inspections/Inspections.kt

Forgot one deprecated call

---

src/nl/hannahsten/texifyidea/run/linuxpdfviewer/PdfViewer.kt
src/nl/hannahsten/texifyidea/run/linuxpdfviewer/ViewerConversation.kt
src/nl/hannahsten/texifyidea/run/linuxpdfviewer/evince/EvinceInverseSearchListener.kt
src/nl/hannahsten/texifyidea/startup/StartEvinceInverseSearchListener.kt
src/nl/hannahsten/texifyidea/util/Strings.kt

Fixes #1133
* Add check for Evince 3
* Check you can still use Evince

Add evince version check

---

.travis.yml
README.md
build.gradle
codecov.yml

[![codecov](https://img.shields.io/codecov/c/github/Hannah-Sten/TeXiFy-IDEA/coverage?style=flat-square)](https://codecov.io/gh/Hannah-Sten/TeXiFy-IDEA)

Add coverage report

---

resources/META-INF/plugin.xml
src/nl/hannahsten/texifyidea/documentation/LatexDocumentationProvider.kt
src/nl/hannahsten/texifyidea/refactoring/LatexNameSuggestionProvider.kt

Fixes leftover of #1264
* Provide suggestions when refactoring an environment.
* Refactor an environment and use the suggestions.

Suggest environment names when refactoring an environment

---

src/nl/hannahsten/texifyidea/inspections/latex/LatexAbsolutePathInspection.kt

Fixes #1294

---

src/nl/hannahsten/texifyidea/editor/autocompile/AutoCompileState.kt

Show warning if no valid run config was selected

---

.github/workflows/main.yml
src/nl/hannahsten/texifyidea/highlighting/LatexTypedHandler.kt

Redo #1323

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md

Add link to wiki to feature request issue template

Update issue templates

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
src/nl/hannahsten/texifyidea/util/Magic.kt

Add renewcommand/providecommand as command definitions

---

src/nl/hannahsten/texifyidea/LatexParserDefinition.java

Increase stub version

---

src/nl/hannahsten/texifyidea/inspections/latex/LatexEscapeHashOutsideCommandInspection.kt
src/nl/hannahsten/texifyidea/util/PsiCommands.kt
test/nl/hannahsten/texifyidea/inspections/TexifyInspectionTriggerTestBase.kt
test/nl/hannahsten/texifyidea/inspections/latex/TexifyRegexInspectionTestBase.kt
test/nl/hannahsten/texifyidea/inspections/latex/UnescapedHashInspectionTest.kt

Unescaped hash symbol inspection was uncorrectly triggered

---

build.gradle
src/nl/hannahsten/texifyidea/inspections/latex/LatexPackageNotInstalledInspection.kt

Don't use code unavailable in non-Java IDEAs

---

src/nl/hannahsten/texifyidea/run/bibtex/BibtexSettingsEditor.kt

Make bibtex working dir configurable via UI

---

src/nl/hannahsten/texifyidea/ui/PreviewFormUpdater.kt
src/nl/hannahsten/texifyidea/util/Strings.kt

Somehow we didn't notice that the display math equation preview was broken by https://github.com/Hannah-Sten/TeXiFy-IDEA/pull/1398/commits/a3e271da06814b696044e47abd73edac524afeb1...

Fix display math equation preview

---

src/nl/hannahsten/texifyidea/inspections/latex/LatexNonBreakingSpaceInspection.kt
src/nl/hannahsten/texifyidea/lang/LatexRegularCommand.kt
src/nl/hannahsten/texifyidea/util/Magic.kt
test/nl/hannahsten/texifyidea/inspections/latex/LatexNonBreakingSpaceInspectionTest.kt

* Fixed non-breaking space inspection 
* Added tests for non-breaking space inspection
```latex
abc \dummy{Reference~\ref{fig}}
```

Non breaking space

---

src/nl/hannahsten/texifyidea/psi/LatexCommandsImplUtil.kt

Special characters in structure view

---

src/nl/hannahsten/texifyidea/lang/LatexRegularCommand.kt
src/nl/hannahsten/texifyidea/lang/Package.kt

Add SIunitx commands to autocompletion

---

build.gradle
src/nl/hannahsten/texifyidea/inspections/latex/LatexMissingImportInspection.kt
src/nl/hannahsten/texifyidea/lang/CommandManager.kt
src/nl/hannahsten/texifyidea/lang/LatexRegularCommand.kt
src/nl/hannahsten/texifyidea/util/Magic.kt

Rerun inspections after adding an include command, and fix concurrency crash

---

build.gradle
src/nl/hannahsten/texifyidea/lang/CommandManager.kt
src/nl/hannahsten/texifyidea/util/files/RootFile.kt

Use correct index for command definitions, fixes a UI freeze

---

src/nl/hannahsten/texifyidea/completion/LatexCommandProvider.kt
src/nl/hannahsten/texifyidea/inspections/latex/LatexMissingImportInspection.kt
src/nl/hannahsten/texifyidea/run/OpenCustomPdfViewerListener.kt

Fix #1557
Fix #1571 
Fix #1573

Improve error message, fix IOOB and remove a workaround

---

build.gradle
src/nl/hannahsten/texifyidea/run/latex/logtab/LatexFileStack.kt
src/nl/hannahsten/texifyidea/run/latex/logtab/LatexLogMagicRegex.kt
src/nl/hannahsten/texifyidea/run/latex/logtab/LatexLogMessageExtractor.kt
src/nl/hannahsten/texifyidea/util/Strings.kt
test/nl/hannahsten/texifyidea/run/LatexLogFileFinderTest.kt
test/nl/hannahsten/texifyidea/run/LatexOutputListenerTest.kt

Fix some parentheses issues in log parsing

---

src/nl/hannahsten/texifyidea/formatting/BibtexSpacingRules.kt
test/nl/hannahsten/texifyidea/formatting/BibtexFormattingTest.kt

Basically ignore braces in text.

Fix bibtex formatting braces

---

build.gradle.kts
src/nl/hannahsten/texifyidea/index/stub/BibtexEntryStubElementType.kt
src/nl/hannahsten/texifyidea/index/stub/LatexEnvironmentStubElementType.kt
src/nl/hannahsten/texifyidea/run/latex/LatexRunConfiguration.kt
src/nl/hannahsten/texifyidea/run/latex/logtab/LatexFileStack.kt
src/nl/hannahsten/texifyidea/run/latex/logtab/messagehandlers/errors/LatexUndefinedControlSequenceHandler.kt
src/nl/hannahsten/texifyidea/structure/latex/LatexStructureViewModel.kt
test/nl/hannahsten/texifyidea/run/logtab/LatexLogFileFinderTest.kt
test/nl/hannahsten/texifyidea/run/logtab/LatexOutputListenerTest.kt

Fix #1610 
* Fix crash psi change listener
* Fix opening parentheses not being counted when before files (logtab)
* Fix command missing for undefined control sequence (logtab)
* Fix sync from source for structure view

Sync from source for structure view, log parsing improvements

---

src/nl/hannahsten/texifyidea/util/Strings.kt
test/nl/hannahsten/texifyidea/intentions/LatexAddLabelIntentionTest.kt

Fix #1618
* Added test to show failing behaviour
* formatAsLabel() now removes comma
A test is included in the PR

Fixes label creation with commas

---

src/nl/hannahsten/texifyidea/run/linuxpdfviewer/okular/OkularConversation.kt

Fix Okular grabbing focus all the time

---

src/nl/hannahsten/texifyidea/editor/LatexQuoteInsertHandler.kt
src/nl/hannahsten/texifyidea/intentions/LatexLanguageInjectionIntention.kt
test/nl/hannahsten/texifyidea/editor/LatexQuoteInsertHandlerTest.kt

Fix NPE language injection and smart quote substitution

---

build.gradle.kts
src/nl/hannahsten/texifyidea/inspections/latex/LatexUnicodeInspection.kt
src/nl/hannahsten/texifyidea/lang/DefaultEnvironment.kt
src/nl/hannahsten/texifyidea/run/latex/LatexOutputPath.kt
src/nl/hannahsten/texifyidea/settings/TexifyConfigurable.kt
src/nl/hannahsten/texifyidea/settings/sdk/NativeTexliveSdk.kt
src/nl/hannahsten/texifyidea/ui/PreviewFormUpdater.kt
test/nl/hannahsten/texifyidea/inspections/latex/LatexUnicodeInspectionTest.kt

Fix lateinit exception and remove obsolete unicode quickfix

---

gen/nl/hannahsten/texifyidea/parser/LatexParser.java
gen/nl/hannahsten/texifyidea/psi/LatexGroup.java
gen/nl/hannahsten/texifyidea/psi/LatexKeyvalValue.java
gen/nl/hannahsten/texifyidea/psi/LatexParameter.java
gen/nl/hannahsten/texifyidea/psi/LatexParameterGroup.java
gen/nl/hannahsten/texifyidea/psi/LatexParameterGroupText.java
gen/nl/hannahsten/texifyidea/psi/LatexPictureParam.java
gen/nl/hannahsten/texifyidea/psi/LatexPictureParamContent.java
gen/nl/hannahsten/texifyidea/psi/LatexRequiredParamContent.java
gen/nl/hannahsten/texifyidea/psi/LatexTypes.java
gen/nl/hannahsten/texifyidea/psi/LatexVisitor.java
gen/nl/hannahsten/texifyidea/psi/impl/LatexGroupImpl.java
gen/nl/hannahsten/texifyidea/psi/impl/LatexKeyvalContentImpl.java
gen/nl/hannahsten/texifyidea/psi/impl/LatexKeyvalValueImpl.java
gen/nl/hannahsten/texifyidea/psi/impl/LatexParameterGroupTextImpl.java
gen/nl/hannahsten/texifyidea/psi/impl/LatexParameterImpl.java
gen/nl/hannahsten/texifyidea/psi/impl/LatexPictureParamContentImpl.java
gen/nl/hannahsten/texifyidea/psi/impl/LatexPictureParamImpl.java
gen/nl/hannahsten/texifyidea/psi/impl/LatexRequiredParamContentImpl.java
src/nl/hannahsten/texifyidea/LatexParserDefinition.kt
src/nl/hannahsten/texifyidea/formatting/spacingrules/TableAlignRule.kt
src/nl/hannahsten/texifyidea/grammar/Latex.bnf
src/nl/hannahsten/texifyidea/index/LatexCommandsIndex.kt
src/nl/hannahsten/texifyidea/index/LatexDefinitionIndex.kt
src/nl/hannahsten/texifyidea/index/LatexEnvironmentsIndex.kt
src/nl/hannahsten/texifyidea/index/LatexIncludesIndex.kt
src/nl/hannahsten/texifyidea/index/LatexMagicCommentIndex.kt
src/nl/hannahsten/texifyidea/index/LatexParameterLabeledCommandsIndex.kt
src/nl/hannahsten/texifyidea/index/LatexParameterLabeledEnvironmentsIndex.kt

Fix #1712 (picture arguments)
Fix #1720 (IOOB TableAlignRule)
Fix #1721 (stub indexes didn't have a version)

Add picture arguments to parser

---

resources/META-INF/plugin.xml
src/nl/hannahsten/texifyidea/action/ClearGeneratedFiles.kt
src/nl/hannahsten/texifyidea/editor/InlineMathBackspaceHandler.kt
src/nl/hannahsten/texifyidea/editor/autocompile/AutoCompileHandler.kt
src/nl/hannahsten/texifyidea/editor/autocompile/ContinuousPreviewHandler.kt
src/nl/hannahsten/texifyidea/inspections/latex/LatexMathFunctionTextInspection.kt
src/nl/hannahsten/texifyidea/run/latex/LatexRunConfiguration.kt
src/nl/hannahsten/texifyidea/util/Projects.kt
src/nl/hannahsten/texifyidea/util/files/RootFile.kt
test/nl/hannahsten/texifyidea/inspections/latex/LatexMathFunctionTextInspectionTest.kt

* Fix #1726, handle custom output dirs for 'delete generated files' action 
* Fix #1728, deep clone run config 
* Fix #1740, apparently default should be false for charDeleted backspacehandler

Custom out dir generated files, run config clone and backspacehandler

---

src/nl/hannahsten/texifyidea/completion/LatexCompletionContributor.kt
test/nl/hannahsten/texifyidea/completion/LatexEnvironmentCompletionTest.kt

which was started in #1767, but now includes a test.
[TEX-113](https://texify-idea.myjetbrains.com/youtrack/issue/TEX-113)

Finish refactor of completion contributor

---

build.gradle.kts
src/nl/hannahsten/texifyidea/action/ClearGeneratedFiles.kt
src/nl/hannahsten/texifyidea/blame/LatexErrorReportSubmitter.kt
test/nl/hannahsten/texifyidea/util/LatestTexifyVersionTest.kt

Fix [TEX-24](https://texify-idea.myjetbrains.com/youtrack/issue/TEX-24)
* Show popup if current version is less than github release version
* Couldn't find a way to open the settings page immediately, so 'cancel' does nothing at the moment
* When there's no internet connection, skip the check
Change version to something old in gradle build file, make sure to produce an error somewhere and see the popup come up.

Ask to update TeXiFy before trying to submit a bug report for an older version

---

src/nl/hannahsten/texifyidea/action/DeleteGeneratedFiles.kt
src/nl/hannahsten/texifyidea/action/ReformatWithLatexindent.kt
src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexUnicodeInspection.kt
src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/packages/LatexPackageNameDoesNotMatchFileNameInspection.kt

Fix #1960
Fix #1953
Fix #1969
Fix #1975 (IOOB)
* Fix an empty collection exception
* Catch exception and pass it to notification in two cases: when latexindent.pl is not found and when deleting files has permission problems

Change some exceptions to notifications

---

src/nl/hannahsten/texifyidea/editor/ImagePasteProvider.kt
src/nl/hannahsten/texifyidea/file/SaveImageFromClipboardDialog.kt

Clarify which images are supported by image paste provider

---

resources/META-INF/actions/actions.xml

Fix wrong xpointer in plugin.xml

---

build.gradle.kts
src/nl/hannahsten/texifyidea/run/compiler/BiberCompiler.kt
src/nl/hannahsten/texifyidea/run/compiler/BibtexCompiler.kt
src/nl/hannahsten/texifyidea/run/compiler/LatexCompiler.kt

See #1902 but now to be included in 0.7.10 instead of waiting for 0.8.0.
@solonovamax I uploaded it into 0.7.10-alpha.2, should be approved by Jetbrains soon. (Also attached the build)
[TeXiFy-IDEA-0.7.10-alpha.2.zip](https://github.com/Hannah-Sten/TeXiFy-IDEA/files/7078523/TeXiFy-IDEA-0.7.10-alpha.2.zip)

Quoted custom arguments

---

.gitignore
.idea/icon.svg
build.gradle.kts
src/nl/hannahsten/texifyidea/action/preview/JlatexmathPreviewer.kt

Catch jlatexmath exception #2105

---

.github/workflows/main.yml

Needs to be on the master branch.

Enable manual trigger of github workflow

---

src/nl/hannahsten/texifyidea/action/DeleteGeneratedFiles.kt
src/nl/hannahsten/texifyidea/editor/typedhandlers/LatexEnterInCommentHandler.kt
src/nl/hannahsten/texifyidea/util/Strings.kt

Fix #2167 (check if caret/file are valid before using)
Fix #2207 index out of range for capitalizeFirst()
Fix #2204 provide user feedback when some files could not be cleaned up

Fix invalid VirtualFileWindow, IOOB and file cleanup crashes

---

src/nl/hannahsten/texifyidea/gutter/LatexElementColorProvider.kt
src/nl/hannahsten/texifyidea/lang/commands/LatexColorDefinitionCommand.kt
src/nl/hannahsten/texifyidea/lang/commands/LatexGenericRegularCommand.kt
src/nl/hannahsten/texifyidea/lang/commands/LatexRegularCommand.kt
src/nl/hannahsten/texifyidea/lang/commands/LatexXparseCommand.kt

Fix #2142 remove dependency on xparse package
Fix #2161 some commands are provided by the color package, not directly in xcolor

Package dependencies

---

src/nl/hannahsten/texifyidea/lang/DefaultEnvironment.kt
src/nl/hannahsten/texifyidea/lang/LatexPackage.kt
src/nl/hannahsten/texifyidea/util/magic/EnvironmentMagic.kt

Fix #2244
This PR adds the widetabular environment, which is provided by the widetable package.

Add widetable package

---

build.gradle.kts
src/nl/hannahsten/texifyidea/index/IndexUtilBase.kt
src/nl/hannahsten/texifyidea/inspections/bibtex/BibtexUnusedEntryInspection.kt
src/nl/hannahsten/texifyidea/inspections/latex/codestyle/LatexFigureNotReferencedInspection.kt
src/nl/hannahsten/texifyidea/run/linuxpdfviewer/evince/EvinceInverseSearchListener.kt
src/nl/hannahsten/texifyidea/startup/LoadUnloadListener.kt
src/nl/hannahsten/texifyidea/util/SystemEnvironment.kt

Fix #2253 
Fix #2257 
Fix #2260

Fix Evince inverse search coroutine and some NPE

---

src/nl/hannahsten/texifyidea/run/compiler/LatexCompiler.kt
src/nl/hannahsten/texifyidea/run/latex/ui/LatexSettingsEditor.kt

Fix #1742
This is just a quick fix to add it to the compiler list, real support is planned in [TEX-146](https://texify-idea.myjetbrains.com/youtrack/issue/TEX-146)

Add arara to compiler list

---

build.gradle.kts
src/nl/hannahsten/texifyidea/inspections/grazie/LatexTextExtractor.kt
src/nl/hannahsten/texifyidea/util/PsiCommands.kt

Fix #2268, at least I hope it does.
Fix #2287 stealthy ranges

Fix PsiInvalidElementAccessException

---

src/nl/hannahsten/texifyidea/gutter/LatexNavigationGutter.kt
src/nl/hannahsten/texifyidea/run/linuxpdfviewer/evince/EvinceConversation.kt
src/nl/hannahsten/texifyidea/run/sumatra/SumatraConversation.kt
src/nl/hannahsten/texifyidea/util/Log.kt
src/nl/hannahsten/texifyidea/util/SystemEnvironment.kt

Fix #2320 
* Improve and add logging for when system commands error out
I don't know yet how the debug messages can be logged, but I guess it's possible so I added debug messages as well.

Add info logging for executing system commands

---

src/nl/hannahsten/texifyidea/action/reformat/ExternalReformatAction.kt
src/nl/hannahsten/texifyidea/action/reformat/ReformatWithLatexindent.kt

Make latexindent work with Windows

---

src/nl/hannahsten/texifyidea/run/latex/MakeindexUtil.kt
src/nl/hannahsten/texifyidea/run/makeindex/MakeindexCommandLineState.kt

Replace crash by notification for makeindex

---

src/nl/hannahsten/texifyidea/formatting/LatexBlock.kt
src/nl/hannahsten/texifyidea/settings/codestyle/LatexCodeStyleSettings.kt
src/nl/hannahsten/texifyidea/settings/codestyle/LatexIndentOptionsEditor.kt
test/nl/hannahsten/texifyidea/formatting/LatexFormattingTest.kt

Add option to disable indentation of document environment

---

src/nl/hannahsten/texifyidea/run/latex/LatexRunConfiguration.kt

Fix auxilpath macro resolving

---

src/nl/hannahsten/texifyidea/index/IndexUtilBase.kt
src/nl/hannahsten/texifyidea/inspections/latex/codestyle/LatexFigureNotReferencedInspection.kt
src/nl/hannahsten/texifyidea/util/Packages.kt

Fix #2408 Issue with using old psi after reparse
Fix #2411 NPE In LatexFigureNotReferencedInspection
Fix #2434 NPE in Packages

Fixed caching and NPE crashes

---

src/nl/hannahsten/texifyidea/LatexErrorReportSubmitter.kt
src/nl/hannahsten/texifyidea/editor/typedhandlers/InlineMathBackspaceHandler.kt
src/nl/hannahsten/texifyidea/editor/typedhandlers/LatexTypedHandler.kt
src/nl/hannahsten/texifyidea/settings/sdk/MiktexWindowsSdk.kt
src/nl/hannahsten/texifyidea/util/General.kt

Fix #2452 grazie dependency
Fix #2483  IOOB miktex windows sdk
Fix #2468 error report submitter without internet

Remove unnecessary hard dependency on Grazie

---

src/nl/hannahsten/texifyidea/settings/sdk/DockerSdkConfigurable.kt
src/nl/hannahsten/texifyidea/util/Psi.kt
src/nl/hannahsten/texifyidea/util/files/PsiFile.kt

Fix #2499 IOOB
Fix #2493 disposed project
Fix #2494 invalid parent directory

Fix crashes docker sdk / disposed project / invalid parent

---

src/nl/hannahsten/texifyidea/inspections/latex/typesetting/spacing/LatexEllipsisInspection.kt
src/nl/hannahsten/texifyidea/lang/LatexPackage.kt
src/nl/hannahsten/texifyidea/lang/commands/LatexNewDefinitionCommand.kt
src/nl/hannahsten/texifyidea/util/magic/CommandMagic.kt

Fix #2505 ellipsis in tikzpicture
Fix #2501 tcolorbox environment definitions

Fix inspection false positives ellipsis/hash

---

src/nl/hannahsten/texifyidea/run/latex/LatexCommandLineState.kt
src/nl/hannahsten/texifyidea/run/sumatra/SumatraConversation.kt
src/nl/hannahsten/texifyidea/settings/sdk/DockerSdk.kt
src/nl/hannahsten/texifyidea/settings/sdk/NativeTexliveSdk.kt
src/nl/hannahsten/texifyidea/util/Log.kt

Fix #2525
Sumatra changed their registry key, and the backup check using that sumatra is in PATH was broken on our side.

Fix check if Sumatra is installed

---

src/nl/hannahsten/texifyidea/run/compiler/LatexCompiler.kt
src/nl/hannahsten/texifyidea/run/latex/LatexCommandLineState.kt
src/nl/hannahsten/texifyidea/run/latex/LatexDistributionType.kt
src/nl/hannahsten/texifyidea/run/latex/LatexRunConfiguration.kt

Fix #2530
* Fix isMiktex() check to include project sdk

Fix default working directory for bibtex when using miktex

---

src/nl/hannahsten/texifyidea/index/file/LatexIndexableSetContributor.kt
src/nl/hannahsten/texifyidea/settings/sdk/NativeTexliveSdk.kt
src/nl/hannahsten/texifyidea/settings/sdk/TexliveSdk.kt
src/nl/hannahsten/texifyidea/util/SystemEnvironment.kt

See #2387
* Resolve symlinks and update suggested homepaths

Resolve symlinks when suggesting home paths for texlive sdk

---

build.gradle.kts
src/nl/hannahsten/texifyidea/documentation/LatexDocumentationProvider.kt
src/nl/hannahsten/texifyidea/index/file/LatexIndexableSetContributor.kt
src/nl/hannahsten/texifyidea/remotelibraries/mendeley/MendeleyAuthenticator.kt

Fix #2548 IOOB exception
Fix #2553 Nullpointer in LatexDocumentationProvider
Fix #2551 LinkageError on the PDF Viewer plugin when using a dependency on Netty

Fix index out of bounds and NPE in LatexDocumentationProvider and LinkageError for Netty

---

src/nl/hannahsten/texifyidea/structure/latex/LatexNewCommandPresentation.kt

Fix #2559 
Put this in the document and open the structure view.
```latex
\NewDocumentCommand{test}{}
```

Fix IOOB when getting definition of new command

---

src/nl/hannahsten/texifyidea/settings/sdk/TexliveSdk.kt

Fix path filter in TexliveSdk

---

src/nl/hannahsten/texifyidea/settings/sdk/DockerSdk.kt
src/nl/hannahsten/texifyidea/settings/sdk/DockerSdkConfigurable.kt

Fix #2556
[Oops](https://xkcd.com/1691/).

Do not cache docker image list

---

resources/META-INF/plugin.xml
src/nl/hannahsten/texifyidea/ui/DetexifyToolWindowFactory.kt
src/nl/hannahsten/texifyidea/ui/remotelibraries/RemoteLibrariesToolWindowFactory.kt
src/nl/hannahsten/texifyidea/ui/symbols/SymbolToolWindowFactory.kt
src/nl/hannahsten/texifyidea/util/Projects.kt

Fix #2566
The `ModuleManager.getModules()` is apparently broken now (returns empty list), so I added a check if any latex run configurations are present.
Download: https://plugins.jetbrains.com/files/9473/205515/TeXiFy-IDEA-0.7.21-alpha.2.zip

Improve check if tool windows should be shown

---

src/nl/hannahsten/texifyidea/completion/LatexCommandsAndEnvironmentsCompletionProvider.kt

In #2517 I had removed the cache because I thought it wasn't necessary anymore, but on texlive-full it is, so I put that back. Of course I left the actual performance improvement in.
https://plugins.jetbrains.com/files/9473/207659/TeXiFy-IDEA-0.7.21-alpha.5.zip

Add back completion lookupelement cache

---

src/nl/hannahsten/texifyidea/settings/sdk/DockerSdkConfigurable.kt

Fix #2555, I hope.
* Show docker error message to user in case we cannot find any images.
```
systemctl stop docker
systemctl stop docker.socket
```

Propagate docker error message to user

---

src/nl/hannahsten/texifyidea/lang/commands/LatexBiblatexCommand.kt

Fix typo in biblatex command

---

.github/workflows/main.yml

Fix SARIF upload on master branch.
See https://github.com/github/codeql-action/issues/796

Workaround for bug in codeql-action

---

src/nl/hannahsten/texifyidea/action/DeleteGeneratedFiles.kt

Ignore InvalidVirtualFileAccessException when deleting files

---

.github/workflows/main.yml
build.gradle.kts
gradle.properties
resources/META-INF/plugin.xml
src/nl/hannahsten/texifyidea/settings/codestyle/BibtexCodeStyleSettingsProvider.kt
src/nl/hannahsten/texifyidea/settings/codestyle/LatexCodeStyleSettingsProvider.kt
test/nl/hannahsten/texifyidea/formatting/TableAlignTest.kt
test/nl/hannahsten/texifyidea/inspections/latex/NonAsciiCharactersInspectionTest.kt

Update to Java 17 as required: https://blog.jetbrains.com/platform/2022/08/intellij-project-migrates-to-java-17/

Compatibility for idea 223

---

src/nl/hannahsten/texifyidea/inspections/TexifyRegexInspection.kt
src/nl/hannahsten/texifyidea/psi/LatexPsiHelper.kt
src/nl/hannahsten/texifyidea/util/Log.kt
src/nl/hannahsten/texifyidea/util/Projects.kt

Fix #2675 run configurations of disposed project
Fix #2668 regex text range
Fix #2661 improve logging

Fix exceptions

---

build.gradle.kts
src/nl/hannahsten/texifyidea/reference/InputFileReference.kt
src/nl/hannahsten/texifyidea/util/LatexmkRcFileFinder.kt
test/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexFileNotFoundInspectionTest.kt
test/resources/inspections/latex/filenotfound/latexmkrc/.latexmkrc
test/resources/inspections/latex/filenotfound/latexmkrc/main.tex
test/resources/inspections/latex/filenotfound/latexmkrc/subdir1/mypackage2.sty

Fix #2635
* Use a lot of guesses to try and find a latexmkrc file
* Assumes TEXINPUTS is set as in the test
Magic comments could be implemented later if necessary.
See test files

Search latexmkrc files for TEXINPUTS

---

resources/META-INF/extensions/annotators.xml
src/nl/hannahsten/texifyidea/highlighting/LatexAnnotator.kt
src/nl/hannahsten/texifyidea/highlighting/TextidoteAnnotator.kt
src/nl/hannahsten/texifyidea/settings/TexifyConfigurable.kt
src/nl/hannahsten/texifyidea/settings/TexifySettings.kt
src/nl/hannahsten/texifyidea/settings/TexifySettingsState.kt
src/nl/hannahsten/texifyidea/util/SystemEnvironment.kt

Fix #2596
* Add Textidote annotator
* Add global settings to enable and to configure options
Install Textidote, enable in settings and open https://github.com/sylvainhalle/textidote/blob/master/example.tex

Add Textidote integration

---

.github/workflows/main.yml
gradle.properties
src/nl/hannahsten/texifyidea/highlighting/LatexAnnotator.kt

Fix #2743, not 100% sure but I think this fixes it.

Avoid creating an Annotation without calling the create() method

---

.github/workflows/main.yml

Not sure if this works, but I need to create a PR to test this fix

Fix codeql-action sarif upload

---

build.gradle.kts
src/nl/hannahsten/texifyidea/editor/LatexParagraphFillHandler.kt
src/nl/hannahsten/texifyidea/index/file/LatexExternalPackageInclusionDataIndexer.kt
src/nl/hannahsten/texifyidea/index/file/LatexExternalPackageInclusionIndex.kt
src/nl/hannahsten/texifyidea/settings/sdk/MiktexLinuxSdk.kt

* Add default style files path
* Fix regex

Add style and class files to MiKTeX Linux SDK package inclusion index

---

.github/workflows/main.yml
qodana.yaml

Update qodana image

---

resources/META-INF/extensions/intentions.xml

Fix #2798
Interestingly, looks like this has been there for years but somehow only shows up after the latest PR

Fix description directory of LatexAddLabelToCommandIntention

---

src/nl/hannahsten/texifyidea/util/magic/PatternMagic.kt

A semicolon is not a sentence end

---

src/nl/hannahsten/texifyidea/run/latex/ui/LatexSettingsEditor.kt

Fix #2799
I don't understand, but looks like we've had this issue before.

Make sure enableSumatraPath is initialized

---

CHANGELOG.md
src/nl/hannahsten/texifyidea/intentions/LatexLanguageInjectionIntention.kt
src/nl/hannahsten/texifyidea/psi/LatexLanguageInjector.kt

Do not suggest to inject languages without a parser definition

---

.github/workflows/main.yml
src/nl/hannahsten/texifyidea/intentions/LatexToggleSmartQuotesIntention.kt
src/nl/hannahsten/texifyidea/settings/TexifySettings.kt
src/nl/hannahsten/texifyidea/util/General.kt
src/nl/hannahsten/texifyidea/util/Projects.kt

Fix #2895
Fix #2896
Fix #2856 
Fix #2855 (well, ignored it)

Fix disposed project, too early call of applicationmanager and write action not in edt exceptions

---

CHANGELOG.md
build.gradle.kts
gradle.properties
src/nl/hannahsten/texifyidea/util/General.kt
src/nl/hannahsten/texifyidea/util/Packages.kt

Fix 'insert usepackage' in a different and hopefully better way

---

src/nl/hannahsten/texifyidea/util/Packages.kt

Run insertUsepackage in write action

---

src/nl/hannahsten/texifyidea/run/latex/LatexCommandLineState.kt

Fix #2950 
* Avoid running a synchronous refresh under read lock when generating a run configuration

Avoid running a synchronous refresh under read lock

---

src/nl/hannahsten/texifyidea/completion/pathcompletion/LatexGraphicsPathProvider.kt

Fix #2971
* Fixes no such element exception.

Fix no such element exception

---

CHANGELOG.md
build.gradle.kts

Fix #3014
* No idea, it's all magic to me. And Xerces hell, apparently.

Fix TranscoderException in equation preview

---

src/nl/hannahsten/texifyidea/inspections/latex/codematurity/LatexPrimitiveStyleInspection.kt
test/nl/hannahsten/texifyidea/inspections/latex/codematurity/LatexPrimitiveStyleInspectionTest.kt

Fix #3012
Run the quick fix on the following examples (they have been added as tests as well):
```latex
\it test
```
```latex
\it
```

Avoid IncorrectOperationException, fixes #3012

---

CHANGELOG.md
build.gradle.kts
src/nl/hannahsten/texifyidea/util/LatexmkRcFileFinder.kt

Fix #2991 accessing invalid directory

---

.github/FUNDING.yml
src/nl/hannahsten/texifyidea/editor/typedhandlers/LatexTypedHandler.kt
src/nl/hannahsten/texifyidea/index/IndexUtilBase.kt

Fix #3036 IOOB
Fix #3049, do not get index for default project

Fix IndexOutOfBoundsException in insertDisplayMathClose

---

src/nl/hannahsten/texifyidea/index/BibtexEntryIndex.kt

Fix unnecessary non-null assertion

---

CHANGELOG.md
build.gradle.kts
gradle.properties
src/nl/hannahsten/texifyidea/action/preview/PreviewAction.kt
src/nl/hannahsten/texifyidea/action/preview/PreviewToolWindowFactory.kt
src/nl/hannahsten/texifyidea/run/LatexProjectTaskRunner.kt
src/nl/hannahsten/texifyidea/settings/sdk/LatexProjectSdkSetupValidator.kt

* Remove usages of removed module type
* Replace deprecated api usage for creating preview tool window

Replace deprecated api usages (preview tool window and module type)

---

src/nl/hannahsten/texifyidea/modules/LatexModuleType.kt
src/nl/hannahsten/texifyidea/run/LatexProjectTaskRunner.kt
src/nl/hannahsten/texifyidea/util/Projects.kt

Improve LatexProjectTaskRunner canRun check to only build if we are not interfering with other languages

---

src/nl/hannahsten/texifyidea/util/Packages.kt

Fix #3083
Cause as yet unknown

Avoid NPE in insertUsepackage

---

.github/actions/insert-youtrack-link/index.js
.github/actions/insert-youtrack-link/node_modules/.package-lock.json
.github/actions/insert-youtrack-link/package-lock.json
.github/actions/insert-youtrack-link/package.json
.github/workflows/youtrack.yml

Fix [TEX-166](https://texify-idea.myjetbrains.com/youtrack/issue/TEX-166)

Update octokit api for insert-youtrack-link action

---

.github/workflows/main.yml

https://youtrack.jetbrains.com/issue/QD-6119/Pull-request-workflow-is-not-working-when-files-are-removed-from-git

Disable broken Qodana pull request mode

---

src/nl/hannahsten/texifyidea/run/latex/LatexOutputPath.kt

Index access should be done in a read action

---

src/nl/hannahsten/texifyidea/highlighting/LatexAnnotator.kt
src/nl/hannahsten/texifyidea/lang/commands/LatexGenericMathCommand.kt

Fix #3120 hopefully, can't think of any other reason right now. See #2835 and #2747

Fix abandoned annotationbuilder

---

src/nl/hannahsten/texifyidea/inspections/latex/typesetting/spacing/LatexNonBreakingSpaceInspection.kt
test/nl/hannahsten/texifyidea/inspections/latex/typesetting/spacing/LatexNonBreakingSpaceInspectionTest.kt

Fix #3122
all tests passed locally

Remove False Alarm Non-Breaking Whitespace

---

src/nl/hannahsten/texifyidea/settings/conventions/LabelConvention.kt
src/nl/hannahsten/texifyidea/settings/conventions/TexifyConventionsConfigurable.kt
src/nl/hannahsten/texifyidea/settings/conventions/TexifyConventionsSettings.kt

Closes #3022
I got most of the way there. I need to do more testing and commenting and cleaning but the idea is that you can now add now commands/environments or even remove them.

Allow custom label environments

---

CHANGELOG.md
build.gradle.kts
gradle.properties
gradle/wrapper/gradle-wrapper.properties
resources/META-INF/extensions/application-settings.xml

Specify displayName for TexifyConfigurable

---

resources/META-INF/extensions/application-settings.xml

Second half of #3148 
Fix #3164

Specify displayName for conventions settings

---

CHANGELOG.md
gradle.properties
src/nl/hannahsten/texifyidea/reference/InputFileReference.kt

Trim quotes from TEXINPUTS

---

src/nl/hannahsten/texifyidea/reference/InputFileReference.kt

Improve performance of input file reference

---

src/nl/hannahsten/texifyidea/action/library/AddLibraryAction.kt
src/nl/hannahsten/texifyidea/action/library/SyncLibraryAction.kt
src/nl/hannahsten/texifyidea/remotelibraries/RemoteBibLibrary.kt
src/nl/hannahsten/texifyidea/run/latex/LatexRunConfiguration.kt

Fix initialization issue in remote library tool window

---

build.gradle.kts

Temporarily disabled until I find a solution

Disable SumatraPDF forward search

---

CHANGELOG.md
build.gradle.kts
gradle.properties
src/nl/hannahsten/texifyidea/intentions/LatexAddLabelIntention.kt

Improve logging for add label intention

---

src/nl/hannahsten/texifyidea/editor/folding/LatexCodeFoldingOptionsProvider.kt
src/nl/hannahsten/texifyidea/editor/folding/LatexCodeFoldingSettings.kt
src/nl/hannahsten/texifyidea/editor/folding/LatexEnvironmentFoldingBuilder.kt
src/nl/hannahsten/texifyidea/editor/folding/LatexEscapedSymbolFoldingBuilder.kt
src/nl/hannahsten/texifyidea/editor/folding/LatexFootnoteFoldingBuilder.kt
src/nl/hannahsten/texifyidea/editor/folding/LatexMathSymbolFoldingBuilder.kt
src/nl/hannahsten/texifyidea/editor/folding/LatexSectionFoldingBuilder.kt
src/nl/hannahsten/texifyidea/editor/folding/LatexSymbolFoldingBuilder.kt

Add folding settings for all folding builders

---

src/nl/hannahsten/texifyidea/structure/bibtex/BibtexStructureViewElement.kt

Fix #3390
Somehow this is the first time this 7 year old assertion is triggered, no idea why, maybe this logging will help.

Improve logging for bibtex structure view

---

.github/workflows/docs.yml

Reverts Hannah-Sten/TeXiFy-IDEA#3418

Revert "Bump actions/deploy-pages from 1 to 4"

---

.github/workflows/docs.yml

Reverts Hannah-Sten/TeXiFy-IDEA#3417

Revert "Bump actions/upload-artifact from 3 to 4"

---

.github/workflows/docs.yml

Reverts Hannah-Sten/TeXiFy-IDEA#3416

Revert "Bump actions/checkout from 3 to 4"

---

.github/workflows/docs.yml

Reverts Hannah-Sten/TeXiFy-IDEA#3415

Revert "Bump actions/download-artifact from 1 to 4"

---

.github/workflows/docs.yml

Reverts Hannah-Sten/TeXiFy-IDEA#3414

Revert "Bump actions/upload-pages-artifact from 1 to 3"

---

src/nl/hannahsten/texifyidea/index/file/LatexDocsRegexer.kt
src/nl/hannahsten/texifyidea/index/file/LatexExternalCommandDataIndexer.kt
src/nl/hannahsten/texifyidea/lang/Environment.kt
src/nl/hannahsten/texifyidea/lang/commands/LatexCommand.kt
src/nl/hannahsten/texifyidea/lang/commands/LatexGenericRegularCommand.kt
test/nl/hannahsten/texifyidea/index/file/LatexExternalCommandDataIndexerTest.kt

Improved support for pythontex documentation
cherry-picked old commit

Handle braced \DescribeMacro definitions with included arguments

---

Writerside/topics/Tool-Windows.md
resources/META-INF/extensions/tool-windows.xml
src/nl/hannahsten/texifyidea/TeXception.kt
src/nl/hannahsten/texifyidea/action/library/AddBibtexFileAction.kt
src/nl/hannahsten/texifyidea/action/library/AddLibraryAction.kt
src/nl/hannahsten/texifyidea/action/library/SyncLibraryAction.kt
src/nl/hannahsten/texifyidea/remotelibraries/BibtexFileLibrary.kt
src/nl/hannahsten/texifyidea/remotelibraries/RemoteBibLibrary.kt
src/nl/hannahsten/texifyidea/remotelibraries/RemoteBibLibraryFactory.kt
src/nl/hannahsten/texifyidea/remotelibraries/mendeley/MendeleyLibrary.kt
src/nl/hannahsten/texifyidea/remotelibraries/zotero/ZoteroLibrary.kt
src/nl/hannahsten/texifyidea/util/Bibtex.kt
src/nl/hannahsten/texifyidea/util/CredentialAttributes.kt
src/nl/hannahsten/texifyidea/util/parser/Psi.kt

Fix #2744
* Add remote bib library for local bib files
* Refactor some methods to be more generic than http-based remote bib libraries

Support local bibtex files in the remote libraries tool window

---

build.gradle.kts
gradle.properties
src/nl/hannahsten/texifyidea/run/latex/ui/LatexSettingsEditor.kt
src/nl/hannahsten/texifyidea/util/General.kt

Fix #3457
* getting content root cannot be done on EDT

Resolve main file in background when editing run configuration

---

build.gradle.kts
src/nl/hannahsten/texifyidea/structure/bibtex/BibtexStructureViewTagElement.kt
src/nl/hannahsten/texifyidea/util/Bibtex.kt

Fix #3512 
* Read action for bibtex structure view tag element,

Read and write actions

---

Writerside/topics/Run-configuration-settings.md
src/nl/hannahsten/texifyidea/run/compiler/LatexCompiler.kt
src/nl/hannahsten/texifyidea/run/latex/LatexDistributionType.kt
src/nl/hannahsten/texifyidea/run/latex/LatexRunConfiguration.kt
src/nl/hannahsten/texifyidea/settings/sdk/DockerSdk.kt
src/nl/hannahsten/texifyidea/settings/sdk/LatexSdk.kt
src/nl/hannahsten/texifyidea/settings/sdk/LatexSdkUtil.kt
src/nl/hannahsten/texifyidea/settings/sdk/MiktexLinuxSdk.kt
src/nl/hannahsten/texifyidea/settings/sdk/MiktexWindowsSdk.kt
src/nl/hannahsten/texifyidea/settings/sdk/TectonicSdk.kt
src/nl/hannahsten/texifyidea/settings/sdk/TexliveSdk.kt

Fix #3157
* Similar to miktex docker image

Support TeX Live docker image

---

src/nl/hannahsten/texifyidea/intentions/LatexToggleSmartQuotesIntention.kt
src/nl/hannahsten/texifyidea/run/linuxpdfviewer/InternalPdfViewer.kt

Avoid calling services during class initialization

---

src/nl/hannahsten/texifyidea/completion/LatexExternalCommandsIndexCache.kt

Don't fill cache from index in dumb mode

---

src/nl/hannahsten/texifyidea/completion/LatexBibliographyReferenceProvider.kt

Ensure consistent projects for bibtex lookup elements

---

build.gradle.kts

Fix #3654, I think: reproduced but didn't get it anymore
Was accidentally removed in #3688

Re-apply kotlin serialization plugin

---

CHANGELOG.md
Writerside/topics/BibTeX.md
Writerside/topics/TeXiFy-settings.md
Writerside/topics/Tool-Windows.md
src/nl/hannahsten/texifyidea/completion/handlers/LatexReferenceInsertHandler.kt
src/nl/hannahsten/texifyidea/settings/TexifyConfigurable.kt
src/nl/hannahsten/texifyidea/settings/TexifySettings.kt
src/nl/hannahsten/texifyidea/settings/TexifySettingsState.kt

Add setting to disable auto-import of bibtex entries from remote libraries

---

CHANGELOG.md
gradle.properties
src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexFileNotFoundInspection.kt
src/nl/hannahsten/texifyidea/inspections/latex/redundancy/LatexMultipleIncludesInspection.kt
src/nl/hannahsten/texifyidea/reference/InputFileReference.kt
test/nl/hannahsten/texifyidea/reference/InputFileReferenceTest.kt
test/resources/reference/simplesubfile/main.tex
test/resources/reference/simplesubfile/subdir/onedown-after.tex
test/resources/reference/simplesubfile/subdir/onedown.tex

* Fix rename of files when using subfiles
* Fix incorrect 'package already included' warning for the subfiles package

Improve subfiles support

---

CHANGELOG.md
src/nl/hannahsten/texifyidea/index/file/LatexExternalCommandDataIndexer.kt
test/nl/hannahsten/texifyidea/index/file/LatexExternalCommandDataIndexerTest.kt

Add DeclareMathSymbol to indexed command definitions

---

CHANGELOG.md
src/nl/hannahsten/texifyidea/index/IndexUtilBase.kt

Fix 'missing import' false positive in subfiles

---

CHANGELOG.md
gradle.properties
src/nl/hannahsten/texifyidea/ui/CreateFileDialog.kt

* Do not format existing directories in the given path in the file creation quickfix dialog

Improve 'create file' quickfix

---

CHANGELOG.md
src/nl/hannahsten/texifyidea/action/wizard/graphic/InsertGraphicWizardAction.kt
src/nl/hannahsten/texifyidea/util/Documents.kt
src/nl/hannahsten/texifyidea/util/files/Files.kt
src/nl/hannahsten/texifyidea/util/files/RootFile.kt

Fix relative path conversion in graphics insertion wizard 

---

CHANGELOG.md
gradle.properties
src/nl/hannahsten/texifyidea/util/CommandRunner.kt

Ignore "stream closed"

---

CHANGELOG.md
Writerside/topics/Running-a-LaTeX-file.md
Writerside/topics/TeXiFy-settings.md
src/nl/hannahsten/texifyidea/editor/autocompile/AutoCompileDoneListener.kt
src/nl/hannahsten/texifyidea/editor/autocompile/AutoCompileHandler.kt
src/nl/hannahsten/texifyidea/editor/autocompile/AutoCompileState.kt
src/nl/hannahsten/texifyidea/editor/autocompile/AutoCompileVfsListener.kt
src/nl/hannahsten/texifyidea/settings/TexifyConfigurable.kt
src/nl/hannahsten/texifyidea/settings/TexifySettings.kt
src/nl/hannahsten/texifyidea/settings/TexifySettingsState.kt

Convert autocompile settings to combobox and add setting to disable in power save mode

---

CHANGELOG.md
src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexUnicodeInspection.kt
src/nl/hannahsten/texifyidea/inspections/latex/typesetting/spacing/LatexNonBreakingSpaceInspection.kt
src/nl/hannahsten/texifyidea/lang/commands/LatexSiunitxCommand.kt
src/nl/hannahsten/texifyidea/run/linuxpdfviewer/evince/EvinceInverseSearchListener.kt
src/nl/hannahsten/texifyidea/util/parser/Psi.kt
test/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexUnicodeInspectionTest.kt

Fix #3813 invalid element
Fix #3795 \micro
Fix #3818 "this.dbus" is null
Fix #3793 nbsp \nameref

Various small fixes

---

resources/META-INF/extensions/inspections/latex/probablebugs/packages.xml
src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/packages/LatexPackageUpdateInspection.kt

Fix package update cache

---

src/nl/hannahsten/texifyidea/util/CommandRunner.kt

Ignore closed stream

---

src/nl/hannahsten/texifyidea/completion/LatexExternalCommandsIndexCache.kt

Use smart read action for index access

---

Writerside/topics/External-tools.md
src/nl/hannahsten/texifyidea/run/latex/externaltool/ExternalToolCommandLineState.kt
src/nl/hannahsten/texifyidea/run/latex/externaltool/ExternalToolRunConfiguration.kt
src/nl/hannahsten/texifyidea/run/latex/externaltool/ExternalToolSettingsEditor.kt

Add environment variables to external tool run config

---

CHANGELOG.md
gradle.properties
src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/packages/LatexPackageNotInstalledInspection.kt
src/nl/hannahsten/texifyidea/util/TexLivePackages.kt

Fix a performance problem caused by cache misses in "Package not installed" inspection

---

src/nl/hannahsten/texifyidea/util/Projects.kt

Fix #3883 
* Fixed a bug in getting the focused editor.
Have multiple editors open in split view, paste an image in one of them.

Fixed getting the currently active text editor, fixes #3883

---

CHANGELOG.md
src/nl/hannahsten/texifyidea/reference/InputFileReference.kt

Fix invalid element exception

---

CHANGELOG.md
src/nl/hannahsten/texifyidea/lang/alias/AliasManager.kt
src/nl/hannahsten/texifyidea/lang/alias/CommandManager.kt
src/nl/hannahsten/texifyidea/util/CommandAlias.kt
src/nl/hannahsten/texifyidea/util/General.kt
test/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexFileNotFoundInspectionTest.kt

Improve performance of alias manager

---

CHANGELOG.md
gradle.properties
src/nl/hannahsten/texifyidea/editor/autocompile/AutoCompileDoneListener.kt
src/nl/hannahsten/texifyidea/editor/autocompile/AutoCompileVfsListener.kt
src/nl/hannahsten/texifyidea/run/latex/LatexCommandLineState.kt

Avoid possible freeze when autocompile on save is enabled

---

CHANGELOG.md
Writerside/topics/Tool-Windows.md
Writerside/topics/Troubleshooting.md
src/nl/hannahsten/texifyidea/action/preview/JlatexmathPreviewer.kt
src/nl/hannahsten/texifyidea/action/preview/PreviewForm.kt

Fix https://github.com/Hannah-Sten/TeXiFy-IDEA/discussions/3201#discussioncomment-12451338

Remove labels for jlatexmath preview and add hint to error output

---

CHANGELOG.md
gradle.properties
src/nl/hannahsten/texifyidea/index/file/LatexExternalEnvironmentDataIndexer.kt

See #3947 and https://github.com/josephwright/beamer/blob/fef8f1b049516cebfc2eda4ca34e64cf17e544ec/base/beamerbaseframecomponents.sty#L207

Allow <> after newenvironment to find beamer environments

---

CHANGELOG.md
src/nl/hannahsten/texifyidea/util/files/ReferencedFileSetCache.kt

Fix #3955 read action in ReferencedFileSetCache.kt

---

CHANGELOG.md
src/nl/hannahsten/texifyidea/index/file/LatexExternalPackageInclusionCache.kt
src/nl/hannahsten/texifyidea/structure/filter/CommandDefinitionFilter.kt
src/nl/hannahsten/texifyidea/structure/filter/IncludesFilter.kt
src/nl/hannahsten/texifyidea/structure/filter/LabelFilter.kt
src/nl/hannahsten/texifyidea/structure/latex/LatexIncludePresentation.kt
src/nl/hannahsten/texifyidea/structure/latex/LatexPresentationFactory.kt
src/nl/hannahsten/texifyidea/structure/latex/LatexStructureViewElement.kt
src/nl/hannahsten/texifyidea/util/labels/ProjectLabels.kt

Fix #3965
* Improve performance of the file structure popup
* Add filters to filter out some elements by default in the file structure popup
* Make sure the external packagge inclusion cache refills are not attempted unnecessarily

Improve the file structure popup

---

CHANGELOG.md
gradle.properties
src/nl/hannahsten/texifyidea/action/wizard/graphic/InsertGraphicWizardAction.kt
src/nl/hannahsten/texifyidea/editor/pasteproviders/ImagePasteProvider.kt

Fix graphic insertion wizard not opening after pasting an image from the clipboard

---

CHANGELOG.md
build.gradle.kts
resources/META-INF/plugin.xml
src/nl/hannahsten/texifyidea/action/DeleteGeneratedFiles.kt

Disable action to remove generated files

---

src/nl/hannahsten/texifyidea/lang/alias/AliasManager.kt
test/nl/hannahsten/texifyidea/lang/CommandManagerTest.kt

Fix synchronization when registering aliases

---

CHANGELOG.md
src/nl/hannahsten/texifyidea/structure/latex/LatexStructureViewElement.kt
src/nl/hannahsten/texifyidea/structure/latex/SectionNumbering.kt

Fix index out of bounds SectionNumbering

---

CHANGELOG.md
src/nl/hannahsten/texifyidea/run/linuxpdfviewer/evince/EvinceInverseSearchListener.kt

Delay starting dbus communication

---

CHANGELOG.md
build.gradle.kts
gradle.properties
src/nl/hannahsten/texifyidea/grammar/Latex.bnf
src/nl/hannahsten/texifyidea/grammar/LatexParserDefinition.kt
src/nl/hannahsten/texifyidea/inspections/grazie/LatexTextExtractor.kt
src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/LatexUnicodeInspection.kt
src/nl/hannahsten/texifyidea/inspections/latex/typesetting/LatexCollapseCiteInspection.kt
src/nl/hannahsten/texifyidea/psi/impl/LatexKeyValKeyImplMixin.kt
test/nl/hannahsten/texifyidea/inspections/grazie/GrazieInspectionTest.kt
test/nl/hannahsten/texifyidea/testutils/Common.kt

Fix #3998
Parser change: no Content in group anymore

Do not run grammar checks in graphicspath argument

---

CHANGELOG.md
src/nl/hannahsten/texifyidea/editor/autocompile/AutoCompileState.kt

Make sure not to start a new autocompile run if a previous one is still running

---

CHANGELOG.md
src/nl/hannahsten/texifyidea/run/latex/LatexCommandLineState.kt

Always create output directory if it does not exist

---

src/nl/hannahsten/texifyidea/index/BibtexEntryIndex.kt
src/nl/hannahsten/texifyidea/index/IndexUtilBase.kt
src/nl/hannahsten/texifyidea/index/file/LatexIndexableSetContributor.kt

Fix #4008 
Fix #4017 
Fix #4026 
Fix #4024

Fix invalid stub exceptions

---

src/nl/hannahsten/texifyidea/run/linuxpdfviewer/evince/EvinceInverseSearchListener.kt
src/nl/hannahsten/texifyidea/util/files/PsiFile.kt

Retry registering dbus

---

CHANGELOG.md
src/nl/hannahsten/texifyidea/index/IndexUtilBase.kt
src/nl/hannahsten/texifyidea/inspections/grazie/LatexTextExtractor.kt
src/nl/hannahsten/texifyidea/run/latex/LatexCommandLineState.kt

exceptions

---

CHANGELOG.md
src/nl/hannahsten/texifyidea/run/bibtex/BibtexCommandLineState.kt
src/nl/hannahsten/texifyidea/run/compiler/LatexCompiler.kt
src/nl/hannahsten/texifyidea/settings/sdk/LatexSdkUtil.kt
src/nl/hannahsten/texifyidea/util/SystemEnvironment.kt

Replace wsl command with wsl --exec

---

CHANGELOG.md
src/nl/hannahsten/texifyidea/lang/LatexPackage.kt
src/nl/hannahsten/texifyidea/lang/commands/LatexGenericRegularCommand.kt
src/nl/hannahsten/texifyidea/reference/InputFileReference.kt
src/nl/hannahsten/texifyidea/util/magic/CommandMagic.kt

Add support for file references for the tikzfig command, fix #4050

---

CHANGELOG.md
src/nl/hannahsten/texifyidea/lang/alias/AliasManager.kt
src/nl/hannahsten/texifyidea/util/CommandRunner.kt

Fix ConcurrentModificationException in AliasManager

---

CHANGELOG.md
src/nl/hannahsten/texifyidea/util/parser/LatexCommandsImplMixinUtil.kt

Fix IllegalArgumentException in LatexCommandsImplMixinUtil

---

src/nl/hannahsten/texifyidea/action/analysis/WordCountAction.kt
src/nl/hannahsten/texifyidea/action/preview/InkscapePreviewer.kt
src/nl/hannahsten/texifyidea/action/reformat/ExternalReformatAction.kt
src/nl/hannahsten/texifyidea/highlighting/TextidoteAnnotator.kt
src/nl/hannahsten/texifyidea/run/bibtex/BibtexCommandLineState.kt
src/nl/hannahsten/texifyidea/run/latex/LatexCommandLineState.kt
src/nl/hannahsten/texifyidea/run/latex/externaltool/ExternalToolCommandLineState.kt
src/nl/hannahsten/texifyidea/run/makeindex/MakeindexCommandLineState.kt
src/nl/hannahsten/texifyidea/run/sumatra/SumatraAvailabilityChecker.kt
src/nl/hannahsten/texifyidea/util/CommandRunner.kt
src/nl/hannahsten/texifyidea/util/Strings.kt

See https://github.com/Hannah-Sten/TeXiFy-IDEA/pull/4067#discussion_r2117855517

Replace deprecated withWorkDirectory(File) by withWorkingDirectory(Path)

---

CHANGELOG.md
gradle.properties
src/nl/hannahsten/texifyidea/index/IndexUtilBase.kt
src/nl/hannahsten/texifyidea/index/file/LatexExternalPackageInclusionCache.kt
src/nl/hannahsten/texifyidea/inspections/latex/probablebugs/packages/LatexPackageCouldNotBeFound.kt
src/nl/hannahsten/texifyidea/util/General.kt
src/nl/hannahsten/texifyidea/util/files/FileSet.kt
src/nl/hannahsten/texifyidea/util/files/ReferencedFileSetCache.kt
src/nl/hannahsten/texifyidea/util/files/RootFile.kt

* Don't use index cache when checking for root files cache refresh
* Always trigger a cache refresh in background, previously this was done implicitly by the check mentioned in the previous point

Improve root files cache

---

CHANGELOG.md
gradle.properties
src/nl/hannahsten/texifyidea/settings/sdk/NativeTexliveSdk.kt
src/nl/hannahsten/texifyidea/util/files/LatexPackageLocationCache.kt

Avoid a possible UI freeze when finding files to index for native TeX Live installations

---

src/nl/hannahsten/texifyidea/editor/MathEnvironmentEditor.kt
src/nl/hannahsten/texifyidea/reference/InputFileReference.kt
src/nl/hannahsten/texifyidea/run/latex/LatexCommandLineState.kt
src/nl/hannahsten/texifyidea/run/latex/LatexRunConfiguration.kt
src/nl/hannahsten/texifyidea/util/Packages.kt
src/nl/hannahsten/texifyidea/util/files/PsiFile.kt

I saw some cases with false positives due to information from the index not being up to date, not sure if this helps.
Although it looks like the psi itself is confused:

Do not use index cache for some inspections

---

CHANGELOG.md
src/nl/hannahsten/texifyidea/structure/latex/LatexStructureViewElement.kt
src/nl/hannahsten/texifyidea/structure/latex/SectionNumbering.kt

Romans had no zero

---

CHANGELOG.md
gradle.properties
src/nl/hannahsten/texifyidea/grammar/LatexLexer.flex
test/nl/hannahsten/texifyidea/psi/LatexParserTest.kt

Fix parser issue from MnSymbol

Add hbox to commands that switch math to text mode

---

CHANGELOG.md
src/nl/hannahsten/texifyidea/editor/postfix/editable/LatexPostfixTemplateEditor.kt
src/nl/hannahsten/texifyidea/ui/DetexifyToolWindowFactory.kt
src/nl/hannahsten/texifyidea/ui/remotelibraries/RemoteLibrariesToolWindowFactory.kt
src/nl/hannahsten/texifyidea/ui/symbols/SymbolToolWindowFactory.kt
src/nl/hannahsten/texifyidea/util/Projects.kt

containsFileOfType requires a read action

---

src/nl/hannahsten/texifyidea/gutter/LatexNavigationGutter.kt
src/nl/hannahsten/texifyidea/run/latex/LatexCommandLineState.kt
src/nl/hannahsten/texifyidea/util/files/FileSet.kt

Fix index not ready and valid files check

---

CHANGELOG.md
src/nl/hannahsten/texifyidea/run/latex/logtab/LatexOutputListener.kt

Fix https://github.com/FirstTimeInForever/intellij-pdf-viewer/issues/106

Automatically reload pdf when using latexmk continuous update
